### ISSUE TITLE
Problem: AIP status in dashboard does not update after deletion is requested

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#1014]
**Expected behaviour**

As per the [documentation](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/archival-storage/archival-storage/#delete-aip), when a user requests deletion of an AIP in the Archival Storage tab, the status of the AIP should change from "Stored" to "Deletion requested".

**Current behaviour**
The status of the AIP continues to be "Stored".

Based on anecdotal evidence from Artefactual staff, this seems to be a regression, though we're not sure when it last worked.

**Steps to reproduce**
Create an AIP deletion request from the Archival Storage tab.

**Your environment (version of Archivematica, operating system, other relevant details)**
1.10.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I've been working around here this week, so I decided to give this a quick look.

The problem is we removed [these couple of lines](https://github.com/artefactual/archivematica-storage-service/pull/474/files#diff-4d646faa433a8061cee8229b383a14f8L1687-L1691) that updated the package status after the deletion is requested. If I restore those lines the status works again:

![Screenshot_2019-11-29 Archivematica Dashboard - Archival storage](https://user-images.githubusercontent.com/560781/69847437-bf987980-123c-11ea-8608-e4c101a50291.png)

This also affects the Packages table in the Storage Service.

I couldn't figure out in the https://github.com/artefactual/archivematica-storage-service/pull/474 conversation why the lines were removed, but found https://github.com/archivematica/Issues/issues/760 that might be related.

**Comment by ross-spencer** [comment]
I had a suspicion I caused this. That PR is also https://github.com/artefactual/archivematica-storage-service/pull/463 but the conversation doesn't illuminate further. I suspect it was partially a misunderstanding on my part of the interaction between the storage service and AM in this case which is unfortunate.

**Comment by sallain** [comment]
Just a note that this worked in 1.9.2!

**Comment by ablwr** [comment]
Working again in qa/1.x (1.11RC)!
