### ISSUE TITLE
Attempt restructure for compliance fails when creating SIP from appraisal

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#1031]
**Expected behaviour**
It should be possible to create a SIP from backlog files on the Appraisal tab

**Current behaviour**
The SIP is successfully submitted from the Appraisal tab but fails at the Attempt Restructure for compliance step with the following error:

```
ERROR: file information not found: no results found for arguments: {'removedtime__isnull': True, 'sip_id': '8ef77599-18be-4563-950c-51c57388d579', 'currentlocation': '%SIPDirectory%abroadcranethoma00craniala_0014.jpg'}
```

**Steps to reproduce**
Start a transfer with the OCRImage sample transfer, and send it to the backlog.

Find the transfer in the backlog on the Appraisal tab and use it to create a SIP (either via tags, or by creating a directory and dragging the jpg file into it).

Watch the steps in the ingest tab.

**Your environment (version of Archivematica, operating system, other relevant details)**
QA branches (last updated Dec 4th 2019) using docker compose environment on an Ubuntu 18.04 Virtualbox VM

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by helenst** [comment]
Having stepped through the code a little bit here - the restructure task attempts to find a File matching the given location and SIP ID. It seems that there is an entry matching the location, but the SIP ID is incorrect. (i.e. the `sip_id` on the `File` object does not matched the passed in `SIPUUID` value. I am not sure where the value on the `File` is coming from, I am not hugely familiar with how this is supposed to work though.

**Comment by helenst** [comment]
The `sip_id` on the `File` comes from `_create_arranged_sip` (`components.filesystem_ajax/views`). This is different from the SIP UUID passed into the microservice later on.

**Comment by helenst** [comment]
When 'create SIP' is invoked from the dashboard, a SIP is created in the watch directory:
```
Creating SIP: 1f481479-c323-4891-aa34-d82aaf7677b3 - %sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/48e/ 
```

When MCP server detects the SIP in the watched directory, `SIP.get_or_create_from_db_by_path` attempts to extract the SIP UUID from the path. But the path doesn't contain the SIP, so this fails and MCP server creates its own SIP with a different UUID:

```
INFO     WatchDirs 2020-01-02 14:46:19 packages:get_or_create_from_db_by_path:773:  Creating SIP ab06a28c-830f-48e8-a4f4-0f4d0d529e3d at %sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/48e/
```

The old SIP UUID remains on the `File` object, but the new one is passed into the microservice - hence the file is not found and the microservice errors.

This is just my analysis of what's happening, I'm not sure where we need to fix it! My instinct is that the SIP UUID should be included in the path when Dashboard first creates the SIP, so the same one can be used by MCP Server.

**Comment by helenst** [comment]
I'm not sure how to set up the SIP path here so that the UUID is included.
Currently it's just `sip-name` so no UUID included at all.
If I use `sip-name_sip-uuid` or similar, it will succeed but the UUID will be included in the name of the SIP which I don't know if we want.
If I use `sip-name/sip-uuid` the UUID won't be detected from the path (since MCP server just takes at whatever is directly inside the watch dir, i.e. the top level)
If I use `sip-uuid/sip-name` the name is lost altogether and the ingest fails. (not entirely sure why)

**Comment by helenst** [comment]
`sip_name`-`sip_uuid` appears to work (hyphen, not underscore :)

**Comment by ross-spencer** [comment]
@sromkey I'll add my name to this if that's okay? Looking through my tasks this morning I should be able to tackle it and as it will involve some coordination with Wellcome it makes sense while I follow up with zip transfers.

**Comment by ross-spencer** [comment]
I wanted to track back to where this was introduced to fully understand the context of a fix. 

In short, after arrangement is complete a new SIP is expected to have been created [here](https://github.com/artefactual/archivematica/blob/44eca798ff408ca727d239ac7515bafc28908662/src/dashboard/src/components/filesystem_ajax/views.py#L393-L396). Afterwards, the SIP gets sent to the `SIPsUnderConstruction` watched directory™, where previous behavior anticipated matching a path to that SIP in the database. But as @replaceafill points out [here](https://github.com/archivematica/Issues/issues/1092#issuecomment-585313063) we previously removed a [chunk of logic](https://github.com/artefactual/archivematica/blob/862c4cdd780f1a235f20716d8472d34d9b56094f/src/MCPServer/lib/archivematicaMCP.py#L162-L163) that allowed us to use the existing SIP UUID based on the path of the package's current directory, and so Archivematica proceeds to create a new SIP, and that causes the failure described by Helen.

The proposed fix from Helen is works well, it proposes that we fix this by appending our SIP uuid to a SIP path so that we can take advantage of logic that can strip that UUID to [match it against the DB](https://github.com/artefactual/archivematica/blob/44eca798ff408ca727d239ac7515bafc28908662/src/MCPServer/lib/server/packages.py#L753). E.g. if you tag your newly arranged SIP `sonntag` your SIP on the filesystem looks like `sonntag-{uuid}`. 

I would like to propose we revert the behavior introduced in https://github.com/artefactual/archivematica/commit/c1e7468ca30794504e8b2f09c352a1b216b1f880 however until much more of the logic across Archivematica is cleaned up and we can understand the full impact of the change in context, vs. adding something new now. https://github.com/artefactual/archivematica/pull/1572 is a proposed way to do that and as noted in the PR borrows from Douglas' work to do so.

**Comment by sallain** [comment]
This is now working!
