### ISSUE TITLE
Problem: Manual approval of transfers fails in qa/1.x

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1032]
**Expected behaviour**

When I select a transfer from the transfer browser I can elect not to `Approve automatically`. I can instead start it manually. 

**Current behaviour**

1. Select a transfer in `qa/1.x`.
2. Deselect `Approve automatically`.
3. Fill in the remainder of the form.
4. Start the transfer. 
5. It will not start. 

There is a stack trace in `archivematica-mcp-server`: 
```
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-12-13 13:38:31 decisions:run:51:  Running Approve standard transfer (package None)
archivematica-mcp-server_1       | ERROR    ThreadPoolExecutor-0_0 2019-12-13 13:38:31 _base:_invoke_callbacks:333:  exception calling callback for <Future at 0x7f62a41fc110 state=finished raised DoesNotExist>
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
archivematica-mcp-server_1       |     callback(self)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/queues.py", line 233, in _job_completed_callback
archivematica-mcp-server_1       |     next_job = future.result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
archivematica-mcp-server_1       |     return self.__get_result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
archivematica-mcp-server_1       |     result = self.fn(*self.args, **self.kwargs)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/jobs/decisions.py", line 53, in run
archivematica-mcp-server_1       |     self.package.reload()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
archivematica-mcp-server_1       |     _reraise(*exc)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
archivematica-mcp-server_1       |     result = f(*args, **kw)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 724, in reload
archivematica-mcp-server_1       |     transfer = models.Transfer.objects.get(uuid=self.uuid)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
archivematica-mcp-server_1       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
archivematica-mcp-server_1       |     self.model._meta.object_name
archivematica-mcp-server_1       | DoesNotExist: Transfer matching query does not exist.
```

**Steps to reproduce**

As above.

**Your environment (version of Archivematica, operating system, other relevant details)**

Running `qa/1.x` with the most recent commit: https://github.com/artefactual/archivematica/commit/82c624dd7ce3d0859d753e5774a9818f476d8d22 nb. the commit is incidental, it is expected this was broken some time before.

Confirmed as working in `1.10` on https://sandbox.archivematica.org/

**Additional context**

I'll just note, that being able to do this (e.g. for the use-case for which I discovered this) is useful for debug and understanding other mechanics in Archivematica as a dev. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Similar symptom of https://github.com/archivematica/Issues/issues/1024

**Comment by ross-spencer** [comment]
🙇 @replaceafill great spot! 

I'm not sure the best approach, whether to bring the two issues together, or keep them separate, what do you think? 

I have double-checked my work here just:

1. Clearing and rebuilding.
2. Attempting the same process above in a completely new Docker deploy, with no other work happening at the same time.

Same error. So perhaps this is a specific instantiation of #1024 that might be helpful?

**Comment by replaceafill** [comment]
@ross-spencer I'd keep them separate until we investigate (refine) one.

**Comment by sromkey** [comment]
I'm going to go ahead and milestone this as it's a regression.

**Comment by replaceafill** [comment]
I identified three scenarios where this problem shows:

- As explained in the **Current behaviour** section of this issue, by deselecting the `Approve automatically` checkbox when starting a transfer
- By calling the `/api/v2beta/package` endpoint setting `auto_approve: false`
- By moving content (directories or files) manually to a watched directory, for example to start transfers into the `watchedDirectories/activeTransfers` directories. I think this might be @jorikvankemenade's scenario in https://github.com/archivematica/Issues/issues/1024

In any of these scenarios the cause is the same: a transfer cannot be found in the database by the function that polls the watched directories [`MCPServer.lib.server.mcp.watched_dir_handler`](https://github.com/artefactual/archivematica/blob/7f11af7ba5eb120df44a992a37983e93916fe1cd/src/MCPServer/lib/server/mcp.py#L53-L75) in a separate thread.

The problem was introduced in the [package queue work](https://github.com/artefactual/archivematica/pull/1485), specifically in [this part](https://github.com/artefactual/archivematica/commit/75a6f8c133184020b66cebccc5e0048aaca9ab24#diff-0b78042c2f8b9ab7eeb857e453bef094L164) where the logic for *finding or creating units* was refactored. A [couple of helpers were introduced later](https://github.com/artefactual/archivematica/commit/d386aa975b2b649d360cb0276739a45c8a5ddd4c#diff-8e8c86aeb5830a77eb8857eab61f8c98R50-R60) for SIPs and DIPs, but not for Transfers from directories or files (zipped).

**Comment by jorikvankemenade** [comment]
The problem in #1024 was when running with Enduro. So my guess would be that the cause of the problem is scenario 2. But I am not sure, would have to look at the Enduro code to be sure.

**Comment by ablwr** [comment]
This one's all good now. Tested in qa/1.x on CentOS (last commit: https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63)

**Comment by ablwr** [comment]
Upon further inspection...

Works fine at first, but then old pattern returns under the following conditions:

1. De-select manually approve
2. Add a transfer, any transfer!
3. Select Reject Transfer. 

After that, new manual approval transfers do not start. Tested in qa/1.x on Bionic and CentOS (last commit: https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63)

I don't see anything of note in any of the component logs.

**Comment by sallain** [comment]
I'm no longer seeing the issue that @ablwr reported in the previous comment, which is great!

But I've found another issue - the "Approve automatically" button is not persistent. If I de-select it and then start a transfer, the check re-appears. This caught me twice over five tests, as I expected to be prompted to approve and then wasn't, because automatic approval had been checked off. I think the checked-or-unchecked state of the button should not change unless the user changes it. @replaceafill maybe you can have a look?

**Comment by replaceafill** [comment]
@sallain After the `Start transfer` button is clicked the state of [that whole component is reset](https://github.com/artefactual/archivematica/blob/44eca798ff408ca727d239ac7515bafc28908662/src/dashboard/frontend/app/services/transfer_browser_transfer.service.js#L16-L23). This includes transfer type, name, access information, added paths and the approval checkbox.

**Comment by sallain** [comment]
@replaceafill and I just chatted behind the scenes and this is not a regression. We theorized that, [since this feature was introduced in 2018](https://github.com/artefactual/archivematica/pull/1217) and no user has complained about the "Approve automatically" button resetting, it's likely that no one is de-selecting it and expecting that state to persist. So... I propose that we just leave it for now and mark this issue as closed.

**Comment by sromkey** [comment]
> @replaceafill and I just chatted behind the scenes and this is not a regression. We theorized that, [since this feature was introduced in 2018](https://github.com/artefactual/archivematica/pull/1217) and no user has complained about the "Approve automatically" button resetting, it's likely that no one is de-selecting it and expecting that state to persist. So... I propose that we just leave it for now and mark this issue as closed.

I remember this being a compromise when the feature was introduced, that it would always reset to clicked... making it persistent would be a separate enhancement request.
