### ISSUE TITLE
Problem: Can't start a transfer if transfer name has diacritics

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1051]
**Expected behaviour**
A transfer should start if the transfer name entered into the dashboard has diacritics.

**Current behaviour**
The transfer doesn't start - or at least it doesn't appear in the dashboard

**Steps to reproduce**
Start a new transfer with a transfer name such as saké Dvořák or Montréal

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 111 qa (xenial and bionic)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Related to https://github.com/wellcometrust/platform/issues/4175#issuecomment-578136053 we might want to use this as a test vector as well. Perhaps.

**Comment by replaceafill** [comment]
I found interesting that https://github.com/archivematica/Issues/issues/519 mentions `am19centos.qa` as the testing environment back then. So I compared how a `SampleTransfers/Images/pictures` transfer with the name `Montréal` is handled between `1.9`, `1.10` and `qa`.

### 1.9

Even though you can see a couple of unicode errors regarding logging at the beginning of the transfer, once the `Sanitize Transfer name` job is reached the workflow can finish just fine.

### 1.10

The logging errors mentioned in `1.9` at the beginning of the transfer are still there and the transfer starts but it quickly fails in the `Verify mets_structmap.xml compliance` job which was changed in `1.10` from a [bash based script](https://github.com/artefactual/archivematica/blob/53167ee1a00745ca2a82dea9e636ab28be2bb173/src/MCPClient/lib/archivematicaClientModules#L37) to a [Python based one](https://github.com/artefactual/archivematica/blob/6946cb55158ca3fe33e2504c358ace79b1be1ed5/src/MCPClient/lib/archivematicaClientModules#L119).

https://github.com/artefactual/archivematica/pull/1404 changed the script to import [`unicode_literals`](https://github.com/artefactual/archivematica/blob/3b67d7919affb47e79a8b7cd5dab5f226e96eb86/src/MCPClient/lib/clientScripts/verify_mets.py#L10) and [pass a couple of hardcoded strings to `os.path.join`](https://github.com/artefactual/archivematica/blob/3b67d7919affb47e79a8b7cd5dab5f226e96eb86/src/MCPClient/lib/clientScripts/verify_mets.py#L23).The problem with this is that the job arguments passed from the workflow are byte string (`job.args[1]` represents the transfer directory). So when `os.path.join` finds one byte string and two unicode strings, it tries to decode the bytes string automatically producing this error:

```
archivematica-mcp-client_1       | 'ascii' codec can't decode byte 0xc3 in position 60: ordinal not in range(128)Traceback (most recent call last):
archivematica-mcp-client_1       |   File "/src/MCPClient/lib/job.py", line 111, in JobContext
archivematica-mcp-client_1       |     yield
archivematica-mcp-client_1       |   File "/src/MCPClient/lib/clientScripts/verify_mets.py", line 24, in call
archivematica-mcp-client_1       |     mets_structmap = os.path.join(job.args[1], "metadata", "mets_structmap.xml")
archivematica-mcp-client_1       |   File "/usr/lib/python2.7/posixpath.py", line 71, in join
archivematica-mcp-client_1       |     path +=  b
archivematica-mcp-client_1       | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 60: ordinal not in range(128)
```

This can be fixed by decoding the transfer directory explicitly when calling `os.path.join`:

```python
mets_structmap = os.path.join(job.args[1].decode("utf8"), "metadata", "mets_structmap.xml")
```

and after doing that the workflow can continue until the `Verify metadata directory checksums` job which produces:

```
'ascii' codec can't decode byte 0xc3 in position 60: ordinal not in range(128)Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/verify_checksum.py", line 309, in call
    job.set_status(run_hashsum_commands(job))
  File "/src/MCPClient/lib/clientScripts/verify_checksum.py", line 273, in run_hashsum_commands
    hashfilepath = os.path.join(transfer_dir, "metadata", hashfile)
  File "/usr/lib/python2.7/posixpath.py", line 71, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 60: ordinal not in range(128)
```

This is a similar scenario ([Python script introduced](https://github.com/artefactual/archivematica/blob/6946cb55158ca3fe33e2504c358ace79b1be1ed5/src/MCPClient/lib/archivematicaClientModules#L117), [`unicode_literals`](https://github.com/artefactual/archivematica/blob/6946cb55158ca3fe33e2504c358ace79b1be1ed5/src/MCPClient/lib/clientScripts/verify_checksum.py#L33) being imported, and [mixed byte and unicode strings being passed to `os.path.join`](https://github.com/artefactual/archivematica/blob/6946cb55158ca3fe33e2504c358ace79b1be1ed5/src/MCPClient/lib/clientScripts/verify_checksum.py#L273)) that can be fixed in a similiar way:

```python
transfer_dir = job.args[1].decode("utf8")
```

With these two fixes the `Sanitize Transfer name` job can be reached and the workflow can continue.

### qa

`qa` has the same problems mentioned for `1.10` (but those can be fixed as explained) but there are new ones introduced by the MCPServer refactoring that won't allow the transfer to start (as explained in the issue description):

```
archivematica-mcp-server_1       | DEBUG    RPCServer-2 2020-01-26 22:18:46 packages:create_package:356:  Transfer object created: 88062c11-2358-45ef-bd26-8aded5749e4c
archivematica-mcp-server_1       | DEBUG    RPCServer-2 2020-01-26 22:18:46 packages:create_package:362:  Package 88062c11-2358-45ef-bd26-8aded5749e4c: starting transfer (('Montr\xc3\xa9al', u'standard', '149091fb-bb7b-4899-bc1e-c61eb04bf578:/home/archivematica/archivematica-sampledata/SampleTransfers/Images/pictures', u'/var/archivematica/sharedDirectory/tmp/tmpobTZvV'))
archivematica-mcp-server_1       | ERROR    ThreadPoolExecutor-0_0 2020-01-26 22:18:46 packages:wrap:388:  Exception occurred during transfer processing
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 381, in wrap
archivematica-mcp-server_1       |     return fn(*args, **kwargs)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 425, in _start_package_transfer_with_auto_approval
archivematica-mcp-server_1       |     transfer_rel, filepath, path = _determine_transfer_paths(name, path, tmpdir)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 400, in _determine_transfer_paths
archivematica-mcp-server_1       |     transfer_dir = filepath = os.path.join(tmpdir, name)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/posixpath.py", line 73, in join
archivematica-mcp-server_1       |     path += '/' + b
archivematica-mcp-server_1       | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
```

The problem in the `lib/server/packages.py` module is that also imports `unicode_literals` and then uses mixed byte and unicode strings for joining paths and replacing strings.

I could force my way out the initial error above and get to the point described by Helen in https://github.com/wellcometrust/platform/issues/4175#issuecomment-578136053 by making these [hacky changes](https://gist.github.com/replaceafill/6cb98345c4a80550655f0bba66c2e693).

I think we need to analyze the data flow in that module carefully and follow the "decode early, use unicode everywhere and encode late" strategy that works in Python 2 and 3.

**Comment by sallain** [comment]
This is now working! Tested on qa/1.x on Bionic.
