### ISSUE TITLE
Problem: adding tag to entire transfer in appraisal tab and then attempting to start ingest causes Archivematica to hang

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1052]
**Expected behaviour**
The user should be able to do one of the following:
1) Add a tag to the entire transfer and turn that transfer into a single SIP, or
2) Not be able to add a tag to the entire transfer

**Current behaviour**
The user can add a tag to an entire transfer and then try to create a SIP using that tag. However, the SIP is not created and the user is not able to start any other transfers.

**Steps to reproduce**
1) Create a transfer and send it to backlog
2) In the appraisal tab, search for the transfer
3) Create a tag and assign it to the entire transfer
4) Open the arrangement pane, select the tag and click "Create SIP"
5) Go to the ingest tab - the SIP never appears there
6) Go to the transfer tab and try starting another transfer - the transfer doesn't appear in the dashboard

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.11-qa (bionic and xenial)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
I have added a comment [here](https://github.com/archivematica/Issues/issues/1055#issuecomment-574429288) and can now make this behavior work locally through my proposed fix there. I still need to create a PR.  

Once it works locally I then see @helenst's failure [here](https://github.com/archivematica/Issues/issues/1031). 

These haven't been mile-stoned yet but #1055 and #1031 and #1052 (a by-product of #1055) can be fixed together 🤞 cc. @sromkey

**Comment by ross-spencer** [comment]
Along with the diagnosis in #1055 I should add context here about why this bug is so apparent in our testing servers. 

Each of the testing servers are virtual machine images sitting on dual-core servers, their specification in our hosted environment is as follows:

![image](https://user-images.githubusercontent.com/1880412/72520622-d1070680-3827-11ea-9550-49c1050724a6.png)

And `lscpu` shows:
```
artefactual@am110xenial:~$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel Core Processor (Haswell, no TSX)
Stepping:              1
CPU MHz:               2394.440
BogoMIPS:              4788.88
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1
```
MCP Server changes for `1.11` will see this as one core to work with. 

As soon as there is `1` activated package that isn't correctly decremented when it becomes inactive, we see the behavior exhibited here, and in #1055. Packages will happily trundle through the workflow job by job otherwise, but as soon as there is an "active package" in a purposely "stalled" state, e.g. from the user perspective we're not doing anything with it for a bit, e.g. being pushed to backlog - if a core isn't given up by Archivematica to work with, no work will be done.

**Comment by ross-spencer** [comment]
This should now be resolved by https://github.com/artefactual/archivematica/pull/1537/commits/38ff3f77936e0b0db757a98d5f11d36e54085605

@evelynPM we've also pushed this one into `qa/1.x` today and would love to get your feedback on its efficacy once the test servers are updated. Another gnarly one down, just a few I think to tackle 🤞

**Comment by peterVG** [comment]
This is now testing successfully on the latest am111bionic.qa instance. I can successfully create a SIP from a tag assigned to the entire transfer. I did not run into the related #1031 issue, the "Attempt restructure for compliance" Job also completes successfully. 

The only (possible) abnormality I noticed is that the original transfer name dissapears now is and is replaced by the name of the tag. Can't recall but that could be expected behaviour?

**Comment by peterVG** [comment]
One weird anomaly though. The transfer that I used to test this shows up as having failed in the Transfer tab. However, it got sent to Backlog successfully and I retrieved it from there no problem to complete this test.
<img width="971" alt="Screen Shot 2020-03-23 at 5 06 34 PM" src="https://user-images.githubusercontent.com/672121/77374913-42cc6680-6d29-11ea-9eb9-39695ae35f5e.png">

**Comment by sromkey** [comment]
@peterVG that's weird!! But a separate issue, so let's move this to Done and if you reproduce that weirdness again we can file a new issue.
