### ISSUE TITLE
Problem: processing of packages is never started under some circumstances 

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1055]
**Expected behaviour**
Archivematica should not refuse to process packages transferred from sources such transfer source locations or backlog.

**Current behaviour**
(props to @replaceafill for the details)
Under some circumstances that we're still investigating, Archivematica is unable to start processing packages transferred by the user. We suspect that this is a problem introduced in the new [queuing system](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/MCPServer/lib/server/queues.py#L24) in MCPServer, where packages seem to be stuck on the deferred queue forever, or until the service is restarted.

With DEBUG set to True in MCPServer, we've seen the following messages:

```
RPCServer-2 2020-01-10 18:53:37 queues:queue_next_job:341:  Released job a6838ac7-7e69-49e5-9889-cee8397872eb (Transfer 951c5a67-794c-447c-8bdd-70d64f93c967). Current queue size: 0
RPCServer-2 2020-01-10 18:53:37 queues:decide:378:  Decision made for job 6cb40337-1652-4a2d-9b22-725b4cc9dba1 (1b04ec43-055c-43b7-9543-bd03c6a778ba)
WatchDirs 2020-01-10 18:54:26 queues:schedule_job:144:  Active packages are: Transfer("/var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/more pictures to approve/", 951c5a67-794c-447c-8bdd-70d64f93c967)
WatchDirs 2020-01-10 18:54:26 queues:schedule_job:158:  Scheduled job 4dc55d22-4422-4141-8247-062dd50ed74d (Transfer 482715ed-9d63-4a54-b4a1-65e4b726f60d). Current queue size: 1
WatchDirs 2020-01-10 18:54:26 queues:schedule_job:168:  Not processing next job; 1 pac
```

The following parameters seem to have an impact on the behaviour observed:
* The value in the ARCHIVEMATICA_MCPSERVER_CONCURRENT_PACKAGES configuration parameter.
* The number of CPUs available in the system.

**Steps to reproduce**
In our docker-based dev environment:
* Set CONCURRENT_PACKAGES to 1,
* Start a transfer from the transfer browser or from backlog.

More variations may have been found, we'll share them later.

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/1052

**Comment by ross-spencer** [comment]
Some of the behavior in this issue can be recreated in Docker by setting the [concurrent packages](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/MCPServer/lib/settings/common.py#L247-L251) to an artificially low number. `1` I think is good for testing I feel because we want to make sure counters involved in this variable are incremented and decremented when packages start or complete tasks. 

A first observation is that we might be missing `Move transfer to backlog`, e.g.
```
    # TODO: make this better by signifying the end of a package in the workflow
    PACKAGE_COMPLETED_LINK_IDS = set(
        [
            # Move to SIP creation directory for completed transfers
            "d27fd07e-d3ed-4767-96a5-44a2251c6d0a",
            # Move to SIP Creation
            "39a128e3-c35d-40b7-9363-87f75091e1ff",
            # AIP completed
            "d5a2ef60-a757-483c-a71a-ccbffe6b80da",
            # Move SIP to failed directory
            "828528c2-2eb9-4514-b5ca-dfd1f7cb5b8c",
            # Move Transfer to failed directory
            "377f8ebb-7989-4a68-9361-658079ff8138",
            # Move transfer to backlog
            "abd6d60c-d50f-4660-a189-ac1b34fafe85",
        ]
    )
```

[Here](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/MCPServer/lib/server/queues.py#L60-L74) Where the server needs to remove it from the active transfers list on completion of a particular workflow task, e.g. [here](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/MCPServer/lib/server/queues.py#L198-L202).

Adding the chain-link ensures the package is destroyed when completed and other transfers can be started. 

When initializing a SIP from the backlog, the following tasks occur, and increment the active package count by 1:

```
archivematica-mcp-server_1       | DEBUG    WatchDirs 2020-01-14 23:31:38 mcp:watched_dir_handler:55:  Starting chain for /var/archivematica/sharedDirectory/watchedDirectories/SIPCreation/SIPsUnderConstruction/all/
archivematica-mcp-server_1       | INFO     WatchDirs 2020-01-14 23:31:38 packages:get_or_create_from_db_by_path:849:  SIP 3739e7db-9a3d-4f03-af72-3a96e186fac7 created (%sharedPath%watchedDirectories/SIPCreation/SIPsUnderConstruction/all/)
archivematica-mcp-server_1       | DEBUG    WatchDirs 2020-01-14 23:31:38 chain:__init__:101:  Creating JobChain a2e19764-b373-4093-b0dd-11d61580f180 for package 3739e7db-9a3d-4f03-af72-3a96e186fac7 (initial link ab69c494-23b7-4f50-acff-2e00cf7bffda)
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2020-01-14 23:31:38 client:run:113:  Running Check transfer directory for objects (package c3513dff-ac47-4278-a08c-260d78305d03)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2020-01-14 23:31:38 gearman_backend:submit:221:  Submitted gearman job 049436ae-165e-4dc5-8e8b-55c1079d8eb6 (checktransferdirectoryforobjects_v0.0)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2020-01-14 23:31:38 gearman_backend:update_task_results:265:  Task 109a32cc-661c-436e-94b9-5a3b727f37d8 finished! Result COMPLETE - 0
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2020-01-14 23:31:38 chain:chain_completed:150:  Done with chain 498795c7-06f2-4f3f-95bf-57f1b35964ad for package c3513dff-ac47-4278-a08c-260d78305d03
```

Following that logic we can then add `Check transfer directory for objects` to this list and then I can see the same behavior happening (the active count being increased, but not decreased once complete) at `Reject` decision points where the final activity is `Move SIP to rejected directory`:

```
    # TODO: make this better by signifying the end of a package in the workflow
    PACKAGE_COMPLETED_LINK_IDS = set(
        [
            # Move to SIP creation directory for completed transfers
            "d27fd07e-d3ed-4767-96a5-44a2251c6d0a",
            # Move to SIP Creation
            "39a128e3-c35d-40b7-9363-87f75091e1ff",
            # AIP completed
            "d5a2ef60-a757-483c-a71a-ccbffe6b80da",
            # Move SIP to failed directory
            "828528c2-2eb9-4514-b5ca-dfd1f7cb5b8c",
            # Move Transfer to failed directory
            "377f8ebb-7989-4a68-9361-658079ff8138",
            # Move transfer to backlog
            "abd6d60c-d50f-4660-a189-ac1b34fafe85",
            # Check transfer directory for objects
            "032cdc54-0b9b-4caf-86e8-10d63efbaec0",
            # Move SIP to rejected directory
            "3467d003-1603-49e3-b085-e58aa693afed",
            "0d7f5dc2-b9af-43bf-b698-10fdcc5b014d",
        ]
    )
```

This these are just a few points that I have identified, we should identify similar tasks where a job chain is supposed to be ended and another package can start processing.

I need to double-check some of the above, the `Check transfer directory for objects` inclusion feels like it might be a hack? Where the other tasks are clear end tasks in a workflow and so packages should be deactivated. I might be missing some in-between logic, even though this essentially works and resolves the symptoms in https://github.com/archivematica/Issues/issues/1052

If the above is right, then regarding the correct solution I believe we should follow the paradigm outlined by Cole so far, but then in the future, we should consider his `TODO` `# TODO: make this better by signifying the end of a package in the workflow`... and ensure a signal is sent back from the completed microservice job to deactivate the package from the active transfers list on successful completion.

**Comment by ross-spencer** [comment]
For testing this on the various Test VMs one just needs to be able to ensure that there is never a time that a transfer started once a package has reached one of the microservice jobs listed here:
```
    # TODO: make this better by signifying the end of a package in the workflow
    PACKAGE_COMPLETED_LINK_IDS = set(
        [
            # Move to SIP creation directory for completed transfers
            "d27fd07e-d3ed-4767-96a5-44a2251c6d0a",
            # Move to SIP Creation
            "39a128e3-c35d-40b7-9363-87f75091e1ff",
            # AIP completed
            "d5a2ef60-a757-483c-a71a-ccbffe6b80da",
            # Move SIP to failed directory
            "828528c2-2eb9-4514-b5ca-dfd1f7cb5b8c",
            # Move Transfer to failed directory
            "377f8ebb-7989-4a68-9361-658079ff8138",
            # Move transfer to backlog
            "abd6d60c-d50f-4660-a189-ac1b34fafe85",
            # Check transfer directory for objects
            "032cdc54-0b9b-4caf-86e8-10d63efbaec0",
            # Move to the rejected directory
            "0d7f5dc2-b9af-43bf-b698-10fdcc5b014d",
            "333532b9-b7c2-4478-9415-28a3056d58df",
            "3467d003-1603-49e3-b085-e58aa693afed",
            # Failed compliance. See output in dashboard. SIP moved back to SIPsUnderConstruction
            "f025f58c-d48c-4ba1-8904-a56d2a67b42f",
            # Failed compliance. See output in dashboard. Transfer moved back to activeTransfers
            "61af079f-46a2-48ff-9b8a-0c78ba3a456d",
        ]
    )
```
So, when you move a SIP to the backlog for example, you should be able to start a new transfer. Similarlly. any of the three `Move to the rejected directory` decision points encoded in the Archivematica workflow.

**Comment by jorikvankemenade** [comment]
While playing around with this I found that `bbfbecde-370c-4e26-8087-cfa751e72e6a`: "Failed compliance" is also the end of a chain. But not in the `PACKAGE_COMPLETED_LINK_IDS`.

![image](https://user-images.githubusercontent.com/7934339/75036600-8aee3400-54b2-11ea-866b-e6540a1d6125.png)

The images transfer should start, but it does not because the failed package is still active (and the max number of packages is configured as 1):

```
DEBUG     2020-02-21 10:57:04  archivematica.mcp.server.queues:queues:schedule_job:157:  Active packages are: Transfer("/cephfs/sharedDirectory/currentlyProcessing/Images", 94dffdd2-7d5a-4cdc-9879-f03027ca44a0)
DEBUG     2020-02-21 10:57:04  archivematica.mcp.server.queues:queues:schedule_job:171:  Scheduled job 253f3652-bc88-4dbc-80a4-5ca6859345dd (Transfer 6ef56f65-74f5-4e9e-b23f-aa3b0aca955a). Current queue size: 2
DEBUG     2020-02-21 10:57:04  archivematica.mcp.server.queues:queues:schedule_job:181:  Not processing next job; 1 packages already active
```

**Comment by jorikvankemenade** [comment]
It might be relevant to mention #1108 here as well. This does not necessarily block the processing of a transfer. But it shows the relative fragility of hard coding the `PACKAGE_COMPLETED_LINK_IDS`. Personally I find it quite hard to reason about the workflow when part of it is defined in the `workflow.json` and a part of it is decided by some hardcoded values in the codebase. 

Are there already ideas on how to encode this in the workflow? If so I might have some time to have look at that this weekend/next week. Personally I thought of adding an extra attribute to the links. But I haven't given it proper thought yet.

**Comment by sevein** [comment]
> Are there already ideas on how to encode this in the workflow? If so I might have some time to have look at that this weekend/next week. Personally I thought of adding an extra attribute to the links. But I haven't given it proper thought yet.

[Amazon States Language](https://states-language.net/spec.html) uses a similar concept: ["terminal state"](https://states-language.net/spec.html#terminal-state). In our workflow, a "terminal link" or "end of chain" could be explicitly declared with an attribute like you're suggesting, e.g. `"end": true` could work. An alternative could be to consider all links without references to other links to be terminal. A new `terminal` boolean property in `workflow.Link` would be awesome.

I'd say that "Check transfer directory for objects" isn't a terminal link, but you'd want its `exit_codes.0.link_id` and `fallback_link_id` attributes to connect to a new link that is terminal.
"Move to the rejected directory" is going to be by far the most common terminal link. A whole different category is those like "Move to the rejected directory" that trigger a new chain via watched directories - they can be considered "terminal links" today but ideally in the future we'd just stop using watched directories. It sounds like you could do the changes in workflow.json programmatically right?

**Comment by jorikvankemenade** [comment]
> A new `terminal` boolean property in `workflow.Link` would be awesome.

My thoughts exactly. Nice to see that we are on the same page for this.

> I'd say that "Check transfer directory for objects" isn't a terminal link (...)

Okay, I would think so as well. This would mean that we need to change the `workflow.json` for this link. I can combine this in a PR together with a proposal for the `workflow.Link`. I am currently looking into how the whole queueing works for some tests in relation to #1010. If you want I can probably open a draft PR this weekend so we have something more concrete to discuss?

**Comment by sevein** [comment]
Awesome, thanks for doing this!

**Comment by sevein** [comment]
> If we could move Archivematica away from the watched directories concept, having a fully connected workflow graph, we could move to an "automatic" terminal state. Or am I missing something?

Do you mean the end of workflow? That makes sense yeah. I sort of think that we have multiple workflows dealing with different entity types. E.g. Transfer/Backlog, Ingest, DIPs... In a fully automated pipeline, they can be interpreted as composable child workflows.

**Comment by jorikvankemenade** [comment]
Yes, I think we have the same idea. To me, the workflow is a graph. Every node is either a script/action or a decision point. Currently, there are a lot of smaller disconnected graphs - child workflows if you will. Each of these graphs is fully specified, i.e. every node has a connection to another node. Some of these disconnected graphs are related via the watched directories. For example, the "Complete Transfer" microservice is linked to the "Create SIP from Transfer"  microservice via filesystem events. Not because of a hard link in the workflow. I believe that the ideal situation would be that every node in the graph is either:
1. a starting point 
1. a link
1. a decision point 
1. a `terminal` node  

Where the starting point is an explicit action by a user or via the API. The rest of the workflow is fully deterministic based on *either* user actions or the processing configuration and *not* on filesystem events.

**Comment by sromkey** [comment]
I've followed @ross-spencer 's instructions in comment above (https://github.com/archivematica/Issues/issues/1055#issuecomment-577291018) so I'm marking this as Done.
