### ISSUE TITLE
Problem: You get two-transfers for the price of one when you manually approve a zipped bag transfer in qa/1.x

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1092]
**Expected behaviour**

The manual approval workflow of any transfer should only result in one "transfer" in the pipeline.

**Current behaviour**

Manually approving a zipped bag results in the following:

![image](https://user-images.githubusercontent.com/1880412/74093856-fb09bc80-4aa5-11ea-9ef0-9f6b12112c92.png)

Two transfers, one without a name. 

I didn't verify the contents or behavior of any of these given the initial reaction from Archivematica is incorrect. 

**Steps to reproduce**

Take a recent `qa/1.x` commit, and try to initiate a zipped bag transfer. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Verified in Xenial, CentOS, Docker, etc. 

**Additional context**

To the extent that I have the time to be able to do further investigation into it this evening, I checked to see if this was related to the changes to preserve the processing config in zip-like transfers. Where the following two commits represents that work, and then the work immediately prior to that (not containing those changes) the behavior seems consistent in both, so it might go back to some of the other changes at the heart of the MCP server. As ever we need to dive into the code to verify. It's largely an educated guess up until that point. 

* https://github.com/artefactual/archivematica/commit/55c1d0fccb12f34ab5d2393fce5eead232184a0f <-- preserve processing config in zips
* https://github.com/artefactual/archivematica/commit/cf68558768b7be2a558f034414e453c9458cffd0 <-- commits prior to that 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I compared qa's behavior with 1.10 and realized two things:

1. In https://github.com/artefactual/archivematica/pull/1526 when we faced a similar issue with manually approved transfers we restored the ability for the watched directory handlers to reuse a transfer in the database based on its `UUID` or create it if necessary.

    However we left out a [block of logic that allows to reuse a transfer based only on its current location path](https://github.com/artefactual/archivematica/blob/b4dab1d01ea3978dd6c3919f251bab58e394ec77/src/MCPServer/lib/unitTransfer.py#L48-L50), not its `UUID`.

    According to my testing adding this bit of code back takes care of part of this issue (see next point).

1. The next part of the problem is that manually approved transfers rely on the watched directories logic instead of being put directly in the processing directory like the automatically approved ones are. Anything that lands **or gets created** inside a watched directory will be picked up by a handler.

    In https://github.com/artefactual/archivematica/pull/1446 the ability to keep the processing configuration with zipped transfers was added and the MCPServer was changed to [precreate the extraction directory](https://github.com/artefactual/archivematica/blob/f50d86e1835644e1492c97984b1270879a5c70e6/src/MCPServer/lib/server/packages.py#L305-L323). But this has a side effect: when the empty directory is created inside the watched directory its handler creates a second transfer since it cannot match by `UUID` or current location path.

    In my testing if I comment out this "precreate the extraction directory" block, Zipped bag and Dspace transfers work as expected with manual approval.

I'm not sure how to address the second part of the problem: keep the processing configuration for zipped files and make the watched directory handler not to react this way. Maybe @sevein or @ross-spencer can suggest an approach?

**Comment by replaceafill** [comment]
@sevein @ross-spencer I've created this [draft PR](https://github.com/artefactual/archivematica/pull/1570) to address the problems mentioned in my previous https://github.com/archivematica/Issues/issues/1092#issuecomment-585313063.

This is my approach:

- The [first commit](https://github.com/artefactual/archivematica/pull/1570/commits/f750532b30eb5896aa8c12de423fefec128aaeea) addresses the first problem in my previous comment: the current location needs to be queried before creating a transfer

- The [second commit](https://github.com/artefactual/archivematica/pull/1570/commits/7cf2003a3293ac0241c2a3d710e8262595327128) creates a `UnitVariable` called `processingConfiguration` for transfers that contains its name. A `processing_configuration` has been added to the `Transfer` model to encapsulate the retrieving logic (like returning the `default` when the variable is empty).

- The [third commit](https://github.com/artefactual/archivematica/pull/1570/commits/f7ccdcde10d4d3c98842356bbeb1fdf0b93b1596) sets the value for the variable when a package is created (and the processing configuration name is available). Then a `%processingConfiguration%` string replacement is set in the `packages.Transfer` class with its value so the workflow has access to it like any other string replacement (`%SIPUUID%` and so on).

- The [forth commit](https://github.com/artefactual/archivematica/pull/1570/commits/9496eed06d04a1f7077e5351d7f8ec54e11f73c4) updates `workflow.json` to copy the xml file using the replacement. This has the nice advantage that we can use the same `copy_v0.0` client script.

- The remaining commits remove configuration copying from the server side and the "precrate the extraction directory" block that I mentioned in the second problem of my previous comment. This will stop messing with the watched directories without changing the handlers.

I didn't fix the test failures yet because I'd like to hear your opinion first.

A couple of concerns I have:

* We're adding more rows/queries to the database with the new variable. The old approach relied (more) on the filesystem

* The API now fails if you pass a nonexistent processing configuration name:

  ```
  cp: cannot stat '/var/archivematica/sharedDirectory/sharedMicroServiceTasksConfigs/processingMCPConfigs/foobar123ProcessingMCP.xml': No such file or directory
  ```

  Previously if you passed a nonexistent name a [warning was logged](https://github.com/artefactual/archivematica/blob/44eca798ff408ca727d239ac7515bafc28908662/src/MCPServer/lib/server/processing_config.py#L270-L275) and the `copy_v0.0` client script would take care of copying the default one if one didn't exist.

**Comment by ross-spencer** [comment]
@replaceafill I had a bit of a preview of this yesterday as we tried to figure out some of the problems here. I wasn't a fan of the current approach. I think what you've proposed is really clever and a great extension on the logic of using unit vars (Archivematica's heap :wink:). I don't see any issues with doing it like this myself. 

> The API fails with a non-existent processing config: 

Can you control whether the default configuration is selected if one isn't supplied? That's always available, and recreated on a restart of Archviematica if it has been deleted. 

If @sevein gives the thumbs up too, then we should definitely proceed along this path.

**Comment by sevein** [comment]
Makes sense to me, thanks @replaceafill and @ross-spencer.

**Comment by replaceafill** [comment]
Thank you both!

> Can you control whether the default configuration is selected if one isn't supplied? or check that it exists when we receive the request? That's always available, and recreated on a restart of Archviematica if it has been deleted.

I just added this check when the package is created in https://github.com/artefactual/archivematica/pull/1570/commits/61be6dfc943397674fbad640fba8d0b12a1ef0d2

> I'm seeing the default processing selected over the one supplied in this sample.

I [restored passing the `--no-clobber` flag to the `copy_v0.0` client script](https://github.com/artefactual/archivematica/pull/1570/commits/796c1ae0229a83d114e320b14707b6ae0fa1d4c7) which I think takes care of this.

Thanks again for testing! :bowing_man:

**Comment by sallain** [comment]
This is now working! Tested on qa/1.x on Bionic.
