### ISSUE TITLE
Problem: SS timeout occurs during Store AIP of large dataverse dataset 

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#114]
Expected behaviour
When I select the dataset "3D Laser Images..." in the Transfer Browser from Dataverse, I epect it to complete processing and for an AIP to be stored. 

Current behaviour
The dataset fails at the "Store the AIP" job within the Store AIP Microservice. 
The following error appears in the task page: 
```
SIP creation failed.  See Storage Service logs for more details
HTTPConnectionPool(host='archivematica-storage-service', port=8000): Read timed out. (read timeout=5.0)
storeaip_v0.0: WARNING   2018-08-22 20:08:39,210  archivematica.mcp.client.storeAIP.store_aip:184  SIP unabled to be created: HTTPConnectionPool(host='archivematica-storage-service', port=8000): Read timed out. (read timeout=5.0).  See logs for more details.
```

The following errors appear in the Storage Service logs: https://gist.github.com/joel-simpson/966a0524070792aa7779b77675fc509e

Steps to reproduce
Need to test from an instance of Archivematica that has a Dataverse Storage Space connected. Select the 3D Lasers dataset. 

Your environment (version of Archivematica, OS version, etc)
Testing the latest changes for Dataverse which are up to date with qa/1.x (Dev branch for [SS PR 398] (artefactual/archivematica-storage-service#398 AM PR 1242). Tested on my local docker dev environment and in our QA environment http://ocul-am-dv.dev.archivematica.org:62080

**Comment by marktriggs** [comment]
Hi all,

I've added a pull request for this one too.  The issue here was that `storeAIP` would call `create_file`, POST a package to the storage service and then start polling the async endpoint waiting for results.  After a few poll attempts, one of them would suddenly take longer than 5 seconds and would hit the default HTTP request timeout as a result.

When this happened, the storage service appeared to be in the process of creating a new pointer file--reading a bunch of records from the DB and producing XML.  This was CPU intensive enough to delay handling of the async poll requests, which caused them to take longer than 5 seconds to be handled, which caused everything else to blow up.

So I've increased the timeout to 10 minutes now, which Should Be Enough For Anyone.  Python's thread scheduling should hand control over to the async request thread periodically, so in reality it shouldn't need to wait long (just a little longer than 5 seconds in some cases...)

**Comment by joel-simpson** [comment]
Joel D rebased the dev branches for Dataverse, so I was able to update my environment and test this. 
Both of the datasets that failed previously (3D Lasers & AV Large Files) now complete with no problems. 
I'm moving this to verified. Issues are linked to PRs, which are merged to qa/1.x. 
I don't believe specific documentation is required for this issue because the fix is quite a low level change.
