### ISSUE TITLE
Problem: the user is not seeing all relevant information on the Archival Storage tab

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#1168]
**Please describe the problem you'd like to be solved**
The user is not seeing the complete set of information they need to efficiently process their Archivematica packages. They would like to add the number of files and accession number to the columnar display of AIPs on the Archival Storage tab.

**Describe the solution you'd like to see implemented**
**Feature:**	Select which columns to display in the table list on the Archival Storage tab
**Scenario:** The user would like to take further action with the AIP packages listed on the Archival Storage tab.
**Given:** That he can browse packages using the table list, column sorting, and list paging on the Archival Storage tab.
**And:** The default AIP, Size, UUID, Date Stored, Status, Encrypted, and Actions are currently displayed in the table list.
**When:** He clicks on the column selector icon, he can deselect one or more of the currently displayed default columns and can select one or more <column> options in their place.
**Then:** The columns displayed in the table list on the Archival Storage tab match the selected and deselected options. 
**And:** These selections will also apply to the “Show files” display option (except “File Count”)
**And:** These selections will be applied to all users of the pipeline
**And:** The select and deselect choices will persist between user sessions 

**Examples:** 
|    column                   |
| File Count                 |
| Accession Number |

**Describe alternatives you've considered**
Replacing existing columns, e.g. eliminating the long UUID field and replacing it with two new columns, is problematic because which columns on the limited horizontal screen real estate are most relevant is a user-specific criterion. That is, those columns that may be useful to one user may be less so to an Archivematica user at another institution.

**Additional context**
See related https://github.com/archivematica/Issues/issues/1167

The same "Select columns" icon and location should be used on the Archival Storage tab as is being implemented for the Backlog tab. 

Archivematica currently uses a Django template to display the table on the Archival Storage tab. To be consistent with table display and functionality on the Backlog tab and Archivematica Storage Service, the Archival Storage tab (and "Show files" option) should also switch to using the https://datatables.net/ javascript library.

Any new strings introduced as part of this feature enhancements (e.g. "Select columns, column headers) should be translatable.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by tw4l** [comment]
I added the documentation label, as visual changes to the Archival Storage tab UI (moving search results - including file search results - into a DataTable; removing the "Show AICs" checkbox) will require updated screenshots and potentially changes to the text in the Archivematica docs.

**Comment by peterVG** [comment]
Note, also added a link to the AIP detail page from the "Show files?" table. As well as making "Accession Numbers" a plural label as there may be many to one relationship between accessions and AIPs.

**Comment by peterVG** [comment]
**[√]** Then: The `<column>` displayed in the table list on the Archival Storage tab match the selected and deselected options.
**[√]** And: These selections will also apply to the “Show files” display option (except “File Count”)
**[√]** And: These selections will be applied to all users of the pipeline
**[√]** And: The select and deselect choices will persist between user sessions

Examples:
| `column`                 |
| Name                       |
| UUID                        |
| AIC |
| Size |
| File Count                |
| Accession Numbers |
| Created |
| Status |
| Encrypted |
| Action |

Examples:
| `file column` |
| Thumbnail |
| File |
| File UUID |
| AIP |
| Accession Number |
| Status |
| Download |

**Comment by peterVG** [comment]
Not sure if that was intentional but the following columns do not have sorting enabled:
Archival Storage - Accession numbers, Status.
Show files - File, Accession number, Status.

**Comment by peterVG** [comment]
When following a link to an AIP record from the Show files page (e.g. pv-test10 in the screencap below):

<img width="1346" alt="Screen Shot 2020-06-02 at 4 35 36 PM" src="https://user-images.githubusercontent.com/672121/83579841-374aa800-a4ef-11ea-9cc4-9859ef9a9be2.png">

And then use your browser's "Back" button, the following Datatables alert will be displayed:

<img width="1372" alt="Screen Shot 2020-06-02 at 4 29 01 PM" src="https://user-images.githubusercontent.com/672121/83579866-4c273b80-a4ef-11ea-8076-fbeb0405e1c5.png">

This does not occur if you select the "Archival Storage" from the AIP detail page.

**Comment by tw4l** [comment]
The sorting issues are not intentional. I will check to see what's going on (likely has to do with the Elasticsearch mappings).

On the second issue (the somewhat cryptic DataTables error), this seems to be a browser-specific issue relating to how state is saved relative to the back button functionality. Here's what happens in Firefox vs. Chrome:

- Firefox: User clicks on AIP link from files view of table -> user clicks back button in browser -> user is taken correctly back to the files view of table, data is displayed properly, and no error message is displayed.
- Chrome/Chromium: User clicks on AIP link from files view of table -> user clicks back button in browser -> Chrome tries to load the AIPs (not files) view of table but using the data from the files view (because "show files" is still clicked), so there is a data mismatch and the DataTables error alert is shown.

I will update this issue again as I have questions or solutions to test. Thanks for your sharp eye, @peterVG!

**Comment by tw4l** [comment]
@peterVG fixes for the Chrome issue (setting `autocomplete=off`) and sorting issues (adding explicit keyword mappings for new text fields) have been merged to `qa/1.x`, and this is ready for re-review.

**Comment by peterVG** [comment]
The sorting is fixed.

However, I'm experiencing some inconsistencies with the browser back button issue. I realize though that we may have settled on it "just not breaking with a cryptic alert in Chrome" versus cross-browser consistency. Please remind me what the expected behaviour is.

Right now, if I am in the Show files screen, and could be on page 3 of 6 say, when I click on the AIP detail link, I am taken to that AIP detail page, then when I hit the back button in Chrome, I am taken to page 1 of the AIP browse page on the Archival Storage tab. However, when performing the same routine on Safari or Firefox, I am returned to page 3 of 6 of the "Show files" table where I started from (more desirable as this is the actual previous page I want to go "back" to).

**Comment by peterVG** [comment]
Hmm, it would appear from this comment thread https://github.com/artefactual/archivematica/pull/1618#issuecomment-639166656 that the behaviour is expected to be the same across browsers. Maybe the "autocomplete=off" setting didn't take on my Chrome instance?

**Comment by peterVG** [comment]
Nope, that appears to be set correctly:

<img width="955" alt="Screen Shot 2020-06-08 at 2 42 03 PM" src="https://user-images.githubusercontent.com/672121/84083335-48376580-a996-11ea-84d7-7c95fe90c8d0.png">

**Comment by tw4l** [comment]
Hi @peterVG, that's so strange! The behavior you are describing is actually what I expected to happen based on my reading of browser differences, but in my local testing (Ubuntu 18.04), Chromium 83.0.4103.61 and Firefox 76.0.1 were both bringing me back to page 1 of the AIP browse page after hitting the back button.

I'm glad that the DataTable error and failure to render are fixed, so that this doesn't prevent anyone from using Archivematica or the Archival Storage tab.

I do wonder how much effort we should put into making the experience in Firefox vs Chrome vs Safari identical, given how little control we have in the end over this. New versions of Chrome, for instance, are experimenting with back-forward caches to prevent app developers from hijacking the browser history, which means that Chrome may eventually end up having more Firefox-like behavior around the back button.

Personally I'm inclined to be satisfied with "working in both browsers, with slight differences in this one particular case" over continuing to chase uniformity, but I realize that's not my decision to make. Let's take this to the team and see what they say.

**Comment by peterVG** [comment]
Yeah, I agree with your conclusion @tw4l. We've spent enough time on this and at minimum what we have now is something that doesn't break. Just ideal behaviour vs not-as-ideal.

**Comment by tw4l** [comment]
For future reference: In Ubuntu 18.04, Firefox 76 brings me back to page 1 of the AIP view, and Firefox 77 brings me back to page 3 of the "show file" view. So there are differences not only between browsers, but also between recent versions of Firefox.

**Comment by tw4l** [comment]
For additional consideration, this same difference in where the "back" button takes you based on your browser can be found elsewhere where we use DataTables in Archivematica - namely, Backlog and the Storage Service.

So for instance, in Archivematica 1.11/Storage Service 0.16, if I have more than 10 packages registered in my Storage Service and I click on "Packages", go to the second page of my results, click on a link (e.g. "Originating Pipeline"), and then use my browser's back button:

- In Firefox 76 (Ubuntu 18.04) and Chromium, I am taken back to the first page of the Packages results.
- In Firefox 77, I am taken back to the second page of the Packages results.

**Comment by peterVG** [comment]
Draft docs done. Need to be added to am-docs repo. Note that the Archival Storage docs page will also need screencap updates to account for the UI changes introduced with this commit.

**Comment by sromkey** [comment]
Looking good in QA :+1:
