### ISSUE TITLE
Problem: storage_service locations_package.size is not big enough, should be BigIntegerField

### ISSUE THREAD

**Issue by vdecorges** [archivematica/Issues#120]
**Expected behaviour**
When storing file larger than 2^31-1 into the Storage_Service the acutal ize of the AIP or DIP should be stored.

**Current behaviour**
Currently when an AIP or DIP is stored that is larger than 2^31-1 the size is 2^31-1 and not the real size of the file.

**Steps to reproduce**
Store into the Storage_Service a file larger than 2^31-1 bytes. Note that the problem occurs only with MySQL as DB for the Storage_Service.

The correction is to change that datatype of locations_package.size to django.db.models.fields.BigIntegerField

**Your environment (version of Archivematica, OS version, etc)**
Archivematica v 1.7, Storage Service v 0.11 and MySQL for the Storage Service

**Comment by eviau-artefactual** [comment]
Hello @vdecorges - thank you for your patience. 

We realized this should be fixed by commit https://github.com/artefactual/archivematica-storage-service/commit/d54716cd571ac2a6fedf5c4dba314e9c33192cd1 from the Issue https://github.com/archivematica/Issues/issues/981

We will close this issue for now.
