### ISSUE TITLE
Problem: there is no way to clear the archivematica dashboard database

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1239]
**Expected behaviour**

There is a process that allows to clear the archivematica dashboard database, without interrumpting running transfers

**Current behaviour**

When running 24/7 the archivematica MCP database grows 300mb/hour. 

**Steps to reproduce**

Run lots of transfers, or transfers with a lot of files, and see how MCP size grows

**Your environment (version of Archivematica, operating system, other relevant details)**
AM stable/1.11 running on RHEL 7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
A 20K files transfer adds more than 300k records to the `Tasks` table. Do we really need it once the METS file is created?

**Comment by ross-spencer** [comment]
Partially related: https://github.com/archivematica/Issues/issues/314

**Comment by uofmsean** [comment]
I would also like to know what data can be purged. Our dev environment has over 3 million rows in the Tasks table that is over 4GB in size due to many tests creating AIPs with many thousands of files each. MCP Server startup took over 14 minutes due to the Tasks table update query that filters on exitcode=None ([the call is made here](https://github.com/artefactual/archivematica/blob/a31f218ceabc5bbe996775b82b9c9861b2f406d9/src/MCPServer/lib/server/tasks/task.py#L63-L65)).

**Comment by ross-spencer** [comment]
This issue is referenced here on the Google Groups, cc. @uofmsean https://groups.google.com/g/archivematica/c/DfbNIei3GIE/m/uSKZ9Ua1DQAJ

**Comment by uofmsean** [comment]
Thanks @ross-spencer. Truncating the tables (specifically the Tasks table) resolved our slow MCP Server startup issue.

**Comment by sromkey** [comment]
We can continue to refine a solution before releasing but it sounds like a solid documented method of doing this would be sufficient (as opposed to say, a clickable method in the UI)

**Comment by scollazo** [comment]
We are aware of at least one Archivematica deployment working 24 hours a day, 7 days a week, that had a MySQL growing of around of 350Mb/hour ( per Archivematica instance)

It would be good if, besides a manual or automated process, this could be deal also in the app to allow for continuous operations over longer periods of time.

**Comment by sevein** [comment]
We don't have good support for background jobs so a potential long-running task like this can't be properly scheduled unless we make it part of the Archivematica workflow.
Would a management command cut it? E.g. `./manage.py purge-transient-processing-data --age-days=7` would delete all data that relates to packages that are 7 days old or older.

**Comment by scollazo** [comment]
That would be an acceptable solution for the current use case, but 7 days is a too long period, could this be used for transfers, says, older than 6 hours?

Also, could this manage command have effect only on already finished (or failed!) transfers, or are we relying on the age of the tasks for them being removed, without accounting if the transfer/ingest had finished or not?

**Comment by sevein** [comment]
Good ideas, thanks. We will do that.

**Comment by jhsimpson** [comment]
I tested the new management command described in https://github.com/artefactual/archivematica/pull/1736

The [1.13 documentation](https://www.archivematica.org/en/docs/archivematica-1.13/admin-manual/maintenance/maintenance/#management-commands) has good usage examples to follow.

I was able to see what would be deleted, before actually deleting anything with 
`manage.py purge_transient_processing_data --dry-run`

The comments on issue 1736 says 'Related data isn't removed from Elasticsearch' but I found that it was.  I had to rebuild the elasticsearch index afterwards to see the aips int he Archival storage tab. Specifically - if there is an AIP listed in the archival storage tab that has still has the data for its corresponding sip or transfer in the database, when the purge_transient_processing_data command is run, the AIP no longer appears in the Archival Storage tab.  After rebuilding the index, the AIP does appear in the Archival Storage tab, and stays there even after the purge_transient_processing_data command is run again.

**Comment by jhsimpson** [comment]
two suggestions 

1. can you set a default value for the `--age` parameter (say 1 day or 1 week) so that recent data is not affected accidentally.  I had a situation where I ran this command and a transfer was deleted before the SIP had been created, and it seemed to just get lost.  If a user wants to override the default and set age to 0 that's fine, but a default would protect against accidental data loss.
2. can you add a new parameter for `keep-indexed' or something simillar?  The default can be no (current behaviour) , but if a user wants to retain a listing of an AIP in the archival storage tab, when deleting the transient data, this would give them a way to do that without resorting to rebuiding the index after.

**Comment by replaceafill** [comment]
I tested the default value of the `--age` parameter and realized it's set to 6 minutes, not 6 hours. I created https://github.com/artefactual/archivematica/pull/1773 to fix it. And passing `--age 0` does deletes all the data.

The new `--keep-searches` parameter retains the information in the indexes.

**Comment by replaceafill** [comment]
This is working as expected now.
