### ISSUE TITLE
Problem: transfer name doesn’t always show up in Archivematica v1.11.2

### ISSUE THREAD

**Issue by cannedit** [archivematica/Issues#1250]
**Expected behaviour**
The name of a transfer should always be visible immediately when the transfer shows up in the Transfer tab.

**Current behaviour**
The name of a transfer doesn’t always show up in the Transfer tab in Archivematica v1.11.2.

This is different behaviour compared to Archivematica v1.11.0/v1.11.1 and it has probably something to do with the improvement to quickly show something is happening in the Transfer tab in case a large transfer is taken in, because that could take ages previously, but this is an annoying side effect of this improvement.

A workaround for this is to refresh the page while the transfer is still running (but not when a dialogue screen is still open, then you have to deal with the dialogue first and then refresh), this also works after a transfer has been concluded and forwarded to the Ingest tab, but not if you don't have time to do this because a transfer fails right from the start (see the screenshot attached).  

![AMv1 11 2_transfers_withnoname](https://user-images.githubusercontent.com/22167327/86571614-fcb2b000-bf71-11ea-9599-db2afb23e13d.png)

**Steps to reproduce**
This is a bit tricky because the issue doesn’t always occur, but in my experience at least once within 10 to 15 transfers.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica v1.11.2

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Our team is pretty sure they've seen this behaviour at least as of 1.11.0 as well.

**Comment by cannedit** [comment]
Well, for what it's worth: I have done a lot of testing on a a few v1.11.0 environments lately (for example the one of City Archives of Amsterdam, which still is on this version but with the security patch ofc) and I didn't came across it over there once. The first time I encountered is was on a few environments which were upgraded to v1.11.2 recently, so maybe it's happening more often on this latest version than on the other ones.

**Comment by mamedin** [comment]
I could reproduce the issue on AM v1.11.2:

- am111bionic.qa server: Test server deployed directly from v1.11.2
- Other test server upgraded from v1.10.2

The easiest way I found to reproduce the issue is running several times (quickly) the following transfer:

https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/StructMapTransferSamples/ComplexStructureExample

I initially suspected that it could be related to the `ARCHIVEMATICA_MCPSERVER_MCPSERVER_CONCURRENT_PACKAGES` variable, but after some testing it is not related.

**Comment by ross-spencer** [comment]
Okay, so I think I've finally narrowed this down to a set of commits. Which I need to investigate in more depth next. These were the commits needed to include the zip file transfer type as well as improving our ability with Processing MCP and zip-like packages, so Zipped Bags. 

![image](https://user-images.githubusercontent.com/1880412/90791396-22ec9f00-e2d7-11ea-9615-d94e620250bb.png)

To be clear then - this existed in 1.11.0 and didn't exist in 1.10.1. But it means we can discount recent code which might also have had an impact around CORS when making Ajax requests to the server. 

The last commit to work as we expected: https://github.com/artefactual/archivematica/commit/cf68558768b7be2a558f034414e453c9458cffd0
And the first significant commit to then not work: https://github.com/artefactual/archivematica/commit/55c1d0fccb12f34ab5d2393fce5eead232184a0f

The small group of 7 in-between might normally have been rebased and so lets look at those as one and work backwards from there: https://github.com/artefactual/archivematica/pull/1641 

**Race condition?**

It was initially pointed out that this looks like a race condition by our colleagues at Picturae, and it is beginning to look something like that. 

A transfer is starting and triggering the creation of the jobs/transfer html rows in the transfer browser, before the transfer has been fully copied into the watched directory. The transfer directory isn't made available to the transfer status pages until it reaches

![image](https://user-images.githubusercontent.com/1880412/90792933-18330980-e2d9-11ea-9e56-7443aa0bb7fb.png)

A URL to that data is built along the lines of: `http://127.0.0.1:62080/transfer/status/?1597937584377 `

The directory value which is `null` in that image above, is populated at some point in the Jobs table. 

I think it might eventually get to us by `Rename with transfer UUID` but it might also get to us around `Remove uneeded files`, but I need to confirm that next. 

When I say "get to us" I just mean, like you see in the image above, three services have already run and the jobs table looks to still be empty for that SIP which is why there isn't a value to access. 

Which already sounds suspiciously incorrect.

If you try recreating this and you refresh your workflow as you go you'll see this value remainss blank for a few steps until you refresh and all is fine. This means the issue is less apparent on small transfers, but I think you'll see it happen more often as the number of files to copy ramps up. 

**NB.** My sample set is ~1870 files and ~48 directories. The files are all about 20kb. 

So more investigation coming. 

I've been looking in the Jobs.js scripts and Backbone.js scripts this week, but having spent the last few hours identifying the specific group of commits will delve into those as well as related areas of the Python code proper like our handling of watched directories. 

Related (for my notes) https://github.com/artefactual/archivematica/pull/1567

**Comment by ross-spencer** [comment]
This isn't a "fix" but it reverts the previous behavior to fix the symptoms. And it works. https://github.com/artefactual/archivematica/pull/1641/commits/42eaa38987287ebf09987d0d88feeac08f9a7656 TODO: investigate the mechanics of pathlib and I think watched directories to see how the values are being interpreted to cause the issue.

**Comment by ross-spencer** [comment]
A further refinement is that this is not to do with the movement of the objects, but to the current path initially not being terminated by a slash... https://github.com/artefactual/archivematica/pull/1641/commits/afb2c1c4178e5cc7662ae4fcd1753f42b7fa8c64 so, let's see if we can fortify the retrieval of this value, or control how we're writing it better... 

```diff
diff --git a/src/MCPServer/lib/server/packages.py b/src/MCPServer/lib/server/packages.py
index 9ad90e6c2..d840d3a37 100644
--- a/src/MCPServer/lib/server/packages.py
+++ b/src/MCPServer/lib/server/packages.py
@@ -275,7 +275,8 @@ def _move_to_internal_shared_dir(filepath, dest, transfer):
     except OSError as e:
         raise Exception("Error moving from %s to %s (%s)", filepath, dest, e)
     else:
-        transfer.currentlocation = str(dest).replace(
+        dest = os.path.join(str(dest), "")
+        transfer.currentlocation = dest.replace(
             settings.SHARED_DIRECTORY, "%sharedPath%", 1
         )
         transfer.save()
```

**Comment by ross-spencer** [comment]
The rpc server is trying to retrieve the transfer name from [`Job.get_directory_name()`](https://github.com/artefactual/archivematica/blob/396015a44723e6b2dd2f4d7bed1443514a429c12/src/dashboard/src/main/models.py#L809-L824).

Because we don't always terminate the path with a slash, it is possible for the retrieval to fall-through the function and return `None` which is why the transfer name is sometimes blank. Again, the non-termination of this path was introduced in `1.10` and so it wouldn't have been spotted in fairly recent versions of Archivematica. 

Reading the spirit of the function, it looks like returning a sip UUID is a valid return if the regular expressions do not match. We can add that. We can also make sure the path is terminated if it exists. 

We will try and make this all more robust in https://github.com/artefactual/archivematica/pull/1641

**Comment by sromkey** [comment]
I have tested using @mamedin 's suggestion in the comment above and haven't been able to reproduce, so calling this done!
