### ISSUE TITLE
Problem: reindex_aips_from_storage_service fails on replicated AIPs

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1262]
**Expected behaviour**

Running `manage.py index_aips_from_storage_service --delete-all` will successfully index all non-deleted AIPs associated with a pipeline. Replicated AIPs would not be indexed, since they are not normally present in the Archival Storage tab.

**Current behaviour**

The task attempts to index replicated AIPs as well, and throws an `lxml.etree.XMLSyntaxError` when it hits one.

**Steps to reproduce**

* Ingest some AIPs in an environment with AIP replication set up
* Run the ` index_aips_from_storage_service` management task
* Watch it fail

**Your environment (version of Archivematica, operating system, other relevant details)**

`qa/1.x`

**Additional context**

Related to https://github.com/archivematica/Issues/issues/734

Bug introduced in PR https://github.com/artefactual/archivematica/pull/1624

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
Fixed in https://github.com/artefactual/archivematica/pull/1628

**Comment by ross-spencer** [comment]
**On Bionic, deleted all AIPs from the search index:**

![image](https://user-images.githubusercontent.com/1880412/91593592-73df4180-e92e-11ea-8be0-60f095dfb04f.png)

`root@am112bionic:~# curl -XDELETE "http://127.0.0.1:9200/aips,aipfiles,transfers,transferfiles"`

**One replicated package in the storage service:** `a583fb72-1eef-46db-8492-6caf468e4d26`.

![image](https://user-images.githubusercontent.com/1880412/91593629-82c5f400-e92e-11ea-96a7-60e75d43e4e9.png)

**Rebuild the entire index.**

```
root@am112bionic:~# sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /opt/archivematica/archivematica/src/dashboard/src/
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_aip_index_from_storage_service";
...
...
...
Indexing complete. Successfully indexed 23 AIPs/AICs.
```

**Look for my replicated AIP:** 

![image](https://user-images.githubusercontent.com/1880412/91594888-9eca9500-e930-11ea-8f58-3fef4b4c91f3.png)

It is there. 

The resolution of this issue is therefore is...

![looking good](https://media.giphy.com/media/llIeHWDIZVAAvByKP0/giphy.gif)
