### ISSUE TITLE
Problem: Disk usage pages are not reporting accurate numbers

### ISSUE THREAD

**Issue by dcraze** [archivematica/Issues#1281]
**Expected behaviour**
Navigate to the Admin->Storage locations tab; the list of locations should show accurate used and available numbers for each location.
Navigate to the Admin->Processing storage usage page and click the Calculate disk usage button; the Disk usage numbers in the General information section displays an accurate number for the disk space used

**Current behaviour**
Navigate to the Admin->Storage locations tab; the list of locations shows NA for the values for Transfer Backlog and Transfer Source locations.
![image](https://user-images.githubusercontent.com/41158818/90047118-433cae00-dc86-11ea-907f-49eb795bc915.png)

Navigate to the Admin->Processing storage usage page and click the Calculate disk usage button; the Disk usage numbers in the General information section displays 0 bytes used used
![image](https://user-images.githubusercontent.com/41158818/90046944-01ac0300-dc86-11ea-8716-99f26005f8d0.png)

These pages were revamped in the 1.11 release - https://github.com/archivematica/Issues/issues/431

**Your environment (version of Archivematica, operating system, other relevant details)**
version 1.11.2

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
Related to https://github.com/archivematica/Issues/issues/312

**Comment by tw4l** [comment]
The issue lies with the function [`_usage_get_directory_used_bytes`](https://github.com/artefactual/archivematica/blob/c7552ce3e1986483752067a58fd202a38b34da3b/src/dashboard/src/components/administration/views.py#L375-L391), which runs `du` via a subprocess and checks the output.

When the directory being measured has directories that the `archivematica` user doesn't have permissions to (which is always true when we're measuring the server's root directory), `du` returns an exit code of 1, `subprocess.check_output` throws a `subprocess.CalledProcessError`, and the function returns 0 instead of whatever byte count was printed to stdout.

As an example of what's happening, here's what happens when I run the `du` command issued by `_usage_get_directory_used_bytes`  as the `archivematica` user on one of our AM 1.11 QA VMs.

```
$ du --one-file-system --bytes --summarize /
du: cannot read directory '/etc/polkit-1/localauthority': Permission denied
du: cannot read directory '/etc/ssl/private': Permission denied
du: cannot read directory '/etc/sudoers.d': Permission denied
du: cannot read directory '/etc/elasticsearch': Permission denied
du: cannot read directory '/home/ubuntu/.gnupg': Permission denied
du: cannot read directory '/home/ubuntu/.ssh': Permission denied
du: cannot read directory '/home/ubuntu/.ansible': Permission denied
du: cannot read directory '/home/ubuntu/.cache': Permission denied
[... truncated ...]
du: cannot read directory '/var/lib/mysql-files': Permission denied
du: cannot read directory '/var/lib/elasticsearch': Permission denied
7815993444	/
```

We could modify the function to more gracefully handle a non-zero exit code like so:

```
def _usage_get_directory_used_bytes(path):
    """Check the space used at a given path.

    :param string path: path to check.
    :returns: usage in bytes.
    """
    try:
        output = subprocess.check_output(
            ["du", "--one-file-system", "--bytes", "--summarize", path]
        ).decode("utf8")
        return output.split("\t")[0]
    except OSError:
        logger.exception("No such directory: %s", path)
        return 0
    except subprocess.CalledProcessError as err:
        logger.warning("Non-zero exit code while determining size used of %s. Some directories may be missing from total.", path)
        return err.output.split("\t")[0]
```

But it's worth noting that the directories `archivematica` doesn't have permissions to won't be included in the total, meaning that the size reported won't be 100% accurate.

We don't have the same issue when the mount point is `/var/archivematica/` or `/var/archivematica/sharedDirectory/` instead of `/` because the `archivematica` has full permissions to the contents of that directory and so `du` returns an exit code of 0. This also circumvents the inaccurate reporting mentioned above. So we could also avoid the issue in deployments by encouraging that processing space is mounted at one of those directories rather than at root.

I think the two strategies together (handle a non-zero exit code more gracefully and make changes in our deployments that circumvent the issue) might be the best way to move forward.

**Comment by amayita** [comment]
Could you maybe first find out what partition is full by running `df` or `df -h`?
`du` will never work on directories that don't belong to the archivematica user. 
You could first check what directory/partition is full with df:
```
root@atom# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           681M   73M  609M  11% /run
/dev/sda1        97G   11G   87G  100% /
tmpfs           3.4G     0  3.4G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/sdb        200G  198G     0 100% /mnt/st-atom
tmpfs           681M     0  681M   0% /run/user/999
``

Once you have approx located the full partition, you can run `du` in that directory, which is likely to belong to archivematica:

`du -shc  /mnt/st-atom`
And work from there.

**Comment by sevein** [comment]
@amayita, that sounds like a good idea but we're past code freeze and the only change that we managed to make was https://github.com/artefactual/archivematica/pull/1640. Do you think it addresses the original issue?

**Comment by amayita** [comment]
@tw4l  Would you like to try this https://github.com/zevv/duc for the am disk usage tab? I think it can be queried and I'd love to see that tab fixed.

**Comment by amayita** [comment]
@tw4l  Would you like to try this https://github.com/zevv/duc for the am disk usage tab? I think it can be queried and I'd love to see that tab fixed.

There's some example of usage here:
https://slowkow.com/notes/monitor-disk-usage/
