### ISSUE TITLE
Problem: Transfers won't start following 1.11 -> 1.12 upgrade path unless you open the processing config administration page

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1282]
**Expected behaviour**

Upgrading to 1.12 from 1.11 should work and transfers should start without strange workarounds.

**Current behaviour**

There's a problem starting transfers but there are no particularly obvious error-traces. Opening the processing config page and doing nothing else will let transfers start again.

**Steps to reproduce**

From @tw4l and @replaceafill on Docker you can upgrade like this:

* Ingest some AIPs in 1.11
* Switch AM to `qa/1.x` and AMSS to `qa/0.x` and run: `docker-compose up -d --build`
​* AM migrations: `docker-compose run --rm --entrypoint /src/dashboard/src/manage.py archivematica-dashboard migrate --noinput`
​* Storage migrations: `docker-compose run --rm --entrypoint /src/storage_service/manage.py archivematica-storage-service migrate --noinput`
* Frontend: `docker-compose run --rm --no-deps --user root --entrypoint npm --workdir /src/dashboard/frontend archivematica-dashboard install --unsafe-perm`
* Elastic: `docker-compose run --rm --entrypoint /src/dashboard/src/manage.py archivematica-dashboard update_elasticsearch_mappings`

Then try starting one transfer. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Latest `qa/1.x`:
```
commit ea5f700b7f1a613e3225a997c31f621c099c47bd (HEAD -> qa/1.x, origin/qa/1.x)
Author: Jesús García Crespo <jesus@sevein.com>
Date:   Mon Aug 10 20:03:00 2020 +0200

    fpr: stop using get_all_related_objects

    ...
```

**Additional information**

* We've seen this at a client site with Ansible too. 
* Re-creating this in Docker does take time: ~30 mins to round-trip once? So literally haven't had the time to get to the bottom of this as much as one would like, so the notes below are very rough. 
* The processing config workaround might not be entirely a coincidence, it invokes the get storage locations function, and this module was touched in https://github.com/artefactual/archivematica/commit/c75092435aa742f89926f281386bfda86de2f6f5 which I wrote and at least one rogue line I see is the function name being sent to the Prometheus counter. And I haven't tested whether this is the issue. It seems unlikely, but stranger things have happened... we had a hunch it might be to do with this commit as other commits not long before this worked for the client acceptance testing. Again, literally not enough time to get closer to an answer. 

**And finally**

Strike this from my issues logged tally, really just reporting on behalf of @tw4l and @mamedin as they spotted it and I was offering a second eye. Making sure we don't forget this before heading off today. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
I'm deeming this bug Too Weird To Release With so I've put the 1.12 milestone on.

**Comment by tw4l** [comment]
This appears to actually be an issue with CSRF tokens related to the following change to how CSRF is handled in Django 1.10: "To protect against BREACH attacks, the CSRF protection mechanism now changes the form token value on every request (while keeping an invariant secret which can be used to validate the different tokens)" (source: [Django 1.10 release notes](https://docs.djangoproject.com/en/3.1/releases/1.10/#csrf)).

The first clue that this had to do with something other than processing configurations was that after upgrading from Archivematica 1.11 to 1.12 in my Docker dev environment, I was able to successfully start a transfer from the API, specifying any of the available processing configurations.

So this worked:

```
curl -X POST -H "Authorization: ApiKey test:test" -H "Content-Type: application/json" \
     -d "{\
         \"path\": \"$(echo -n '/home/archivematica/archivematica-sampledata/SampleTransfers/Images' | base64 -w 0)\", \
         \"name\": \"1.12 api test automated\", \
         \"processing_config\": \"automated\", \
         \"type\": \"standard\" \
         }" \
    "http://localhost:62080/api/v2beta/package"
```

But attempting to start the equivalent transfer (same transfer source path, same name, same processing configuration) via the Archivematica GUI did not. In Firefox dev tools, I can see that the `POST http://127.0.0.1:62080/api/v2beta/package/` API call made when I attempted to start a transfer in the GUI resulted in a in `403 FORBIDDEN` response (body: `{"message": "API key not valid.", "error": true}`). The error message is a little misleading, as it's actually [the canned message for any failed authentication attempt](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/components/api/views.py#L162-L165), including if the issue lies with CSRF and not the API key.

I note at this point the "Content" value for the CSRF token stored in my browser's cookies for localhost is 32 characters long.

After I open any page involving a form in Archivematica (e.g. the Edit page for a processing configuration, or my user profile at `localhost:62080/administration/accounts/profile/`), two things happen:
1. The CSRF token is replaced with a new one that has a "Content" value 64 characters long.
2.  I can now successfully start transfers from the GUI.

So it seems that what's required is to update the CSRF cookie following an upgrade, either by going to any form in Archivematica or via a programmatic method yet to be determined.

**Comment by sallain** [comment]
Oh this is good info @tw4l. A programmatic method would probably be best, if possible, since having to include an upgrade instruction of "go to any form in AM" is almost certainly going to result in lots of emails to the forum :joy: I'll defer to @sromkey and @sevein on that one though!

**Comment by tw4l** [comment]
Thanks @sallain, and agreed on the fix! :laughing: I feel like at this point I have a clear idea of the symptoms but not am still a bit shaky on the root cause. I will keep looking into it a bit further and see if I can't suggest something a bit more user-friendly for the upgrade :smile:

**Comment by tw4l** [comment]
Also from the Django 1.10 release notes, under the [Miscellaneous header](https://docs.djangoproject.com/en/3.0/releases/1.10/#miscellaneous):

> CSRF token values are now required to be strings of 64 alphanumerics; values of 32 alphanumerics, as set by older versions of Django by default, are automatically replaced by strings of 64 characters. Other values are considered invalid. This should only affect developers or users who replace these tokens.

**Comment by tw4l** [comment]
Per the [Django docs](https://docs.djangoproject.com/en/1.11/ref/csrf/#why-might-a-user-encounter-a-csrf-validation-failure-after-logging-in), CSRF tokens are rotated every time a user logs in:

>  For security reasons, CSRF tokens are rotated each time a user logs in. Any page with a form generated before a login will have an old, invalid CSRF token and need to be reloaded. This might happen if a user uses the back button after a login or if they log in in a different browser tab.

This means that for most users, logging out and logging back in will be enough to avoid this issue.

We seem to have seen it in a client Ansible install specifically because with CAS authentication enabled, CSRF tokens do not seem to be rotated on authentication, and so the issue with starting transfers from the GUI only resolves itself if a user does something else that causes a token rotation, such as going to a page with a form that is CSRF-protected.

One possibility might be adding code into the custom CAS middleware to manually rotate the CSRF tokens on login. @sevein also suggested that running `migrate.py clearsessions` during the upgrade might do the trick. I will continue to investigate first thing Monday.

**Comment by tw4l** [comment]
Okay, I've had a bit more time to test this more thoroughly and have a clearer sense of what's happening and how to avoid it. This issue happens when all of the following are true:

1. User is logged in. Session and CSRF cookies are stored on the local browser.
2. The upgrade to Archivematica 1.12 happens.
3. Post-upgrade, a user goes to Archivematica in their browser (without logging out or visiting any page with a form) and attempts to start a transfer with their now-outdated 32-character CSRF token. Consequently, the transfer doesn't start (API response `403 FORBIDDEN`), but the GUI doesn't provide any feedback to this effect other than the the transfer not appearing.

Logging out and logging back in again (whether CAS is enabled or not, contrary to what I said earlier) rotates the CSRF token and fixes the issue, as does visiting any page in Archivematica that contains a form. What we need to do is to log all users out by clearing their sessions.

`manage.py clearsessions` only clears expired sessions, not active ones, so that won't quite do it. Instead what I think what we need to do is to clear the `MCP.django_session` table as part of the upgrade process. For example, in the Docker dev environment: `docker-compose exec mysql mysql -hlocalhost -uroot -p12345 -e "DELETE FROM MCP.django_session"`.

This way, when users go to Archivematica in their browser following the upgrade, they will be required to log in, which will rotate the CSRF token and prevent them from hitting this issue.

**Comment by sevein** [comment]
Thanks @tw4l. It sounds like something that we should describe in our [release notes](https://wiki.archivematica.org/Archivematica_1.12.0_and_Storage_Service_0.17.0_release_notes). Do you think it is possible this is only affecting users in DEBUG mode? Django 1.10 [release notes](https://docs.djangoproject.com/en/3.1/releases/1.10/#miscellaneous) read the following:

> CSRF token values are now required to be strings of 64 alphanumerics; values of 32 alphanumerics, as set by older versions of Django by default, are automatically replaced by strings of 64 characters. Other values are considered invalid. *This should only affect developers or users who replace these tokens.*

@mamedin, was the QA site by any chance in DEBUG mode?

**Comment by tw4l** [comment]
@sevein It is curious about the `csrf_exempt` decorator. We [let Tastypie handle the CSRF check for API calls](https://github.com/artefactual/archivematica/commit/853ab333f4c7fe98ab7d7058d73ade0a6c6483ab). But Tastypie's `SessionAuthentication` calls [the same Django _sanitize_function](https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/authentication.py#L314) that you point out above for the CSRF check, so I would expect that to work.

I'm not sure about whether this only happens in DEBUG mode but it's a good question. The client deploy where we ran into this was a test server, so it's certainly possible.

**Comment by sevein** [comment]
@tw4l @sromkey, here are the changes:
* Mention in the [release notes](https://wiki.archivematica.org/Archivematica_1.12.0_and_Storage_Service_0.17.0_release_notes), and
* Notes one how to clear sessions (PR: https://github.com/artefactual/archivematica-docs/pull/388).

Feel free to suggest changes.

**Comment by tw4l** [comment]
Looks good @sevein ! I submitted a PR with an additional command to run when using CAS authentication: https://github.com/artefactual/archivematica-docs/pull/389.
