### ISSUE TITLE
METS XML file generator crashes under high load

### ISSUE THREAD

**Issue by dnarc** [archivematica/Issues#1411]
While handling ingests of multiple thousands of files, the METS XML file generator (createMETS) will often stop working, failing the ingest, and is very slow in the general case.

I suspect this is due to the recursive nature of the implementation.

Version: 1.6.1

**Comment by ross-spencer** [comment]
Closing as duplicate of https://github.com/archivematica/Issues/issues/1203 - if this is done in error then some further context around the issue would be great. Number of files, breakdown of file-types. Whether the situation is better since AM `1.6.1` etc. Otherwise Matthew's issue may be a suitable vehicle for further discussions here.
