### ISSUE TITLE
Problem: Bags with a processingMCP.xml fail

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#1467]
**Expected behaviour**
If a processingMCP.xml file is included in a bag as a transfer, the bag should be verified and continue to process, and the processingMCP values should be used. 

**Current behaviour**
The transfer fails at Verify bag and restructure for compliance:
```
ERROR: file information not found: no results found for arguments: {'removedtime__isnull': True, 'currentlocation': '%transferDirectory%data/processingMCP.xml', 'transfer_id': '979be0a3-cec6-49bb-8ea9-cb0171fb1eaa'}
```

**Steps to reproduce**
Create a zipped or unzipped bag transfer using `SampleTransfers/BagExamples/SimpleBagWithProcessingMCP`

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x during 1.13 release testing

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I think this was caused by a change made in https://github.com/artefactual/archivematica/pull/1748 to the `assign_file_uuids.py` script which now ignores the `processingMCP.xml` file when creating `File` objects. As far as I can tell it didn't do that before, and it seems to be only a problem for the bag workflow because [the `verify_and_restructure_transfer_bag.py` expects the file to exist](https://github.com/artefactual/archivematica/blob/fef98993552f8d62f576a30be16306b4f49f49fb/src/MCPClient/lib/clientScripts/verify_and_restructure_transfer_bag.py#L138-L148).
