### ISSUE TITLE
Problem: AM services restart duplicates the uploaded DIP on AtoM server

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1488]
**Expected behaviour**

Once the transfer is finished, if the AM services are restarted the DIP should not be uploaded again.

**Current behaviour**

When restarting AM services all the uploaded DIPs are uploaded again

**Steps to reproduce**

You can reproduce on amdemo, uploading a DIP to atomdemo and the restart amservices:

```
sudo service archivematica-mcp-server restart
sudo service archivematica-mcp-client restart
sudo service archivematica-dashboard restart
```

And depending on the processing config selected, the DIP will be uploaded again or a pop up will ask you about the dip upload.

**Your environment (version of Archivematica, operating system, other relevant details)**

Ubuntu 16.04 and AM1.13.1
Ubuntu 18.04 and AM1.12.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
See also https://github.com/archivematica/Issues/issues/112. As described in https://github.com/archivematica/Issues/issues/112#issuecomment-415766232, a fix was included in Archivematica 1.7 to clear the `uploadDIP` watched directory after a DIP is stored. However, if a DIP is not stored, this directory is not cleared and so the workflow is kicked off at the Upload DIP microservice when mcp-server is restarted.

Still in progress but I think the solution may be to move the DIP from `uploadDIP` to `uploadedDIPs` after DIP upload, rather than copying it (as is currently done, resulting in two copies of the DIP, one in each directory), so that the DIP is no longer in that watched directory after being uploaded.

**Comment by tw4l** [comment]
This fix should come after https://github.com/archivematica/Issues/issues/1496, which is preventing DIP upload at present in some Archivematica 1.13 instances.

**Comment by sevein** [comment]
For QA, make sure that that "Store DIP?" works as expected, i.e. it should be possible to store DIPs and handle unstored DIPs (move to rejected/).

**Comment by replaceafill** [comment]
I've confirmed this works. Tested several combinations (DIPs uploaded and stored, DIPs uploaded and not stored, No uploads, pending DIP upload input choices, finished transfers, transfers in progress, etc) and then restarted the Archivematica services. Old DIP Upload jobs are not re-triggered anymore.
