### ISSUE TITLE
Problem: Normalization using Inkscape failing for deb and rpm envs

### ISSUE THREAD

**Issue by currmie** [archivematica/Issues#1542]
**Expected behaviour**
In sampleData/Images the files Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.eps and lion.svg should be normalized for preservation using Inkscape

**Current behaviour**
File found: d959ea6a-f37a-428c-8852-552bdc52f918 %SIPDirectory%objects/Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.eps
Checking for a manually normalized file by trying to get the unique file that matches SIP UUID 70aff152-e09a-431d-bc55-d0901d65c171 and whose currentlocation value starts with this path: %SIPDirectory%objects/manualNormalization/preservation/Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.
No such file found.
Not normalizing Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.eps  - No rule or default rule found to normalize for preservation

**Steps to reproduce**
Ingest sampleData/Images and choose Normalize for preservation. View the normalization command output in the normalization report.

**Your environment (version of Archivematica, operating system, other relevant details)**
Reported by on-prem user using Centos servers.
Verified that this is also an issue on Ubuntu 18.04.3 LTS (Bionic Beaver) test server.
Could this possibly be a regression of [#537](https://github.com/archivematica/Issues/issues/537)?

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
It looks like we have normalization rules for fmt/123 but this sample file is ID'd as fmt/124. Possibly something changed in the PRONOM signature that changes how it's identified and now there's no rule for the format. I would suggest trying to make a rule for fmt/124 and see if that works.

**Comment by currmie** [comment]
Thanks @sromkey , I looked into the normalization rules for fmt/124, and looks like there is one already set up and enabled on my test server. AM still failed to identify the sample file.

![image](https://user-images.githubusercontent.com/35077919/158485919-b0e3a3d6-24a3-4322-81c8-7c3bb44f6edc.png)

**Comment by jhsimpson** [comment]
@currmie I tried the images sample transfer on a 1.13.0 archivematica and got the same output as you (not normalizing no rule found'.  I noticed that the default processing configuration was set  to not identify file formats.  The METS file showed the pronom format as 'unknown' for the eps file.

I tried again with file format identification turned on.  When the eps is identified as fmt/124, normalization was attempted, but it failed, with an error that makes me think this is related to using python 3 instead of python 2.

stdout:
`File found: 21b25115-d328-4e11-b257-4c0957c735a7 %SIPDirectory%objects/Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.eps
Checking for a manually normalized file by trying to get the unique file that matches SIP UUID 1546c100-ff77-40f8-ae4f-3a649a9d85a8 and whose currentlocation value starts with this path: %SIPDirectory%objects/manualNormalization/preservation/Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.
No such file found.
File format: Image (Vector): Encapsulated PostScript: EPS 3 (fmt/124)
Format Policy Rule: Format policy rule 3e9ad70d-67db-489e-a64d-b52997e267fb
Format Policy Command Transcoding to plain svg with inkscape
Command to execute: /usr/bin/inkscape "/var/archivematica/sharedDirectory/currentlyProcessing/13images-1546c100-ff77-40f8-ae4f-3a649a9d85a8/objects/Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight.eps" --export-plain-svg="/var/archivematica/sharedDirectory/currentlyProcessing/13images-1546c100-ff77-40f8-ae4f-3a649a9d85a8/objects/Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight-dfc3de2d-1c20-445b-81bd-0bb942d7d387.svg"
chmod 777 "/var/archivematica/sharedDirectory/currentlyProcessing/13images-1546c100-ff77-40f8-ae4f-3a649a9d85a8/objects/Vector.NET-Free-Vector-Art-Pack-28-Freedom-Flight-dfc3de2d-1c20-445b-81bd-0bb942d7d387.svg"
-----
Command stdout:
Execution failed:`


stderr
`not expecting type '<class 'list'>'`

**Comment by jhsimpson** [comment]
Another note, the exact same inkscape command was run on the lion.svg file (fmt/91) and that worked fine.

**Comment by currmie** [comment]
@jhsimpson -- I've  got Inkscape 0.92.3 (2405546, 2018-03-11) on my test server and then saw [this](https://inkscape.gitlab.io/extensions/documentation/authors/interpreters.html#selecting-a-specific-interpreter-version-via-preferences-file): in the Inkex docs:

> Inkscape extensions that rely on inkex.py will only work with Python 2 (as of Inkscape 0.92.1), while on some recent Linux distributions, the default Python version used is Python 3, which results in errors during execution of extensions

Your error appears to support that possibility.

**Comment by replaceafill** [comment]
@currmie I just tested the fix you linked in the previous comment in the `am113centos` server and seems to address this problem.

First, I reset the `automated` processing configuration and started a `Standard` transfer using `SampleTransfers/Images` and got the normalization error.

Then I edited the `/var/lib/archivematica/.config/inkscape/preferences.xml` file and changed `<group id="extensions">` to `<group id="extensions" python-interpreter="/usr/bin/python2.7">`

Finally I ran a new `Standard` transfer using the same files and this time there is no normalization error and the AIP contains the SVG file.

**Comment by currmie** [comment]
>@currmie I just tested the fix you linked in the previous comment in the am113centos server and seems to address this problem.

That's awesome, @replaceafill !

**Comment by replaceafill** [comment]
We plan to add a note to the installation documentation explaining how to set up the Python interpreter for `inkscape`. This also might change in Archivematica 1.15 when we support new versions of Ubuntu and Rocky Linux.

**Comment by sromkey** [comment]
Normalization rule now working as expected in 1.16!
