### ISSUE TITLE
Problem: DIP storage not automated after Uploading a DIP

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#1551]
**Expected behaviour**

If a processing configuration is used that automates the storage of a DIP to a location, that should be enacted regardless of the Upload DIP configuration.

**Current behaviour**

It is only enacted automatically if the processing configuration is set to not upload DIP; if upload DIP is set to any of the existing options, it won't automatically store.

**Steps to reproduce**

1. Create a processing configuration that includes Do Not Upload DIP and then yes to Store DIP, process a transfer using that configuration.
2. Re-try after changing the processing configuration to use ArchivesSpace, AtoM or CONTENTdm and observe that the Store DIP is no longer automated

**Your environment (version of Archivematica, operating system, other relevant details)**

1.13.2

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by arthytrip** [comment]
Hello,
thanks to the help of a colleague of mine, we saw that the problem was introduced by [commit a6eab06](https://github.com/artefactual/archivematica/commit/a6eab0642b3c7e3d4c32fde0e57758a2b32f24fa) of 27 September 2021.
The commit puts a change to the workflow.json file (it changes a "copy" to a "move") and that is precisely the cause: MCPServer no longer finds the Processing Configuration file because the whole SIP folder has been moved, instead of only copied, in the uploadedDIPs directory.

Going deeper, there seems to be a discrepancy between some information.

In the [migration 0038_fix_workflow_store_dip.py](https://github.com/artefactual/archivematica/blob/stable/1.13.x/src/dashboard/src/main/migrations/0038_fix_workflow_store_dip.py) of 6 August 2019, point 5 says ...

    5. Change "move" to "copy" in "move to uploadedDIPS dectory" so that the
       SIP is still where MCPServer expects it to be and preconfigured choices
       can work for Store DIP and Store DIP locations.

This seems right!

Instead, in the [commit a6eab06](https://github.com/artefactual/archivematica/commit/a6eab0642b3c7e3d4c32fde0e57758a2b32f24fa) 27 September 2021 we read this explanation ...

    This commit modifies the workflow to move DIPs from the uploadDIP to
    uploadedDIPs watched directories instead of copying. This change fixes
    an issue where an MCPServer restart was causing Archivematica to
    attempt a duplicate DIP upload.

We have not found the issue relating to the MCPServer restart problem but in any case it seems to us that the problem introduced is more serious than the hypothetical issue because it alters the functioning of the normal workflow to prevent an hypothetical problem that occurs following an exceptional event. The MCPServer service should not restart by itself and if there is a need for a restart you must first understand what was being processed at the time of its stop and proceed accordingly.

**Comment by tw4l** [comment]
Hi @arthytrip , good catch and sorry for the trouble!

Commit https://github.com/artefactual/archivematica/commit/a6eab0642b3c7e3d4c32fde0e57758a2b32f24fa was intended to fix https://github.com/archivematica/Issues/issues/1488, which had been causing issues in a few client installations. It seems I messed a bit of context in that work - thank you for pointing out that very helpful migration.

Ideally we'd find a solution here where we're not simply choosing between bugs. Just off the cuff, maybe we could have MCPServer read in and store the processing config values, rather than looking for them on disk each time.

**Comment by mamedin** [comment]
I could reproduce the issue, but setting `Upload DIP: None` in the processing config and Uploading the DIP when having the prompt. So I think we can change the issue tittle from "Problem: DIP storage not automated when DIP upload configuration is used" to "Problem: DIP storage not automated after Uploading a DIP", because the issue happens when Uploading a DIP, not only when `Upload DIP` is enabled on processing config.

**Comment by Dhwaniartefact** [comment]
> I could reproduce the issue, but setting `Upload DIP: None` in the processing config and Uploading the DIP when having the prompt. So I think we can change the issue tittle from "Problem: DIP storage not automated when DIP upload configuration is used" to "Problem: DIP storage not automated after Uploading a DIP", because the issue happens when Uploading a DIP, not only when `Upload DIP` is enabled on processing config.

sure let me do so. Thank you
