### ISSUE TITLE
Problem: "Download CSV"-button in Archival Storage tab disappears when "Show files?" is checkmarked

### ISSUE THREAD

**Issue by cannedit** [archivematica/Issues#1576]
**Expected behaviour**
When I perform a search within the tab "Archival Storage" in the Archivematica v1.13.2 dashboard and checkmark "show files" in the search parameters, then I would like the "Download CSV"-button to be there in order to download the search results as CSV file.

**Current behaviour**
When I perform a search within the tab "Archival Storage" in the Archivematica v1.13.2 dashboard and checkmark "show files" in the search parameters, then the "Download CSV"-button disappears, so I can't download the results of that search.

**Steps to reproduce**
* Log into the Archivematica v1.13.2 dashboard
* Go to the tab  "Archival Storage"
* Set your search parameters including checkmarking "Show files?"

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica v1.13.2

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by eviau-artefactual** [comment]
We are currently going through past issues. 

Thank you for highlighting this!

We think this is the expected behaviour, as the _Download CSV_ button exports AIP metadata, and not file metadata.

This is [mentioned in the documentation](https://www.archivematica.org/en/docs/archivematica-1.15/user-manual/archival-storage/archival-storage/#downloading-all-aip-metadata-in-a-csv-file), and you read a bit more about this in previous [PR](https://github.com/artefactual/archivematica/pull/1626) and [Issue](https://github.com/archivematica/Issues/issues/1213).

Closing this for now.
