### ISSUE TITLE
Enhancement: don't hold open a database transaction when computing checksums

### ISSUE THREAD

**Issue by alexwlchan** [archivematica/Issues#1577]
I have a patch that improves Archivematica's ability to store checksums for large files, but want to double check you want it before I submit.

**Expected behaviour**
Archivematica can successfully store large files.

**Current behaviour**
Sometimes large files can fail to compute checksums with the following error (here large means ~180GB):

```
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

This error occurs in the `update_size_and_checksum.py` script.

**Steps to reproduce**
I don't have an exact reproduction. But I do have a suggested fix, in this diff: [d2dacf2afd6cc91bf1a4b13fe779ff91d9042fef.txt](https://github.com/archivematica/Issues/files/9785369/d2dacf2afd6cc91bf1a4b13fe779ff91d9042fef.txt)

It precomputes all the checksums and file sizes upfront, before opening a database transaction – so the database activity itself is fairly quick. The commit message explains a bit more about the issue.

**Your environment (version of Archivematica, operating system, other relevant details)**
This was in the Wellcome fork of Archivematica, which is based on 0.11.x I think? I've tested this as working in our environment.

It doesn't apply cleanly in 0.13.x because you've made some other changes – in particular batching the files into groups of 10 – but opening this ticket to start a conversation.

I'm happy to do the legwork to tidy this up and get it in 0.13.x, but I don't want to start if you're not interested in the change.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Hey @alexwlchan , thanks so much! An interesting problem that we haven't encountered personally but I believe it ;) 

@sevein would you have time to take a look at this just in case there is a technical consideration I do not know of, but otherwise I think we would encourage Alex to continue with a PR?

**Comment by sevein** [comment]
I think this is a great idea, thanks @alexwlchan! We tried something similar in [archivematica_clamscan.py](https://github.com/artefactual/archivematica/blob/4f4605453d5a8796f6a739fa9664921bdb3418f2/src/MCPClient/lib/clientScripts/archivematica_clamscan.py#L370-L379) and it went well. It's a bit endemic really, the issue is present in every client script.
Related issue: https://github.com/archivematica/Issues/issues/313.

**Comment by mamedin** [comment]
Thanks @alexwlchan I was going to open a similar issue for the Compress AIP microservice. It opens the MySQL connection just at the start of the microservice and then start the compression tasks. The problem is that if it takes more than 8 hours (default wait timeout on MySQL) it fails when trying to write on database. As workaround you can increase the wait timeout on MySQL but it is not usually a good idea (it can creates new issues related to max connections limit).

**Comment by mamedin** [comment]
This other issue is the same: https://github.com/archivematica/Issues/issues/1580

**Comment by replaceafill** [comment]
Hello @alexwlchan :wave:. We'd like to include this in the Archivematica 1.14 release. Would you be interested in creating a pull request or would you prefer us to create it from the patch you provided? Let us know.

**Comment by Dhwaniartefact** [comment]
I verified this in my development environment by creating large file source directory and it does not hold open a database transaction while computing checksum for the transfer.
