### ISSUE TITLE
Problem: EOL dates approaching for Ubuntu 18.04 and RHEL

### ISSUE THREAD

**Issue by FingerlessGlov3s** [archivematica/Issues#1590]
**Expected behaviour**
Archivematica should be compatible with Linux distributions that are actively maintained only.

Should move to latest LTS releases ideally. 22.04 and RHEL 9

**Current behaviour**
Currently Ubuntu and RHEL are the supported distributions
Ubuntu 18.04 is EOL come April [Life CycleDocs](https://wiki.ubuntu.com/Releases)
RHEL 7 is EOL come 20th June 2024 [Life Cycle Docs](https://access.redhat.com/support/policy/updates/errata)

**Steps to reproduce**
Visit links above

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by RussellMcOrmond** [comment]
I am going to repeat my recommendation on how to solve this, and expand the systems Archivematica is compatible with: use Docker.

I offer FOLIO as an example. https://docs.folio.org/docs/getting-started/installation/
They also offer pre-built Vagrant boxes, but these vagrant boxes run all the FOLIO software within docker containers within those boxes.


All management of the environment that Archivematica would run within, and what libraries it needs to be compatible with, would be within containers. Documentation on how to install and configure Archivematica for anyone not using the Vagrant boxes would be in terms of Docker Hub stored containers, rather than packages within RPM and APT repositories.

After a transition period, Artefactual would be able to drop https://packages.archivematica.org/ completely. This is quite a bit of work to manage packages for different environments https://packages.archivematica.org/1.13.x/ (including special Ansible rules, which could easily be ported to Dockerfile rules and be universal across a very wide variety of platforms).

**Comment by sromkey** [comment]
Hi there- we're working on roadmap plans currently to address the upcoming EOL for Ubuntu and RHEL. Please keep an eye on the user [Google Group](https://groups.google.com/g/archivematica) for announcements but we will use this issue to track our work also.
