### ISSUE TITLE
Problem: A leading slash can prevent the download of uncompressed AIPs from Duracloud

### ISSUE THREAD

**Issue by kellyannewithane** [archivematica/Issues#171]
**Expected behaviour**
From the archival storage tab I should be able to download an uncompressed AIP

**Current behaviour**
When attempt to download an AIP on the Archival Storage tab, I get this error: Error re-ingesting package: An unknown error occurred.

**Steps to reproduce**
Make AIP, try to download it!

**Your environment (version of Archivematica, OS version, etc)**
AM1.7.2 with AIP storage location set to Duracloud

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by ross-spencer** [comment]
It turns out this is a configuration issue. I have added the triage-label for 1.11 to discuss:

1. Updating the docs.
2. Create a PR against the storage service to strip leading `/` forward-slash characters. 

**The problem**

_A leading `/` forward-slash in a Duraspace location will prevent individual files from being discovered in Duraspace as it creates the wrong prefix to search for when the storage service talks to Duraspace:_

```
URL: https://archivematica.duracloud.org/durastore/dev-test/, 
params: {'prefix': '/aips/8811/b0ee/f7bb/.../dura-test-2-8811b0ee-f7bb-...c532'}
```

You can use the UI as an analogy,

![image](https://user-images.githubusercontent.com/1880412/67860787-11a38d80-fb1f-11e9-8092-e29978bff2cd.png)

Where the list of files is prefixed with `aips` not `/aips` a search in the UI for the former will be successful where the latter will fail. 

The storage service suffers the same problem querying Duraspace.

**Soltuion/Workaround**

If your path has a slash, dash-it! (remove it).

![image](https://user-images.githubusercontent.com/1880412/67860896-5f1ffa80-fb1f-11e9-818c-0a531458ae16.png)

Needs to be:

![image](https://user-images.githubusercontent.com/1880412/67860936-752dbb00-fb1f-11e9-8c44-b682935ede19.png)

Users may need to do this in:

* Space configuration (`Path`)
* Location configuration (`'Relative-path`)

Once removed, you should be able to download uncompressed AIPs from Duraspace.

**Comment by sallain** [comment]
@ross-spencer @sromkey Does there really need to be an AM PR for this, or is the docs PR I've submitted sufficient?

**Comment by ross-spencer** [comment]
I can't see the change in the docs where this is explicit @sallain? 

I have two opinions:

1. From a customer facing perspective if the slash is there and you can't download from the storage space per this ticket, it doesn't look great. 
2. From a support perspective, say I spent 2-3 hours trying to pick this one apart, and then later someone falls over the same issue (as Amaya did a few weeks after), they might also spend that same time as its not an obvious one to see (because it stores okay, it just doesn't get retrieved okay, so it could be anything in-between) it gets quite costly. 

So my wish-list would be an explicit reference in the docs would be great if you have time, and a PR against the storage service given recent conversations, to make sure it doesn't happen via code or reversed via docs would be incredible. 

Here is a [link](https://artefactual.slack.com/archives/C08Q3FSSZ/p1573647687080700) (internal Slack) to the last time this occurred but we were able to fix it with the docs in this ticket. It's an easy one to demonstrate if it helps too.

**Comment by sallain** [comment]
I think we can only afford to solve this problem via documentation for now, but it's explicit in the AM docs that the relative path in the SS location must be identical to the space name in DuraCloud and must not contain a leading slash.
