### ISSUE TITLE
Problem: the versions shown for fpr tools are outdated

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#191]
**Expected behaviour**
The version shown in Preservation planning -> Format policy registry -> tools  corresponds with the ones available in the system

**Current behaviour**
In some cases, the tools installed in the system are newer than the ones listed

**Steps to reproduce**

Check installed versions for inkscape, cp, ffmpeg...

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by ablwr** [comment]
I did some investigative work here and the METS shows what the system is actually using. The systems don't necessarily use the same version, and @sromkey would prefer that we remove versioning from the FPR since we can't make it consistent. I'll work on this after 1.8.

**Comment by sallain** [comment]
@ablwr We still have tool versions for identification tools (since they have their own section, for some reason). Thoughts?

![Screenshot of Archivematica Dashboard - Format Policy Registry - Identification tools.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/c5c45f98-278c-4b94-b075-6641d0b1a33e/Screenshot+of+Archivematica+Dashboard+-+Format+Policy+Registry+-+Identification+tools.jpg)

**Comment by ablwr** [comment]
Identification is handled a little differently and we update the versions with each PRONOM registry update, so I think it makes sense to continue to show these because 1) They will always be the same across versions 2) they indicate inadvertently which PRONOM release we are up to and 3) yeah they are different from all the other tools!

**Comment by sallain** [comment]
Wonderful!

**Comment by sallain** [comment]
Documentation (including screenshots) need to be updated on the Preservation Planning tab: https://www.archivematica.org/en/docs/archivematica-1.9/user-manual/preservation/preservation-planning/#pres-policies

**Comment by ablwr** [comment]
The screenshots are only of the ID Tools, which still have versions. And we mention the Format Version quite a bit, but that is specific to the FPR and we still show that. We don't mention the tool versions on this page!

**Comment by ablwr** [comment]
Although the docs can ALWAYS be improved in this section... I just don't think they are now incorrect because of this change.

**Comment by sallain** [comment]
@ablwr Fair! I didn't look at them in any depth, I was adding documentation labels to a bunch of issues where I thought that docs might need some attention. Thanks for looking into it, I will remove the label!

**Comment by sallain** [comment]
(... apparently I never added the label in the first place :woman_shrugging: )
