### ISSUE TITLE
Problem: Change the name of the sanitize names microservice

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#230]
**Please describe the problem you'd like to be solved.**

Following reading this paper from [Elvia Arroyo-Ramirez](https://medium.com/on-archivy/invisible-defaults-and-perceived-limitations-processing-the-juan-gelman-files-4187fdd36759), via @sallain we would like to consider renaming the sanitize names micro-service. 

The name sanitize does not clearly describe the rationale for the microservice in the Archivematica preservation workflow.

Further the name suggests something 'other' about a collection's names before Archivematica can continue processing. 

The name marginalizes people using the system where Archivematica is not yet fully capable of handling the widest range of character encoding schemes as possible. 

Sara highlighted the following paragraph:

> To times when we must intervene and remove something that is inherent to the context or content of an archival collection, it is our ethical responsibility to document and articulate our need to act. 

**Describe the solution you'd like to see implemented.**

* Consider alternatives to the name we have adopted for this microservice. 
* Document clearly its intent.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
**Documentation that needs updating:**

* https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/transfer/transfer/#create-a-transfer-with-submission-documentation
* https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/ingest/manual-normalization/#normalizing-files-with-the-same-name

**Comment by ablwr** [comment]
:+1:

**Comment by sevein** [comment]
CC @sallain since you did https://github.com/artefactual/archivematica/pull/1344, you may want to tackle this one too.

**Comment by evelynPM** [comment]
If we change the micro-service name we may want to take the opportunity to change the premis eventType too. Note that the term "filename change" was added to the LoC Events vocabulary relatively recently: http://id.loc.gov/vocabulary/preservation/eventType/fil.html. We could use that instead of "name cleanup" for the eventType, and maybe also use it as the basis for a re-named micro-service. See also https://github.com/archivematica/Issues/issues/645.

**Comment by sallain** [comment]
Current usage:

**Transfer tab**

```
Microservice: Clean up names
   Job: Sanitize Transfer name
   Job: Sanitize object's file and directory names
```

![image](https://user-images.githubusercontent.com/4612276/70938322-c96efa80-1ffa-11ea-8d75-cf92114be71d.png)


**Ingest tab**

```
Microservice: Clean up names
   Job: Load Dublin Core metadata from disk <-- (why is this job located in this microservice?)
   Job: Sanitize SIP name
```

![image](https://user-images.githubusercontent.com/4612276/70938658-70ec2d00-1ffb-11ea-8167-93f1a6fd0d2f.png)

**Comment by sallain** [comment]
@romkey @sevein (and anyone else!) Do you think that the microservice names should be different between Transfer and Ingest? For other microservices where there are similar actions on both tabs, AM specifies transfer vs SIP, e.g. `Rename with transfer UUID` and `Rename SIP directory with SIP UUID`

**Comment by sromkey** [comment]
That seems like a fine approach to me!

**Comment by sallain** [comment]
I used @evelynPM's suggestion and tried to keep the proposed changes in-line with the [LoC Events vocabulary](http://id.loc.gov/vocabulary/preservation/eventType/fil.html) in case we decide to change the names of the PREMIS events later on. "Change filenames" also just feels accurate and neutral.

**Transfer tab**

```
Microservice: Change transfer filenames
   Job: Change filename of transfer
   Job: Change filenames for objects and directories
```

![image](https://user-images.githubusercontent.com/4612276/71121252-00781400-2193-11ea-922e-3fea6931be16.png)

**Ingest tab**

```
Microservice: Change SIP filenames
   Job: Load Dublin Core metadata from disk
   Job: Change filename of SIP
```

![image](https://user-images.githubusercontent.com/4612276/71121415-4b922700-2193-11ea-82b3-d0d792ab02e5.png)

---

@sevein - the microservice/job names appear in a few places. `workflow.json` is obviously the most visible place to change them, but should they be changed in the following locations as well? I don't know the purpose/function of these files so I'm not sure.

* `src/dashboard/tests/fixtures/jobs-processing.json`
* `src/dashboard/tests/fixtures/jobs-sip-complete-clean-up-last.json`
* `src/dashboard/tests/fixtures/jobs-sip-complete.json`
* `src/dashboard/src/main/migrations/0002_initial_data.py`

**Comment by ablwr** [comment]
The test fixtures should be changed to represent our code change, but the migrations should not change -- unless that migration works in an unconventional way I don't understand/anticipate.

**Comment by sallain** [comment]
@ablwr that's what I figured!

**Comment by klpn** [comment]
The translations of the names should perhaps also be changed (e.g. the Swedish "sanera", which appears several times in the JSON files, is a direct translation of "sanitize")? But the [rules themselves](https://github.com/artefactual/archivematica/blob/stable/1.10.x/src/MCPClient/lib/clientScripts/sanitize_names.py#L36) seem to come very close to [the POSIX definition of portable filenames](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/V1_chap03.html#tag_03_281), with a few exceptions (parentheses are allowed and filenames may start with hyphen). Is there any reason for these exceptions? Otherwise, they might perhaps be removed, and the service name changed into something like "Make filenames POSIX portable"?

**Comment by sallain** [comment]
@klpn Good eye - the translations in workflow.json don't get edited directly, we manage translations (or will, in the near future) through a separate application called Weblate. When the new strings here are imported into Weblate, they can be updated for accuracy by translators. That means that the translations won't change until 1.12, unfortunately, but that's the process that we have for now.

I can't speak to the rules themselves (maybe @sevein or @ross-spencer can) but I have opened a new issue #1079 about changing the wording in the scripts/logs - so there is definitely still work to be done in this area.

Thanks for your comment!

**Comment by klpn** [comment]
Thanks for the answer! As for the rules, the current restrictive rules, where all non-ASCiI characters are replaced, may not be needed for much longer, because of better Unicode compatibility, so maybe it is not worth bothering with changing them to conform exactly with the POSIX standard. However, some filename transformation may be necessary even in the future (e.g. replacing ASCII control characters, which are not needed by any writing systems, and may create security issues (see [Wheeler](https://dwheeler.com/essays/fixing-unix-linux-filenames.html)).

**Comment by sallain** [comment]
The microservice and job names display the new text. Tested on qa/0.x on Bionic.
