### ISSUE TITLE
Problem: Dataverse microservice names should all be sentence case

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#266]
**Expected behaviour**

Micro-services all use title case.

**Current behaviour**

@sallain in https://github.com/artefactual/archivematica/issues/1148 noticed some inconsistencies in this style:

Microservice: Parse External Files
Job Determine Parse Dataverse METS XML 

**Steps to reproduce**
Process a Dataverse transfer type.

**Your environment (version of Archivematica, OS version, etc)**

1.8 (qa/1.x), all versions.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
@sevein (cc. @sallain @ablwr @sromkey ) I believe this issue should probably be fixed for 1.8 as it involves a migration and we don't want to introduce migrations in minor releases (or we'd alternatively wait for `1.9`. In terms of fixing this, what is the best approach? Do we submit a fix against the migration itself? Or do we introduce a new migration to fix the existing one?

**Comment by sevein** [comment]
@ross-spencer yes, it's ok to update the migration. We've been doing that in other cases as long as the migration isn't part of a release yet. Thanks.

**Comment by ross-spencer** [comment]
Hi @sallain re: the job `Determine Parse Dataverse METS XML` it is needed to query the database to determine whether or not we are still processing a Dataverse transfer and whether ot not the `Parse Dataverse Mets` job needs still to run. I'm not super happy with the name myself and @joel-simpson also questioned it, but do you have a suggested for alternatives?

**Comment by ross-spencer** [comment]
Also, @sallain here is the full list of group names and job descriptions, if you have time, can you verify they look okay?

https://github.com/artefactual/archivematica/blob/8c74f99cdeb75fdeb11494a1f78ec1c8aa26c012/src/dashboard/src/main/migrations/0061_create_dataverse_transfer_type.py#L134-L147

**Comment by sallain** [comment]
For `Determine Parse Dataverse METS XML`, I looked for another similar job and found `Determine if transfer contains packages`. So how about `Determine if Dataverse METS XML needs to be parsed` or similar? This would lead logically into `Parse Dataverse METS XML`.

Now for the list - I have both questions and notes (this is what happens when you give me these opportunities!)

* `TRANSFER_IN_PROGRESS_DESC = "Dataverse transfer in Progress"` - does this mean "this transfer is in progress", or does it mean "this transfer is in a location called Progress" or does it mean something else?

* `SET_CONVERT_DATAVERSE_DESC = "Set convert dataverse structure"` - Dataverse should be capitalized. Is this job setting up the convert job?

* `SET_PARSE_DATAVERSE_DESC = "Set parse Dataverse METS"` - similar question - is this job setting up the parse job, or does set mean something else?

* `DETERMINE_PARSE_DATAVERSE_DESC = "Determine parse Dataverse METS XML"` - see above

**Comment by ross-spencer** [comment]
@sallain this is great! The temptation coding is to be as succinct as possible. I didn't realize we could take a more humanistic approach to naming jobs and micro-services in AM. 

I have these names to offer in response, do they help?

```
VERIFY_COMPLIANCE_GROUP = "Verify transfer compliance"
PARSE_EXTERNAL_FILES_GROUP = "Parse external files"
APPROVE_TRANSFER_DESC = "Approve Dataverse transfer"
SET_TRANSFER_TYPE_DESC = "Set transfer type: Dataverse"
TRANSFER_IN_PROGRESS_DESC = "Set Dataverse transfer in progress"
SET_CONVERT_DATAVERSE_DESC = "Set convert Dataverse structure flag"
SET_PARSE_DATAVERSE_DESC = "Set parse Dataverse METS flag"
CONVERT_DATAVERSE_DESC = "Convert Dataverse structure"
DETERMINE_CONVERSION_DESC = "Determine if Dataverse conversion needs to happen"
DETERMINE_PARSE_DATAVERSE_DESC = \
    "Determine if Dataverse METS XML needs to be parsed"
PARSE_DATAVERSE_METS_DESC = "Parse Dataverse METS XML"
```

The two `Set convert Dataverse structure` and `Set parse Dataverse structure` are about setting unit variables in Archivematica so that if the system finds them set, it will then run the corresponding tasks `Convert Dataverse Structure` and `Parse Dataverse METS XML`. I called them flags in the text above as variables conjure up a different image for me. 

`Set Dataverse transfer in progress` is an internal name used in the database to label something called a `Chain` which basically contains all of the tasks that will be run as part of a Dataverse transfer. 

Does that help? I can easily incorporate other improvements if we still need to wordsmith a bit :+1:

**Comment by sallain** [comment]
I think those are much more human-readable! Great job!!!!

**Comment by sevein** [comment]
The sooner we merge this the better because it's going to affect translators.

**Comment by sevein** [comment]
Actually... ignore what I've just said! Translations of workflow messages aren't included in this release! :sweat_smile:

**Comment by joel-simpson** [comment]
I tested this using latest version of qa/1.x  (my local docker compose installation updated just now). I can see sentence case for all of the various micoservice Jobs as noted above. Marking as verified. 
![screenshot from 2018-10-25 17-25-20](https://user-images.githubusercontent.com/17187309/47531330-4ed59f80-d87b-11e8-8282-e435ca8be7a3.png)
![screenshot from 2018-10-25 17-25-39](https://user-images.githubusercontent.com/17187309/47531337-51d09000-d87b-11e8-816c-5b76e80a1a3c.png)
