### ISSUE TITLE
Problem: AIC number added via form in Transfer tab does not get saved

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#311]
**Expected behaviour**
I should be able to add the AIC number using the metadata entry form in the UI at any time before `Microservice: Add final metadata`.

![37736908-6c969a14-2d0f-11e8-8189-caf771fdc0a7](https://user-images.githubusercontent.com/4612276/47873286-057ed600-ddce-11e8-9d79-f9b33de086b0.jpg)

**Current behaviour**
Entering the metadata while the transfer is on the Transfer tab creates a new metadata entry, as expected. However, if you then edit the form, the AIC number has disappeared. The AIC number doesn't make it to the AIP METS either. However, if you add the number once the transfer has reached the Ingest tab, it saves just fine.

**Steps to reproduce**
1. Create a new transfer
2. While the transfer is still being processed on the Transfer tab, click on the transfer's metadata icon and add an AIC number. Save the form. You should be taken to the metadata list, where the new metadata form you just created is listed.
3. Click on edit to edit the metadata that you just created. The AIC number field will be blank.
4. Continue processing the transfer and make an AIP. The AIC number will not appear in the METS file either.

**Your environment (version of Archivematica, OS version, etc)**
Tested on 1.7 and 1.8

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
I investigated this today. The two "add metadata" views ([one from Transfer](https://github.com/artefactual/archivematica/blob/e240825332b76f3cc50b66646921fd9b1ab84d4b/src/dashboard/src/components/ingest/views.py#L187) and [one from Ingest](https://github.com/artefactual/archivematica/blob/e240825332b76f3cc50b66646921fd9b1ab84d4b/src/dashboard/src/components/ingest/views.py#L187)) share the [same model form](https://github.com/artefactual/archivematica/blob/e240825332b76f3cc50b66646921fd9b1ab84d4b/src/dashboard/src/components/ingest/forms.py#L23). However they process the POST request differently.

The Ingest view saves the Dublin Core information through the model form, while the Transfer view [goes through each field individually](https://github.com/artefactual/archivematica/blob/e240825332b76f3cc50b66646921fd9b1ab84d4b/src/dashboard/src/components/transfer/views.py#L213-L215). I couldn't find any reason why this is necessary, but this list doesn't include the `is_part_of` (Part of AIC) field and that's why even if it's being rendered as a form field is not being processed to be saved.

I'd propose to remove this list of fields and individual iteration and just pass the existing Dublin Core information to the model form to save it in the Transfer view (just like the Ingest view does).

**Comment by sevein** [comment]
> I'd propose to remove this list of fields and individual iteration and just pass the existing Dublin Core information to the model form to save it in the Transfer view (just like the Ingest view does).

That makes a lot of sense, @replaceafill!
It'd be nice to see some tests too :)

**Comment by sallain** [comment]
The AIC number now persists in the form, which is great! However, it still doesn't make it into the METS file :(

**Comment by sallain** [comment]
Today I noticed that if I add the AIC number while on the Transfer tab, then I go to check it on the Ingest tab, the AIC number has disappeared. If I add data to any other field, though, it persists.

**Comment by replaceafill** [comment]
@sallain This has been fixed in https://github.com/artefactual/archivematica/commit/08187324c85c03aac752ccc3ba417253951b3099

**Comment by sallain** [comment]
This now works perfectly. Thank you so much @replaceafill!!!
