### ISSUE TITLE
Problem: The documentation in Fixity needs to be refreshed

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#317]
**Version of the documentation**

Current [README.md]( https://github.com/artefactual/fixity/blob/3e8abaf9532b4d89c0b0c8284890f30615255d27/README.md)

**Description of the issue**

There are three main issues I can see reading through the documents:

* The mechanism employed by the tool could be made clearer, alongside a sample API call using `curl` or `httpie`. This takes on more importance where the tool could be compared to similarly named industry tools where the mechanism might be quite different.  
* We can include examples of how failures manifest themselves, e.g. where an oxum fails, or a checksum on a particular file is changed.
* We can include the table in the storage service where the data is written to.
* Copyright dates need to be updated, 2014-2018

**Places to update**

* [x] [Fixity Repository](https://github.com/artefactual/fixity/pull/18)
* [x] [Archivematica FAQ](https://github.com/artefactual/archivematica-docs/pull/272)
* [x] [Storage Service Docs](https://github.com/artefactual/archivematica-storage-service-docs/pull/22)

**Comment by sallain** [comment]
Since Fixity is a separate application that doesn't need to be used in conjunction with the Storage Service (I think...), I'm inclined to say that the Fixity documentation belongs in the README (or somewhere else). The Storage Service docs can just point out to the Fixity README, similar to the [integration pages](https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation-setup/integrations/integrations/#integrations) in the Archivematica docs.

Maybe @sevein and anyone else who regularly uses Fixity has an opinion?

**Comment by ross-spencer** [comment]
**NB** To complete this work, changes may still need to be made to the Storage Service Docs to point out to the refreshed Fixity README. Additionally, we might clarify in the Storage Service docs, that fixity is also possible via the [check_fixity](https://wiki.archivematica.org/Storage_Service_API#Check_fixity) endpoint.

**Comment by sallain** [comment]
@ross-spencer Do your two Storage Service PRs resolve this issue?

**Comment by ross-spencer** [comment]
Hi @sallain I had forgotten about this ticket. But yep, I'd say, PR #22 for the Storage Service rounds out this task.
