### ISSUE TITLE
Problem: manually normalized preservation derivatives cannot be validated

### ISSUE THREAD

**Issue by currmie** [archivematica/Issues#331]
**Expected behaviour**
Manual normalization workflow maintains a one-to-one relationship between the transfer and the SIP, and should continue to process successfully according to instructions in the User manual

**Current behaviour**
In manual normalization workflow, SIP fails during jobs `Identify file format` and `Validate preservation derivatives`. Error returned: "MultipleObjectsReturned: get() returned more than one Derivation".

**Steps to reproduce**
1. In archivematica-sampledata > TestTransfers, run a transfer with the `manualNormalization (40 objects)` dataset. 
2. Continue processing as you would a regular SIP.
3. In the Ingest tab, at the normalization microservice, choose `Normalize for preservation and access` for this particular dataset.

**Your environment (version of Archivematica, OS version, etc)**
am18bionic.qa.archivematica.org (@peterVG encountered during QA)
am18xenial.qa.archivematica.org (@currmie encountered during QA)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @peterVG, @currmie, can you run this transfer again and confirm that `normalize manually` is being selected? For the validation error here, I can only recreate it if I choose `normalize for preservation and access` which makes sense because we would be inadvertently creating duplicates (or at least putting duplicate entries into the DB) (we could be more graceful about this). 

The `identify file format error` is perhaps a little more obvious in this scenario because the normalization microservice group performs a lot of tasks but I believe this is expected behavior from Siegfried. It can't identify these BMP files - this is the result I see when running this standalone:

```
filename : 'image_2.bmp'
filesize : 2897918
modified : 2018-08-09T16:42:07-05:00
errors   : 
matches  :
  - ns      : 'pronom'
    id      : 'UNKNOWN'
    format  : 
    version : 
    mime    : 
    basis   : 
```

You should see the same error in Transfer for the same files.

If I run the ManualNormalization (40 objects) set first, in a fresh install, I do get an error in `Move access files to DIP`, and I can confirm this on 1.7 (screenshot from the Sandbox):

![image](https://user-images.githubusercontent.com/1880412/48459725-0251f580-e791-11e8-9c7b-93d3f710252f.png)

![image](https://user-images.githubusercontent.com/1880412/48459744-1dbd0080-e791-11e8-822e-b561802ceb29.png)

I should confirm my setup with yours to ensure that i'm not missing something trying to recreate the issue. All being equal then at least this doesn't look like a regression but let's see.

**Comment by currmie** [comment]
Hi @ross-spencer , I re-ran the transfer and confirmed that `normalize manually` was selected. I'm only seeing the `identify file format error` now. I had a feeling this was one of those transfers in TestTransfers that was meant to fail. :)

**Comment by sromkey** [comment]
This is a weird Archivematica-ism, but if you're doing the manual normalization workflow with a pre-structured transfer you're actually supposed to select "Normalize for Preservation and Access" or whatever is appropriate, rather than "Manual normalization"- see option 1 here: https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/ingest/manual-normalization/#manual-norm  So what Ross is describing does reproduce the error, but it shouldn't. You should be allowed to have a mix of manually normalized and non-manually normalized objects- maybe you have preservation derivatives for a,b, and c but not d, e, or f. Archivematica should first check if there are manually normalized versions, then move on to normalizing if needed. Hope that makes sense.

**Comment by ross-spencer** [comment]
I placed some extra logging into the [script](https://github.com/artefactual/archivematica/blob/707e9332f0bebf4c32def012e30752314a207d48/src/MCPClient/lib/clientScripts/validate_file.py#L206-L215) to try and chase this down this morning:

```
    def _file_is_preservation_derivative(self):
        """Returns ``True`` if the file with UUID ``self.file_uuid`` is a
        preservation derivative.
        """
        try:
            Derivation.objects.get(derived_file__uuid=self.file_uuid,
                                   event__event_type='normalization')
            return True
        except Derivation.DoesNotExist:
            return False
        except Derivation.MultipleObjectsReturned:
            logger.error("Multiple objects for UUID: %s", self.file_uuid)
            derivatives = Derivation.objects.filter(
                             derived_file__uuid=self.file_uuid,
                             event__event_type='normalization')
            for d_ in derivatives:
                logger.error("Here: %s", d_)
            return False
```

And we see this:
```
validatefile_v1.0: ERROR     2018-11-14 13:37:41,444  archivematica.mcp.client.validateFile._file_is_preservation_derivative:220  Multiple objects for UUID: a93ea6b7-036d-4a3b-af0b-3c8e9eb13f18
validatefile_v1.0: ERROR     2018-11-14 13:37:41,445  archivematica.mcp.client.validateFile._file_is_preservation_derivative:225  Here: File a93ea6b7-036d-4a3b-af0b-3c8e9eb13f18:%transferDirectory%objects/manualNormalization/preservation/image_8.png now at %SIPDirectory%objects/manualNormalization/preservation/image_8.png derived from File c019a42e-1863-4227-b12c-7d29822f6563:%transferDirectory%objects/image_8.gif now at %SIPDirectory%objects/image_8.gif in normalization event on File c019a42e-1863-4227-b12c-7d29822f6563:%transferDirectory%objects/image_8.gif now at %SIPDirectory%objects/image_8.gif (manual normalization)
validatefile_v1.0: ERROR     2018-11-14 13:37:41,453  archivematica.mcp.client.validateFile._file_is_preservation_derivative:225  Here: File a93ea6b7-036d-4a3b-af0b-3c8e9eb13f18:%transferDirectory%objects/manualNormalization/preservation/image_8.png now at %SIPDirectory%objects/manualNormalization/preservation/image_8.png derived from File ac9038cc-77dc-4011-b4f2-ed5e9cf7a79e:%transferDirectory%objects/image_8.bmp now at %SIPDirectory%objects/image_8.bmp in normalization event on File ac9038cc-77dc-4011-b4f2-ed5e9cf7a79e:%transferDirectory%objects/image_8.bmp now at %SIPDirectory%objects/image_8.bmp (manual normalization)
```
I also noticed a typo that needs fixing here: https://github.com/artefactual/archivematica/blob/707e9332f0bebf4c32def012e30752314a207d48/src/dashboard/src/main/models.py#L265

I am not clear on why this is happening now in `1.8` and it didn't happen in `1.7` but hopefully this helps someone else in the meantime.

**Comment by currmie** [comment]
Ah, makes sense @sromkey . I've updated 'Steps to reproduce' for this issue.

**Comment by jraddaoui** [comment]
Reproduced the issue using the Docker Compose environment.

That transfer has two original files with the same filename and different extensions:
https://github.com/artefactual/archivematica-sampledata/tree/master/TestTransfers/manualNormalization

And two preservation derivates:
https://github.com/artefactual/archivematica-sampledata/tree/master/TestTransfers/manualNormalization/manualNormalization/preservation

Related in the `normalization.csv` file:
https://github.com/artefactual/archivematica-sampledata/blob/master/TestTransfers/manualNormalization/manualNormalization/normalization.csv

The capitalization issues in the filenames are mentioned in the test cases:
https://github.com/artefactual/archivematica-sampledata/blob/master/TestTransfers/manualNormalization/testcase_descriptions.txt

Somehow, only one derivate is being associated in the database with the two originals:
![derivations](https://user-images.githubusercontent.com/637040/48567815-4b738800-e8fe-11e8-9901-dcd229b4d683.png)

Causing the `MultipleObjectsReturned` in:
https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/validate_file.py#L211-L212

I'll keep digging.

**Comment by jraddaoui** [comment]
Hi @currmie, @sromkey and @ross-spencer,

Doing a case insensitive comparison in [here](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/normalize.py#L105) solves the issue while validating the preservation deritaves, but it doesn't solve the issue while moving the access files to the DIP, which looks to be a similar issue caused by the capitalization in the CSV file. So I wonder, **how far do we want to go to make this process really case insensitive?** It may be a few places more where similar changes could be needed. I thought I should ask before putting more hours into this because, **if we fix the capitalization issues in the CSV file, everything works.**

**Comment by ross-spencer** [comment]
Hmm... 

Good research @jraddaoui. From an OS perspective, upper- and lower- case values are allowed for filenames and so `aFile.txt` and `afile.txt` won't conflict with each other. If a user hasn't capitalized the CSV properly, then perhaps it is just a user error? But what should happen with the duplicated normalized file? Can we just ignore and remove it from the package? (or fail and warn the user as an alternative?)

**Comment by jraddaoui** [comment]
Thanks @ross-spencer!

What duplicated are you refering? I have not checked if there are duplicated derivates after the fix. But, without the capitalization issues, a match should be found in the CSV file for the dirivate and linked to the original without creating a new one.

@currmie, @sromkey, do you know if this test case is there for a good reason? As Ross says, different files may exist with capitalization differences in the file system so, unless there is a good reason, we probably don't want to make the match case insensitive.

**Comment by currmie** [comment]
Hi @jraddaoui , it seems like this test case is a good one for institutions that have already accumulated a mixture of born-digital files and pre-processed/pre-digitized files, and they want to run transfers containing a mix of manually normalized and non-manually normalized objects to deposit and store for a later date. There is another test case in the TestTransfers directory with case-variation in the name (_ManualNormalization_), but it is associated with a more simplified workflow. The _manualNormalization_ test case extends the _ManualNormalization_ workflow with a pre-structured transfer. I can't really speak to how many clients currently use this workflow (maybe @sromkey knows), but it's an interesting test case to demonstrate the utility of normalization.csv for those clients who have already invested time and money on digitizing analogue and/or paper records prior to catching Archivematica fever!

**Comment by currmie** [comment]
@jraddaoui - one more thing, the print shops that do mass digitization of analogue records often provide archival institutions with files that have generic, default filenames like image_001, image_002, image_003 etc. That could be another reason not to make the match case insensitive.

**Comment by jraddaoui** [comment]
Thanks @currmie!

To be clear, I'm not taking about removing the functionallity nor the test transfer, just the capitalization differences bettwen the real files and the filenames in the CSV.

**Comment by currmie** [comment]
> Thanks @currmie!
> 
> To be clear, I'm not taking about removing the functionallity nor the test transfer, just the capitalization differences bettwen the real files and the filenames in the CSV.

For sure @jraddaoui ! I like the idea of changing the filenames in the CSV to make it work!

**Comment by jraddaoui** [comment]
Removing the capitalization issues in the `normalization.csv` file at the sample data repository fixed the issues in the "Identify file format" and "Move access files to DIP" jobs. However, a new issue araised in the "Verify AIP" job, trying to check the checksum of the deleted `normalization.csv` file, which required a small fix in the Archivematica code.

**Comment by jraddaoui** [comment]
Added `Severity: high` as requested to discuss if this should get added to the 1.9 milestone. The fix in the AM code still needs code review, but it's not a big change.

**Comment by sevein** [comment]
@jraddaoui, milestone 1.9 added!

**Comment by jraddaoui** [comment]
Hi @sevein (@ross-spencer and @ablwr), there is already a minor PR pending code review in https://github.com/artefactual/archivematica/pull/1309.
