### ISSUE TITLE
Problem: Restructure DIP for CONTENTdm fails

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#333]
**Expected behaviour**

When a DIP has been created and the transfer included a metadata.csv file, it should be possible to create a DIP for CONTENTdm.

**Current behaviour**

The process fails at Job: Restructure DIP for CONTENTdm upload with this failure:

```
'NoneType' object has no attribute 'items'Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/restructure_dip_for_content_dm_upload.py", line 257, in call
    job.set_status(generate_project_client_package(job, os.path.join(args.dipDir, 'objects'), itemCountType, archivematica_structmap, dmdsecs, args.uuid))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/restructure_dip_for_content_dm_upload.py", line 177, in generate_project_client_package
    for header, value in metadata.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Steps to reproduce**

- start a transfer which contains a metadata.csv
- at normalization, normalize for access to create a DIP
- at DIP upload choose CONTENTdm

**Your environment (version of Archivematica, OS version, etc)**

centos qa/1.x (pre 1.8 release).

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
A further note, the DIP still creates, and a txt file is created, but it's blank. (The CONTENTdm workflow creates a simple.txt or complex.txt file which is used in the CONTENTdm upload process, manually by the user).

**Comment by sromkey** [comment]
This is working, mostly! 

@jraddaoui this is a little nitpicky, but whether or not the transfer is multi-level (e.g. has directories for the objects) the text file is still called "compound.txt." It should be simple.txt for non-multi-level (like this sample transfer: https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/CSVmetadata ) and compound.txt for multi-level: https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/CSVmultiLevel 

I can file another issue if you don't see a relatively straightforward fix for that.

**Comment by jraddaoui** [comment]
Hi @sromkey,

A quick fix is possible but it may be better to do some analysis to see if a more complicated one is needed. I'll try to explain the issue ...

[This](https://gist.github.com/jraddaoui/7b201e9b5cd7c67e686e8b2315e4fa9c) is the physical `structMap` from the "simple" transfer and [this one](https://gist.github.com/jraddaoui/8bb6d4f2c5f0f3f03dd0e7897299b63a) is from the "compound" transfer in the previous update. To determine if the text file is called `simple.txt` or `compound.txt`, [we look for `divs` in the structMap](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/restructure_dip_for_content_dm_upload.py#L76-L95) with a related DMD section and directory type. If there is any result the file will be called `compound.txt` and, in both cases, the `div` element for the entire AIP matches that criteria.

As a quick fix, we could ignore the `div` element for the AIP, by searching over the descendants of that `div` instead of over the descendants of the `structMap`. But I wonder if it will be better in the long term to use a different type for that element, for example `TYPE="AIP"`. I'm not sure if that's a better fix for this issue and it may bring issues in other tools (like the hierarchical DIP upload in AtoM). But I thought I should ask before making the quick fix.

Please, let me know what do you think.

**Comment by sromkey** [comment]
Hey @jraddaoui - thanks, that helps a lot. I think this sounds like a different issue that we should tackle separately... I'll file one and move this one to verified. Thank you!
