### ISSUE TITLE
Problem: AtoM DIP upload link in Access tab is wrong

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#411]
This is an old, old, old known issue. Filing it here so that it has a little more visibility, in the hopes that maybe someday it can get fixed :)

Old issue: https://projects.artefactual.com/issues/7590

**Expected behaviour**
After uploading a DIP to AtoM, the Access tab is populated with information about the DIP upload. There is a link provided which should take users directly to the AtoM target URL.

**Current behaviour**
The target URL is wrong - it points to the SWORD deposit folder rather than the target. For example, if you upload a DIP to `http://atomdemo.artefactual.com/series-a-3`, the URL in the Access tab shows `http://atomdemo.artefactual.com/sword/deposit/series-a-3`.

![image](https://user-images.githubusercontent.com/4612276/50800265-61fde600-1294-11e9-96d9-974d24b4d341.png)

**Steps to reproduce**
Upload a DIP to AtoM then click on the Access tab.

**Your environment (version of Archivematica, OS version, etc)**
All

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
The same URL used to send the DIP is saved as the resource URL in [here](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/upload_qubit.py#L226). It looks like we're trying to update that resource URL with the location header from the AtoM response in [here](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/upload_qubit.py#L254-L259). However, we're use the same target URL in there instead of the location header, which seems to be a bug. Nevertheless, the location header returned from AtoM at the moment is not the full one and just a relative URL (`index.php/target-slug`).

Considering that the upload has succeeded and that the AtoM slug is not going to change in the process, I think we could use the existing base URL and target slug to build the resource URL (without `/sword/deposit`).

**Comment by jraddaoui** [comment]
This should be fixed for new uploaded DIPs but not for existing ones.

**Comment by sallain** [comment]
Omg! @jraddaoui my hero!!!!

**Comment by sallain** [comment]
@jraddaoui this is fixed! I was a tiny bit concerned that the first couple of uploads I created had two slashes in the path, but it turns out that there was a trailing slash in the upload URL in the AtoM/Binder config page. I think we could amend the helptext there to tell folks to leave off the trailing slash but for now I think it can just be a note in the docs.
