### ISSUE TITLE
Problem: Storage Service docs has no README.md or contributing.md

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#429]
**Version of the documentation**
All

**Page (and section, if applicable) where the issue occurs**
Github repo

**Description of the issue**
There is no README or CONTRIBUTING file in the repo so if folks want to make suggestions/changes they may not know where to start. 

**Suggested fix**
With a couple of small changes the README from the am-docs would probably be fine, and it can also point to the am-docs wiki for contributing information.

**Comment by ablwr** [comment]
Related issue in the automation-tools repo: https://github.com/artefactual/automation-tools/issues/90

**Comment by ablwr** [comment]
Hey @sromkey @ross-spencer! Ross, I think your idea and sample demo are both great, and I see you've made an issue to address this larger issue. Since this issue is more focused, I sent a PR to the storage-service-docs repo to add a README that mirrors the AM-docs repo. AM-docs also does not include a contributing.md. I figured this could resolve this issue, and then we can focus on the larger issue in your (@ross-spencer's) Issue #654.

**Comment by ross-spencer** [comment]
The concept sounds good to me @ablwr, @sromkey's a good person for final sign-off. While she's off the next day, I've left a comment on the CR if it helps push it forward a little in the short-term. (You hadn't requested review, so apologies if I mis-read and it wasn't quite ready).
