### ISSUE TITLE
Problem: some AMAUAT tests are not passing consistently

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#438]
In [AMAUAT](https://github.com/artefactual-labs/archivematica-acceptance-tests), a number of tests are unreliably passing, i.e. sometimes we experience errors in different parts of the code and different error messages. These are the tags affected:

- `@pid-binding` (needs to be confirmed)
- `@ipc`
- `@aip-encrypt-mirror`
- `@aip-encrypt`

Usually, they pass after a few attempts.
These tests are excluded from CI because of this issue.
Related:
- https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/132
- https://github.com/artefactual-labs/archivematica-acceptance-tests/issues/124
- https://github.com/artefactual-labs/archivematica-acceptance-tests/issues/125

**Your environment (version of Archivematica, OS version, etc)**
This started happening in AM18. Possibly related to the update to WebDriver.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
I investigated this issue using the `am/compose` environment:

* The `@ipc` and `@premis-events` tags seem to pass consistently in the `am/compose` environment if the `archivematica-acceptance-tests` service is modified to [have a shared memory of at least 2 GB](https://github.com/mozilla/geckodriver/issues/285) (by setting `shm_size: 2g` in the `docker-compose.acceptance-tests.yml` file). Its [default value is only 64MB](https://docs.docker.com/compose/compose-file/compose-file-v2/) and it seems to be the cause of some `Browsing context has been discarded` and `Failed to decode response from marionette` errors.

* `@pid-binding` currently fails because the `am/compose` environment sets the `nodice` string as the value of the [`Web service endpoint`](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/a161832be8bbdd663983978b0fe0c6802fb52ed4/features/steps/pid_binding_steps.py#L36-L37) and [` Resolver URL `](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/a161832be8bbdd663983978b0fe0c6802fb52ed4/features/steps/pid_binding_steps.py#L40-L41) settings in the `/administration/handle/` form. However both form fields are `django.forms.URLField` and rendered as `<input type="url" />` which prevents the form from being submitted if non-URL values are entered (like the `nodice` string). If URLs are passed when calling `behave` (for example using `-D pid_web_service_endpoint=http://example.com`) the test fails because it cannot set PIDs and PURLs from a bogus endpoint (like `http://example.com`) or because issue https://github.com/archivematica/Issues/issues/154. I wasn't able to test this with valid Handle.net credentials.

* `@aip-encrypt` currently fails because generating a [new GPG key](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/a161832be8bbdd663983978b0fe0c6802fb52ed4/amuser/am_browser_ss_ability.py#L374) in the `am/compose` environment takes several minutes, making the selector that looks for the "Saved" message to time out. Passing a `wait_factor` of `100000` didn't seem to help either. I didn't test this in a VM where `rng-tools` makes the GPG key generation process fast.

**Comment by sevein** [comment]
@replaceafill thanks for doing, this is super useful! :clap: :clap

A few comments,

> The `@ipc` and `@premis-events` tags seem to pass consistently in the `am/compose` environment if the `archivematica-acceptance-tests` service is modified to [have a shared memory of at least 2 GB](https://github.com/mozilla/geckodriver/issues/285) (by setting `shm_size: 2g` in the `docker-compose.acceptance-tests.yml` file). Its [default value is only 64MB](https://docs.docker.com/compose/compose-file/compose-file-v2/) and it seems to be the cause of some `Browsing context has been discarded` and `Failed to decode response from marionette` errors.

If we need that workaround then I'd suggest to submit a PR in am.git. I remember having to do that at some point but it stopped being a problem in recent versions of Firefox. But I can still from the link you've shared that many users are still affected and it's still described in places like [docker-selenium](https://github.com/SeleniumHQ/docker-selenium#running-the-images).

But this issue may be about a different problem. Once you have a stable setup (shm workaround, pid creds, rng daemon runnin...), it'd be good to check again that you don't have more interment failures when running [all the tags](https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/132#issue-223371938) in batch. E.g., we experienced this issue in our CI servers where Archivematica isn't being deployed with containers. You could ask @scollazo to point you to some of the builds and errors that he has recorded in Jenkins.

> `@pid-binding` currently fails because the `am/compose` environment sets the `nodice` string as the value of the [`Web service endpoint`](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/a161832be8bbdd663983978b0fe0c6802fb52ed4/features/steps/pid_binding_steps.py#L36-L37) and [`Resolver URL`](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/a161832be8bbdd663983978b0fe0c6802fb52ed4/features/steps/pid_binding_steps.py#L40-L41) settings in the `/administration/handle/` form. However both form fields are `django.forms.URLField` and rendered as `<input type="url" />` which prevents the form from being submitted if non-URL values are entered (like the `nodice` string). If URLs are passed when calling `behave` (for example using `-D pid_web_service_endpoint=http://example.com`) the test fails because it cannot set PIDs and PURLs from a bogus endpoint (like `http://example.com`) or because issue #154. I wasn't able to test this with valid Handle.net credentials.

I'll send you some creds that were working for me.

> `@aip-encrypt` currently fails because generating a [new GPG key](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/a161832be8bbdd663983978b0fe0c6802fb52ed4/amuser/am_browser_ss_ability.py#L374) in the `am/compose` environment takes several minutes, making the selector that looks for the "Saved" message to time out. Passing a `wait_factor` of `100000` didn't seem to help either. I didn't test this in a VM where `rng-tools` makes the GPG key generation process fast.

This can be fixed just by installing rng-tools on the host.

**Comment by scollazo** [comment]
We are currently running 14 tests, using 6 tags (uuids-dirs, mo-aip-reingest, icc, tpc, picc and premis-events) in 3 environments: Ubuntu 18.04, Ubuntu 16.04 and Centos 7, installed using ansible from our Jenkins server.

Succesful build logs for Ubuntu 18.04 and Centos can be found at:
http://jenkins-ci.archivematica.org/job/deploy-pub/job/QA/job/Ubuntu-18.04-QA/184/testReport/
http://jenkins-ci.archivematica.org/job/deploy-pub/job/QA/job/Centos-7-QA/117/testReport/

The premis-events tag fails in Ubuntu 16.04:
http://jenkins-ci.archivematica.org/job/deploy-pub/job/QA/job/Ubuntu-16.04-QA/113/testReport/
http://jenkins-ci.archivematica.org/job/deploy-pub/job/QA/job/Ubuntu-16.04-QA/113/testReport/junit/core.premis-events/history/
