### ISSUE TITLE
Problem: don't know all the backlog information that is stored during Transfer

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#441]
This information is needed to ensure it is all moved to a Transfer METS file, as per issue #442,  that will contain all the information required to restore backlog files from transfer storage (as per issue #391). 

Will need to go through all the current Transfer microservices and note what data is being stored in the MySQL database, ElasticSearch index, (and elsewhere?) 

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
I've moved this to blocked (aka on hold) since we've started working on other issues like creating the bagit or the new transfer storage location in SS. A lot of the work that relates to this issue was reported here: https://gist.github.com/sevein/0317c3095b5c9d571fe502780fa5548a. See also our Waffle board for more details: https://waffle.io/artefactual/archivematica?label=SFU.

**Comment by sromkey** [comment]
This analysis was completed during the project- I'm going to mark it done.
