### ISSUE TITLE
Problem: it is difficult to develop front-end applications in the Dashboard

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#507]
**Please describe the problem you'd like to be solved.**

Developing new Dashboard front-end applications or modifying existing ones (e.g. Appraisal tab) is difficult because we have outdated library dependencies, outdated testing integration, and inconsistent Javascript implementation.

**Describe the solution you'd like to see implemented.**

- [x] Bring dependencies up to date 
- [x] Integrate with the standard development environment using AM.git
- [x] Standardize how Angular javascript is used across the dashboard. 
- [x] Integrate with existing continuous integration system (Travis & Jenkins)
- [ ] If we break AMUAT tests, new issues should be filed

**Describe alternatives you've considered.**

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
>  Integrate with existing continuous integration system (Travis & Jenkins)

I think it's relatively easy to have Firefox/Chrome installed in Travis via `addons`.
Something that you could try is to set up a new job that runs in parallel. Here's a pretty good example: https://github.com/linkerd/linkerd2/blob/master/.travis.yml. The base env is trusty with sudo disabled because that's faster (runs in containers instead of VMs), then each job defines a different `language`. E.g. we could have a new job based on `node_js` and with the addons installed, e.g. Firefox, Chrome or both.

**Comment by replaceafill** [comment]
Really cool and interesting. Thanks for explaining it @sevein! I was initially overwhelmed by "it's relatively easy" but you were right, it didn't take too long :)

I just addressed this in https://github.com/artefactual/archivematica/pull/1364/commits/33a5228b0112694fdd805e8e0b40100e714a7065

**Comment by sallain** [comment]
@peterVG not sure if there is actual testing to be done here?
