### ISSUE TITLE
Problem: It's unclear how well the Appraisal Backlog tab works with more than 10,000 objects

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#549]
**Expected behaviour**
Switching between folders and selecting objects should happen without much delay.

**Current behaviour**

This hasn't been fully tested so this issue is meant to conduct some performance testing on the Appraisal backlog tab.

**Steps to reproduce**

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
I tested the latest Appraisal tab changes (https://github.com/artefactual/archivematica/commit/3ec2fde5a51317b87f69684b5272e9c95e1117c1) in my am.git environment using Chrome (and its developer tools), extracting the [TestTransfers/10,000 files 10,000 directories.tar.7z](https://github.com/artefactual/archivematica-sampledata/blob/master/TestTransfers/10%2C000%20files%2010%2C000%20directories.tar.7z) file and sending a couple of transfers to the backlog (performing file format identification and examining contents in both) which results in 20k files per transfer:

![Captura de pantalla de 2019-03-26 11-49-48](https://user-images.githubusercontent.com/560781/55020951-84fb8480-4fbd-11e9-9f3b-6805b1b64156.png)

### Size of the JSON payload

To get the JSON needed for the panes we need to call the `/ingest/appraisal_list/` view. In this context this would take 9-10 seconds, transferring 14 MB. Marking the *Show metadata & logs directories?* checkbox or not doesn't seem to have a considerable impact in time or transfer size.

I think a quick visual improvement worth discussing would be adding a spinner to the Backlog pane once the Search button is pressed.

A more drastic change could be done to reduce the size of the payload by splitting and transferring only what each pane needs. By default only the Backlog and Analysis panes are open. And changes in the search results only affect the former. Some information like file format and bulk report data is only needed after the user has selected a file and clicked on the Analysis pane buttons.

### ElasticSearch result limit

In the following search screenshot the *Show metadata & logs directories?* checkbox was marked:

![Captura de pantalla de 2019-03-26 12-13-52](https://user-images.githubusercontent.com/560781/55022864-1e786580-4fc1-11e9-8ba5-24fa24c19f63.png)

Notice the uneven top level log/metadata files. There should be 4 of them (bag-info, bagit, manifest, tagmanifest).

I think the reason is that [ElasticSearch queries return up to 10k results](https://github.com/artefactual/archivematica/blob/qa/1.x/src/archivematicaCommon/lib/elasticSearchFunctions.py#L80-L82).

### JS code performance

Selecting all the files in one of these transfers (without expanding it) takes around 7 seconds:

![Captura de pantalla de 2019-03-26 12-48-40](https://user-images.githubusercontent.com/560781/55025007-a3657e00-4fc5-11e9-8eb8-c2e55faeafbc.png)

I'm not a frontend expert but one thing got my attention that may be worth reviewing: the TreeController [recursively calls the SelectedFiles service](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/frontend/app/tree/tree.controller.js#L33-L41) so other panes (like File list) have access to the selected nodes. But before adding each node, the [SelectedFiles service tries to remove the node first](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/frontend/app/services/selected.service.js#L12-L16) which makes it traverse the selected nodes list entirely.

Maybe adding a mapping for membership testing before attempting to remove the node could improve performance.

Enabling the File list pane with a whole transfer selected takes around 10 seconds where most of the scripting work is related to Angular [applying filters](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/frontend/app/front_page/appraisal_tab.html#L167) and [calculating url segments] (https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/frontend/app/front_page/appraisal_tab.html#L179).

Two things currently break:

* Attempting to tag a whole transfer crashes the browser. After reloading the page the tags have been applied only to some of the files
* Attempting to create a SIP from a tag. This hits the database too quickly producing `OperationalError: (1040, 'Too many connections')` errors.

**Comment by sromkey** [comment]
Putting this back in review for release management purposes

**Comment by sallain** [comment]
Closing - we've tested with ~5,000 objects, and things worked fine.
