### ISSUE TITLE
Problem: Information Object not created in AtoM when a SIP is created from a backlogged transfer

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#570]
**Expected behaviour**
AtoM should create an information object out of the Dublin Core metadata entered via the GUI

**Current behaviour**
No Information Object is created and none of the DC metadata appear in AtoM. Maybe this is related to https://github.com/archivematica/Issues/issues/546 ? 

**Steps to reproduce**
-Create a transfer and place it in transfer backlog
-In the Appraisal Tab, retrieve the transfer and create a SIP from it
-Enter DC metadata via the GUI
-Create a DIP and upload it to AtoM

**Your environment (version of Archivematica, OS version, etc)**
centos and xenial 1.9 QA instances

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
I was intrigued by this so I did a little bit of investigation, and discovered some interesting things.

1. Metadata added through the GUI form in the Transfer tab is not being retained if the package is placed in the backlog (the metadata is retained if backlog is **not** used.)

2. Metadata added through the GUI form in either the Transfer or Ingest tab DOES make it to AtoM, as long as the transfer isn't sent to backlog.

So the metadata upload works, but metadata is being stripped when a package is sent to backlog.

@evelynPM I'd suggest just amending the description of this ticket so that it reflects that this is a problem with the backlog move, rather than the AtoM upload!

**Comment by sromkey** [comment]
This would require some analysis to decide how it should work. You could have two different packages in backlog, with two different sets of SIP-level metadata- if they are arranged into one SIP, which set of metadata should AtoM use?

**Comment by sallain** [comment]
@sromkey :bowing_woman:

**Comment by joel-simpson** [comment]
@sevein can you please look at this and size it for potential inclusion in 1.10?

**Comment by jraddaoui** [comment]
Probably the PREMIS 3 upgrade requires changes in AtoM's METS parsing process ...

https://github.com/artefactual/atom/blob/qa/2.6.x/lib/QubitMetsParser.class.php#L31

**Comment by cole** [comment]
Possibly related to https://github.com/archivematica/Issues/issues/586.

**Comment by evelynPM** [comment]
Filed issue in AtoM project: https://projects.artefactual.com/issues/13067.

**Comment by sromkey** [comment]
Testing found that the METS being provided in the DIP doesn't have any problem, rather it's AtoM's interpretation of the METS- so closing this out since we can't solve from the Archivematica side of things.
