### ISSUE TITLE
Investigate possible ES mapping changes in qa/1.x branch

### ISSUE THREAD

**Issue by jraddaoui** [archivematica/Issues#619]
**Please describe the problem you'd like to be solved.**

We should investigate if the changes from https://github.com/artefactual/archivematica/pull/1365 and https://github.com/artefactual/archivematica/commit/7c5da722c761d42371ff7ae4b583071a9c2f6b6f are modifying the current indexes mapping and if there are existing queries that may be affected.

More information in https://github.com/archivematica/Issues/issues/608#issuecomment-477785211 and https://github.com/archivematica/Issues/issues/608#issuecomment-478664116.

**Describe the solution you'd like to see implemented.**

**Describe alternatives you've considered.**

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by hakamine** [comment]
Adding some explanation/background to make the impact of this issue clear:

- The PREMIS3/old AIP handling fixes ( https://github.com/archivematica/Issues/issues/24) initially broke the indexing of AIP files. File uuids weren't being correctly parsed from the METS file, and the `FILEUUID` field in the `aipfiles` index were being set as `''`. This caused internal server errors in the archivematica dashboard when searching for files in the Archival Storage tab.
- To fix this, some changes were made in the indexing related code. All these changes, together with the PREMIS3/old AIP handling fixes were merged as https://github.com/artefactual/archivematica/pull/1365. 
- One of the changes made in 1365 was to replace the library `xml.etree.ElementTree` with `lxml.etree` in `archivematicaCommon/elasticSearchFunctions` (https://github.com/artefactual/archivematica/commit/7c5da722c761d42371ff7ae4b583071a9c2f6b6f) (as `lxml.etree` is already used in most of the other parts of the archivematica codebase for xml processing, this seemed to be a positive change). However a side effect of this replacement was that the METS file is indexed differently in the `aips` index (this is because `ElementTree` replaces namespace names with its own prefixes (ns0,ns1, etc) while `lxml.etree` does not). This makes new aips indexes (created using the code that includes 1365) "incompatible" with the old indexes
- This problem can be fixed in different ways, for now probably the most straightforward way would be to try to fix the indexing of AIP files without replacing the `xml.etree.ElementTree` library in `archivematicaCommon/elasticSearchFunctions`

**Comment by evelynPM** [comment]
Fixed by https://github.com/artefactual/archivematica/pull/1408.

**Comment by evelynPM** [comment]
@hakamine do I need to test this to close the issue? If so, do you have any advice on how to do that?

**Comment by hakamine** [comment]
@evelynPM I believe this can just be closed (already tested for redmine issue 11227)

**Comment by scollazo** [comment]
I'm reopening this to confirm that no reindex will be need for 1.10

**Comment by jraddaoui** [comment]
Thanks for checking @scollazo!

The indexes settings and mappings are the same comparing `stable/1.9.x` with `qa/1.x`. However, we made a couple of changes in the indexing process. They are minor fixes related to how the Dublin Core metadata is indexed in the AIP files documents and they probably won't affect most of the AM instances.

Considering the complications we face to re-index in some of those instances, I'd suggest to only re-index minor instances with local storage. And, for the bigger/more complex instances, I'd wait to see if searching over the Dublin Core metadata becomes an issue after the upgrade and I'd only re-index if that's the case.

**Comment by sallain** [comment]
Test plan:

* Create a new 1.9 site
* Populate with some data (make sure it includes descriptive metadata)
* Upgrade to 1.10

This will let us know if sites need to be reindexed before upgrading.

**Comment by jraddaoui** [comment]
I found the two issues that change a little the Dublin Core metadata index process: #674 and #272. The latter is the most important one and I just realized it's from the 1.9 release. So, I think we can skip the re-index process in this upgrade.

**Comment by sallain** [comment]
This looks good! @scollazo created a 1.9 site which I populated with a variety of transfers, some of which included descriptive metadata. After upgrading to 1.10, the transfers all look good and I am still able to search for the AIPs/files by their descriptive metadata.
