### ISSUE TITLE
Problem: copy_from_arrange view fails when the dashboard and storage service are on different servers

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#671]
**Expected behaviour**

The `copy_from_arrange` view looks for paths in the right server.

**Current behaviour**

When the dashboard and storage service are run on different servers, this [Bag check](https://github.com/artefactual/archivematica/blob/df5aaed7dbf959665854fddc07a6b923fade9b1f/src/dashboard/src/components/filesystem_ajax/views.py#L555) is performed in the dashboard server which fails like this (custom debug call to get the error printed):

```
DEBUG     2019-04-25 22:49:10  archivematica.dashboard:views:_copy_from_arrange_to_completed_common:557:  ** ERROR** Expected bagit.txt does not exist: /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/pv-simple-4925a84a-da7e-4794-9530-8522ba453ed5/bagit.txt
```

**Steps to reproduce**

Set the dashboard and storage service in separate servers and try to create a SIP from the Arrangement pane of the Appraisal tab.

**Your environment (version of Archivematica, OS version, etc)**

http://am191bionic.qa.archivematica.org
http://ss191bionic.qa.archivematica.org:8000/

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Hi @replaceafill. I've logged in both VMs and it seems that they're not sharing `/var/archivematica/sharedDirectory`. Is that expected to work that way? I didn't think so.
In my development environment, AM and SS are virtually running on separate machines and appraisal works because both have access to the transfer backlog I believe.

**Comment by replaceafill** [comment]
Hello @sevein.

> Is that expected to work that way?

Sorry, I don't know how the VMs were set up. Maybe @mamedin or @scollazo can help us explaining that.

> In my development environment, AM and SS are virtually running on separate machines and appraisal works because both have access to the transfer backlog I believe.

Is your development environment docker-based? It works in my docker-based environment too, but I assumed it's because the paths to the host files are the same in both containers.

**Comment by sevein** [comment]
@replaceafill I'm going to review the config today with @mamedin. He's suggested to set up TB using the space using "Pipeline Local Filesystem". I'll report back soon.

**Comment by sevein** [comment]
https://github.com/artefactual/archivematica-storage-service/pull/451 fixes a problem in SS during unserialization that was preventing some errors from being reported properly. The underlying issue is being fixed in https://github.com/artefactual/archivematica/pull/1411. The latter needs some extra work in `filesystem_ajax.views.download_by_uuid` (see https://gist.github.com/sevein/d34dbbe98333c90ea3581263d72a0106 for more).

**Comment by hakamine** [comment]
I did a quick test on am191bionic.qa.archivematica.org (and ss191bionic.qa.archivematica.org) with the fix in artefactual/archivematica#1411 and was able to create a SIP from the Arrangement pane of the Appraisal tab (which was previously unable to do). Probably a more comprehensive testing needs to be done once the `download_by_uuid` fixes are completed.

**Comment by sallain** [comment]
@peterVG can you relabel as Done if you're confident that this is resolved?

**Comment by ablwr** [comment]
Working great!
