### ISSUE TITLE
Storage service packages tab timeout 

### ISSUE THREAD

**Issue by lwo** [archivematica/Issues#676]
**Expected behaviour**
https://github.com/archivematica/Issues
The storage service shows a paged view of the availabe packages (DIPs and AIPs) and their respective status.

**Current behaviour**
We have 169908 records in table locations_packages. NgInx times out waiting for the response.

**Steps to reproduce**
I suppose filling up a test storage database for table 'locations_packages' with about 200 000 dummy records will reproduce the result.

**Your environment (version of Archivematica, OS version, etc)**
Ubuntu 16.04, fork IISH:
https://github.com/IISH/archivematica-storage-service

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
Related to https://github.com/archivematica/Issues/issues/678

**Comment by replaceafill** [comment]
The problem here seems to be that the view is creating an HTML page with all the packages as rows in a table and **then** it uses jQuery's DataTables to make the pagination (Show X entries, Previous, Next, etc) work. A quick test showed that each table row can take around 1.7 kB. With 169908 records that'd be a 280-300 MB page to generate. Also, searching and sorting are currently only stripping the HTML tags from the table cells and using the remaining contents.

We plan to change the implementation of the table to use the ["server side rendering" options](http://legacy.datatables.net/examples/data_sources/server_side.html) where only small amounts of data are retrieved each time and searching and sorting can be more precise.

**Comment by sallain** [comment]
As the resolution for this issue will result in the Packages tab being refactored, this seems like a good opportunity to provide some general feedback that can be incorporated to tidy up the tab generally.

Here is an initial list of the columns, their purpose, whether or not they should be sortable, and some comments.

**UUID**
Purpose: UUID of the package
Sorting: No
Comments: It's possible that users might want to sort by UUID but I think it's much, much more likely that they would want to sort by package name (see comments under Current Location and Other Recommendations).

**Description**
Purpose: Not sure (always seems to be `None`)
Sorting: No
Comments: We should figure out if this column is ever populated. If not, it should be removed.

**Originating Pipeline**
Purpose: The name and UUID of the pipeline that generated the package
Sorting: Yes
Comments: Does it need to have the human-readable name as well as the UUID? I think it's likely that users with more than one pipeline give them unique human-readable names so that they can be differentiated, but not sure.

**Current Location**
Purpose: Path to the package (note: full path of the package, not just the path to the storage location)
Sorting: Yes
Comments: This column is the only one that shows the name of the package, so it's the only column that users can sort by to search by name. Below I have recommended that a _Package name_ column would be more useful.
Also I'm not sure how well this works if the path is not local.
Another thing to note is that clicking on the package path, which is a link, takes you to the info page for the package's location rather than an info page for the package itself, which is not particularly helpful.

**Size**
Purpose: Size of the package
Sorting: Yes
Comments: See #678 

**Type**
Purpose: Type of package (Transfer, AIP, DIP)
Sorting: Yes
Comments: None

**Replicas**
Purpose: Indicates if this package is a replicated package or not (i.e. is it a copy of another package that is in storage). I believe this displays `Yes` or `No`.
Sorting: Yes (could be helpful for doing a replication audit, maybe?)
Comments: I think Replicas / Is Replica Of is a little fuzzy, but I also don't see a quick fix that would make this better.

**Is Replica Of**
Purpose: UUID of the original package, if this package is a replication.
Sorting: Yes (could be helpful for doing a replication audit, maybe?)
Comments: See above under Replicas.

**Pointer File**
Purpose: Link to the pointer file
Sorting: No
Comments: Not sure how often this is used but I think it would the only place to get a link to the pointer file if you've deleted the pipeline, so it should stay. Could, perhaps, be moved under the Actions column.

**Status**
Purpose: Whether the package has been uploaded or deleted
Sorting: Yes
Comments: "Uploaded" is not super informative, especially when it's related to a Transfer-type package.

**Fixity Date**
Purpose: Date that Fixity was last run
Sorting: Yes (helpful for doing a fixity audit)
Comments: None

**Fixity Status**
Purpose: Status reported when Fixity was last run
Sorting: Yes (helpful for doing a fixity audit)
Comments: None

**Actions**
Purpose: Links to actions (Download, Re-ingest, Request deletion)
Sorting: No
Comments: None

**Other recommendations**
* Adding a "package name" column would make it easier to find packages in general
* If the package name column is added, change Current Location to list the location description (and UUID?) of the storage location, rather than the path to the package
 * Note: we can't just make this change independent of adding the package name column, as the current functionality of the Current Location column is the only way to sort by package name.
* Consider how much work it would take to add a package information page, similar to the AIP information page in the AM dashboard.

---

All of the above is just my opinion! Please feel free to comment, disagree, etc.

**Comment by sromkey** [comment]
Great summary @sallain ! 

I find it extremely unlikely that anyone would care to sort by UUID!

I can see value in have the UUID of the pipeline since some institutions might want to keep the pipeline names generic (e.g. "digitization") but replace the pipelines as time wears on.

Status is really really fuzzy and the whole concept of statuses/package states could use a separate analysis, IMO. I have an email thread about this from ages ago that I'll turn into something more useful/public.

Re the idea of a Package name column- it seems like location (which I suspect doesn't actually work if not local?) would be better linked to the SS location rather than an actual link to the disk (which is actually how the link works currently, but it looks like a link to the package). Open to other opinions on that.

**Comment by ablwr** [comment]
We have a lot of columns and it can make the package view not really fit on the screen due to some other formatting. So the less columns, the better, in my opinion -- or adjust the Bootstrap CSS so that the columns all fit on the page without a user having to scroll to the right.

I wonder if Replica/Is Replica Of can be consolidated into one column? Show UUID if is a replica, otherwise show nothing.

Thanks for this analysis @sallain!!

**Comment by ross-spencer** [comment]
**Date the package was added:** 

I notice there isn't a column for the date the package was added? And I also don't believe there there to be an order to the table rows? As a developer I am searching by date added. Searching by name is second to that.  

**Fixity:**

![image](https://user-images.githubusercontent.com/1880412/58614231-20f48580-82b8-11e9-9013-ce2a3af2dbaa.png)

As you can see it links out to its own separate report page. So a compression to date and a status could save space:  `{datetime} ✓` or `{datetime} ✗` (date and a tick and a cross with some color coding?) (but as Sara notes status is good to sort on, for fixity audit, and date is useful in its own right too because it's not an automatic process and folks need to know if fixity was two days ago or two years...) 

(A package summary page would be lovely @sallain!)

**Comment by sallain** [comment]
@ablwr Agreed on the replica columns. Basically, just keep the "Is Replica Of" column (maybe re-titled to just "Replica Of").

**Comment by sallain** [comment]
@ross-spencer Also agreed, a "Date stored" or whatever column would be a good addition. I like your suggestions about the Fixity columns too!

The Current Location column could probably be narrower to help with the width issue.

**Comment by sallain** [comment]
@lwo this is included in the 1.10 release candidate, if you would like to test!
