### ISSUE TITLE
Add gzip to AIP compression options

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#681]
**Please describe the problem you'd like to be solved.**
We would like to be able to generate gzipped AIPs in Archivematica

**Describe the solution you'd like to see implemented.**
To add gzip compression as an available option in the "Compression method" dropdown and include support for that method in the compression script.

**Describe alternatives you've considered.**

**Additional context**
I will be submitting a PR for this :)

Related: #493 

(We went from expecting zipfiles to expecting gzips in our storage engine, so have written support for both into our Archivematica branches).

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @helenst for this and #493 there's likely a corresponding change in the Storage Service you'd need to make for this so that pointer files are created properly and the storage service knows how to work with GZip. There's a bit more information [here](https://github.com/archivematica/Issues/issues/605) in my summary for Copy compression but let me know if we can clarify anything around this. 

The two main modules that I think you'll be looking at are: 

* [`common/utils.py`](https://github.com/artefactual/archivematica-storage-service/blob/d83d383f44dd258f6ba4c1b5a879ca22270e2ae6/storage_service/common/utils.py)
* [`locations/models/package.py`](https://github.com/artefactual/archivematica-storage-service/blob/3f21a96879103d6e550752770e344cff42cd919a/storage_service/locations/models/package.py)

And a good way to test the results are to verify the contents of the pointer file that's created for your compressed packages, and also test re-ingest, though there's only a little bit of logging around how the package is extracted following reading the pointer.

**Comment by sallain** [comment]
Documentation needs to be updated here: https://www.archivematica.org/en/docs/archivematica-1.9/user-manual/administer/dashboard-admin/#processing-config-fields

Also there's nothing about compression on the Ingest page; we might want to add something there? Not critical, though.

**Comment by ross-spencer** [comment]
@sallain @evelynPM I'm happy to pick up the docs if it hasn't been assigned?

**Comment by sallain** [comment]
@ross-spencer go for it!
