### ISSUE TITLE
Problem: Deleted AIPs are not removed from S3

### ISSUE THREAD

**Issue by dcraze** [archivematica/Issues#696]
**Expected behaviour**
When an AIP is deleted through Archivematica it should also be removed from the S3 AIP Store

**Current behaviour**
AIP is removed from the Archival Storage tab ands shows as Deleted in the Storage Service but the files are not removed from S3

**Steps to reproduce**
Create an AIP and store it in an S3 storage location
Request the AIP deletion from the Archival Storage tab
Approve the deletion request in the Storage Service
Note that the AIP is deleted in Archivematica but does not get removed from the S3 location.

**Your environment (version of Archivematica, OS version, etc)**
Reported by customer in 1.8.1 CentOS, reproduced in 1.9.1 Ubuntu 18.04

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by dcraze** [comment]
Justin suggests that adding logging to S3.py may be an option if logging is difficult to obtain from AWS.

**Comment by ross-spencer** [comment]
**Summary**

* S3 was added in this PR: https://github.com/artefactual/archivematica-storage-service/pull/342.
* One compromise for that PR seems to have been the disabling of S3 as a transfer source.
* Delete was [implemented](https://github.com/artefactual/archivematica-storage-service/blob/946a513da208f96c87b00f0ae86ad011d7e9baac/storage_service/locations/models/s3.py#L123-L127) at the time.

**Recreating the issue**

I have attempted to recreate the issue and at time of writing delete works in `qa/0.1` in the docker-compose environment. 

Here I have created an AIP `7716240d-`:

![image](https://user-images.githubusercontent.com/1880412/58612027-74afa080-82b1-11e9-990f-f50556b3dd99.png)

Following deletion the bucket is empty as it was the only object in the bucket:

![image](https://user-images.githubusercontent.com/1880412/58612042-842ee980-82b1-11e9-984b-86de055548fe.png)

I considered multiple objects as a problem:

![image](https://user-images.githubusercontent.com/1880412/58612061-901aab80-82b1-11e9-828f-5689409023b5.png)

But i delete `3d81` in the pair tree:

![image](https://user-images.githubusercontent.com/1880412/58612085-a4f73f00-82b1-11e9-9008-290168d7ac9c.png)

I considered a waiting period. These packages are ~200kb. I set an arbitrary timer of 10 mins. The packages were deleted in ~4 mins. 

**Future planning**

* The PR attached to [this ticket](https://github.com/archivematica/Issues/issues/712) upgrades the Boto3 S3 library.
* The response from the API when we delete an object is as follows:
```python
{  
   'HTTPStatusCode':204,
   'RetryAttempts':0,
   'HostId':'9ettu7axima1GwGoZlieS3MY0+jTKBl7S9/SiUUZiGqnmGHdQXNdlqBUPEtAPSFroQZPsOCyHqc=',
   'RequestId':'516CFCCFA6B322A1',
   'HTTPHeaders':{  
      'x-amz-id-2':'9ettu7axima1GwGoZlieS3MY0+jTKBl7S9/SiUUZiGqnmGHdQXNdlqBUPEtAPSFroQZPsOCyHqc=',
      'date':'Thu, 30 May 2019 05:43:49 GMT',
      'x-amz-request-id':'516CFCCFA6B322A1',
      'server':'AmazonS3'
   }
}
```
* This response looks to have been modified in the [latest Boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=delete_objects#S3.ObjectSummary.delete):
```
{
    'DeleteMarker': True|False,
    'VersionId': 'string',
    'RequestCharged': 'requester'
}
```
* If my reading of this is correct we can upgrade Boto3 and add the additional logging that JHS notes we can add to S3. It seems the more logging the better. I am wondering if it wasn't added in 2018 because the response was a little limited in what it tells us.

**For the user**

* We need to get more information.
* Ensure the client is aware that deletion is a two-step process in the Storage Service: 
   * Request (request deletion in packages tab) -> 
   * Confirm (confirm deletion with a given reason on the view delete requests page).
* If the package is still visible in the S3 space after a reasonable amount of time has elapsed, we should get more information about how that space is configured in S3, For example, I notice it is possible to set an Object-lock on a file. Has this been configured globally? Are there other configuration options in some deployments using S3 that can also prevent deletion on the Amazon side?

**Comment by ross-spencer** [comment]
@dcraze @ablwr this is a difficult one to demonstrate without adding some additional logging to the storage service. In fact, Boto3, and Amazon S3 can't really help us either. But I can now recreate this locally. 

Essentially; if this is a partial S3 configuration here: 

![image](https://user-images.githubusercontent.com/1880412/58876438-60fba400-86ce-11e9-9e60-15b667509f6f.png)

The leading slash will cause Boto3 to return no results when looking for matching packages in S3. 

Vs. 

![image](https://user-images.githubusercontent.com/1880412/58876490-8be5f800-86ce-11e9-92b4-4a0b7b2f65b8.png)

Without a leading slash. 

Again, it is difficult to demo without additional logging, so here is some modified code and the output when we do two deletion requests with the same package, but with different configurations:

```python
    def delete_path(self, delete_path):
        LOGGER.info("S3: entering delete path: {}".format(delete_path))
        obj = self.resource.Bucket(self._bucket_name()).objects.filter(
            Prefix=delete_path
        )
        items = False
        for objectSummary in obj:
            items = True
            resp = objectSummary.delete()
            LOGGER.info("S3 response when attempting to delete: %s", resp)
        if not items:
            LOGGER.error("S3: exiting delete path without deletion")
            raise StorageException("No packages found in S3 at: {}".format(delete_path))
        LOGGER.info("S3: exiting delete path following deletion")
```

**Broken config**
```
archivematica-storage-service_1  | INFO      2019-06-04 04:34:13  locations.models.s3:s3:delete_path:143:  S3: entering delete path: /abs-path/with/slash/rs-testing/29cb/7110/26f6/4325/b41d/46bf/021f/a9a4/s3_test_1-29cb7110-26f6-4325-b41d-46bf021fa9a4.7z
archivematica-storage-service_1  | ERROR     2019-06-04 04:34:14  locations.models.s3:s3:delete_path:153:  S3: exiting delete path without deletion
```
**Good config**
```
archivematica-storage-service_1  | INFO      2019-06-04 04:34:43  locations.models.s3:s3:delete_path:143:  S3: entering delete path: abs-path/with/slash/rs-testing/29cb/7110/26f6/4325/b41d/46bf/021f/a9a4/s3_test_1-29cb7110-26f6-4325-b41d-46bf021fa9a4.7z
archivematica-storage-service_1  | INFO      2019-06-04 04:34:44  locations.models.s3:s3:delete_path:151:  S3 response when attempting to delete: {'ResponseMetadata': {'HTTPStatusCode': 204, 'RetryAttempts': 0, 'HostId': 'sldzgBg5DHHhilR8M4pbGLSDS4JIbFVC2KtwgTrm8EFoDhIMyCaOL6NrgQqQtstsbxcVWfB+YMk=', 'RequestId': '5C959B776753F684', 'HTTPHeaders': {'x-amz-id-2': 'sldzgBg5DHHhilR8M4pbGLSDS4JIbFVC2KtwgTrm8EFoDhIMyCaOL6NrgQqQtstsbxcVWfB+YMk=', 'date': 'Tue, 04 Jun 2019 11:34:45 GMT', 'x-amz-request-id': '5C959B776753F684', 'server': 'AmazonS3'}}}
archivematica-storage-service_1  | INFO      2019-06-04 04:34:44  locations.models.s3:s3:delete_path:155:  S3: exiting delete path following deletion
```

**Paths**

1. (Won't work) `/abs-path/with/slash/rs-testing/29cb/7110/26f6/4325/b41d/46bf/021f/a9a4/s3_test_1-29cb7110-26f6-4325-b41d-46bf021fa9a4.7z`
 
2. (Will work) `abs-path/with/slash/rs-testing/29cb/7110/26f6/4325/b41d/46bf/021f/a9a4/s3_test_1-29cb7110-26f6-4325-b41d-46bf021fa9a4.7z`

We didn't  have a lot of checking in the S3 module and not a lot of feedback either. Boto3 is also returning a Python [generator](https://wiki.python.org/moin/Generators) which we were consuming incorrectly, or at least, consuming without doing any additional checks whether it was or wasn't being consumed. 

In short, we assumed we were looping through a set (of one) objects for deletion, but because the generator had zero-results we never looped at all. The function quietly exits and the Storage Service is non the wiser. 

So, no need to confirm procedure with the client now, but it would be great to see the setup of their Space, and also the setup of their S3 location. We can then confirm whether simply removing the leading-slash from the Space's `Path` will re-enable deletions from the Storage Service. 

I have left am191 bionic configured correctly, with no code-changes to demonstrate S3 deletions work. Feel free to give it a go to confirm. 

I have started a PR for the Storage Service and will look at a corresponding PR for Archivematica as well to make sure that there is more feedback and neither service is reporting incorrect information when something is not deleted. 

I'll be interested to hear if this is fixed by removing the leading slash for the original site reporting the issue as well. 

* [Boto3 API 'generator' docs]( https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/resources/collection.html#ResourceCollection.all)

**Comment by ablwr** [comment]
Very interesting investigative work, Ross!!

**Comment by ross-spencer** [comment]
Update following our conversation yesterday, cc. @ablwr 

Whether removing the `/` from the Path in the Space will work in the interim is also contingent on the Location 'Relative path` and so:

**Won't work** 

![image](https://user-images.githubusercontent.com/1880412/58948608-c44b0c00-878a-11e9-89af-6b1f23f6b324.png)

**Will work**

![image](https://user-images.githubusercontent.com/1880412/58948621-cc0ab080-878a-11e9-84eb-2a9a68888972.png)

So this can be rectified by removing the trailing slash from the relative path as well if there is one. 

Testing this locally works. 

The only issue will be if relative path is just `/` because the field right now is marked as required, and so cannot be blank.

![image](https://user-images.githubusercontent.com/1880412/58949041-c5c90400-878b-11e9-993e-520fa7802660.png)

:crossed_fingers: it's resolved with removing the trailing-slashes and the field isn't currently blank. 

For future packages stored in an S3 bucket a user can just fill in the relative path value with something sensible. 

I will try and update the docs with some of this info as part of the PR. Also related: https://github.com/archivematica/Issues/issues/321

**Comment by ross-spencer** [comment]
**NB.** I wonder if another future approach to maintaining S3 locations will be to implement `update_package_status` per https://github.com/archivematica/Issues/issues/746. `STATUS` is nearly entirely a logical procedure for S3 in Storage Service at present, so being able to get concrete feedback about a status is a good idea. If it is suspected a package isn't deleted, then re-enabling the ability to delete a package would be great (or at least, setting the status to something more appropriate to signal that would be great).

**Comment by obruchez** [comment]
It looks like I still have this issue with Archivematica 1.11.0 (Storage Service 0.16.0).

I have an S3 space with no path and a replicator location on the S3 space with a relative path of "aip-store" (no leading or trailing slash).

Nothing is deleted from my bucket when I delete an AIP. It is deleted from the local filesystem space, though.

Two other related minor problems:

- I'm not sure why I have to define a relative path ("aip-store", in this case), as the bucket will contain only AIPs. It would be cleaner for me not to have that mandatory relative path.

- When an AIP is removed from a local filesystem space, the empty GUID sub-directories in AIPsStore are not removed (e.g. /sharedDirectory/www/AIPsStore/0b41/df85/4373/4c87/a6b7/3e97/7037/8beb doesn't contain anything, but the sub-directories are still there). Shouldn't they be deleted as well?

**Comment by sromkey** [comment]
I don't think this is an S3 specific problem, I think you are experiencing issue #985 .

Regarding the subdirectories, that is also an open issue! #359
