### ISSUE TITLE
Problem: FITS doesn't add useful information

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#703]
**Please describe the problem you'd like to be solved.**

Currently the only output from fits that can't be obtained by other characterization tools, is the filesystem  metadata. But fits is a big java app, that needs a custom aplication server (nailgun) , and is usually one of the most slow tasks in archivematica.

**Describe the solution you'd like to see implemented.**
Change the default characterization tool from fits to a script that runs `stat`

**Describe alternatives you've considered.**
Remove fits

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Related: https://github.com/archivematica/Issues/issues/77.

**Comment by ablwr** [comment]
Related: https://github.com/archivematica/Issues/issues/502, https://github.com/archivematica/Issues/issues/357

**Comment by sromkey** [comment]
I'm proposing now that we refine this and propose a deprecation of FITS in the 1.11 release, given how easy it is to disable FITS in the FPR currently. This gives us the chance to get community feedback and possibly propose an alternate characterize-fall-back method.

**Comment by andrewjbtw** [comment]
I would love to see FITS removed as a default. A script that returns filesystem metadata also would be less likely to return invalid XML to stdout, something FITS still does on occasion, leading to its output being discarded altogether.

**Comment by sromkey** [comment]
At a high level I believe we've decided not to tackle this until post 1.11 but I'll wait to confirm with other team members before bumping the triage label.

**Comment by ross-spencer** [comment]
I believe last modified date has been one of the questions around the removal of FITS as a default. And I think is why `stat` is alluded to in the main body of this issue. I've recorded some notes about this and demonstrated why this need not be a sticking point. NB. this will encode other's thinking around this too, so credit to those who have shared this information previously in notes and Slack. 

* [Removing FITS as a default (MKV Public Google Drive Link)](https://drive.google.com/file/d/1oAgHo-OAv8lacxL9ZZLX-fhx2evFITlE/view?usp=sharing)

**Comment by tw4l** [comment]
Just to confirm what @ross-spencer is saying above, it looks like the logic for recording the modified date as `dateCreatedByApplication` was added in commit https://github.com/artefactual/archivematica/commit/429b35cfeedca6e797df77e6356be29858d169f8 and is not at all dependent on FITS.

**Comment by tw4l** [comment]
One issue I discovered with `dateCreatedByApplication` while working on some updates to METSFlask is that the value Archivematica is storing is an ISO 8601-formatted datestamp without any time information - i.e. YYYY-MM-DD ([here's the relevant bit of code](https://github.com/artefactual/archivematica/blob/3e52494735ebfeb0cabc477d95d692034f4b3142/src/MCPClient/lib/clientScripts/create_mets_v2.py#L541-L545)).

So if FITS is disabled, Archivematica does not record date information below the day. Personally, that seems like a big deal to me because in my experience and [digital archives user research](https://www.bitarchivist.net/blog/2017-05-04-usersurvey/), modified dates are often one of the first bits of information that end users look for to orient themselves with digital objects in a research setting. Some workflows like the [CCA DIP creation script in the Automation-Tools repo](https://github.com/artefactual/automation-tools/blob/master/aips/create_dip.py) even rely on having access to more granular timestamps to restore modified dates in DIPs, so that users can browse files in a local filesystem similar to how they are used to with their own files.

The PREMIS 3 Data Dictionary shows examples of more granular timestamps used with `dateCreatedByApplication` ([see page 79](http://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf)) - e.g. "20030223T151047".

I think we should consider making the time recorded by `dateCreatedByApplication` more granular, or keep it as it is and additionally store a Unix timestamp somewhere in the PREMIS object metadata for original files.

**Comment by replaceafill** [comment]
I'm currently evaluating the removal of the [FITS_v0.0](https://github.com/artefactual/archivematica/blob/48d3c1140b6b2dba9dae4f99c1edae8a7bbb7ebc/src/MCPClient/lib/clientScripts/fits.py) client script.

It's a bit particular because it runs FITS directly no matter what configuration you have in the FPR. From looking at the git history of the script it seems like it used to do [file format identification](https://github.com/artefactual/archivematica-history/commit/d670d7b965299210a762927c61a1fa429c0c3f71#diff-19da87ca972437e568a720d0d25da44ccd0ccf8d6d55f75db34ebf90b7176616) first and then [validation](https://github.com/artefactual/archivematica-history/commit/b9ed546ed7fbd07d845fd378f72bcfac9e6654d4). After that functionality was dropped over time it remained to be used for [characterization](https://github.com/artefactual/archivematica/commit/0c0bc980da05cce1f608429798372f82119beda4) until now.

Unfortunately, it's currently broken because it hard codes the characterization rule UUID to represent an [outdated use of the FITS rule](https://github.com/artefactual/archivematica/commit/4eac54958cb76fdbc162a083d63c9f3a7d22e2e5). See it in the sandbox which currently runs 1.16.0 at https://sandbox.archivematica.org/fpr/fprule/characterize/ and notice its purpose is `characterize` unlike the rest of the [`characterization` rules](https://sandbox.archivematica.org/fpr/fprule/characterization/) which makes the METS creation process to [ignore any of the script related output](https://github.com/artefactual/archivematica/blob/48d3c1140b6b2dba9dae4f99c1edae8a7bbb7ebc/src/MCPClient/lib/clientScripts/create_mets_v2.py#L614-L617).

The `FITS_v0.0` script is referenced to run in two specific points in the MCPServer workflow:

* The [`objects/attachments` directory](https://github.com/artefactual/archivematica/blob/48d3c1140b6b2dba9dae4f99c1edae8a7bbb7ebc/src/MCPServer/lib/assets/workflow.json#L9047-L9081) in a Maildir transfer
* The manual preservation files under [`objects/manualNormalization/preservation`](https://github.com/artefactual/archivematica/blob/48d3c1140b6b2dba9dae4f99c1edae8a7bbb7ebc/src/MCPServer/lib/assets/workflow.json#L1926-L1955)

Since we don't support the Maildir transfer type anymore, I think we can safely remove the first case.

The second case however still seems valid. We even have item [2.5](https://github.com/archivematica/testing-checklists/blob/40cc37cb1dbe73f74d5347a62a50aeebbc9e19f6/.github/ISSUE_TEMPLATE/issue_template.md#25) in the release testing checklist to test manual normalization. You can run that transfer and check its `Ingest -> Microservice: Process manually normalized files -> Job: Run FITS on manual normalized preservation files` job to see the script being run.

I'm going to explore changing this second case to use the `characterizeFile_v0.0` script instead which does follow FPR policies, similarly to how we characterize metadata and submission documentation files.

**Comment by sromkey** [comment]
We've been testing AM 1.17 with FITS removed without issue, but I think I'd like to give @scollazo the honour of closing this issue :joy:

**Comment by scollazo** [comment]
Thanks to everyone involved, it's been indeed a team effort!
