### ISSUE TITLE
Allow s3 credentials fields to be blank

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#712]
**Please describe the problem you'd like to be solved.**
In some setups it is preferable / necessary to supply AWS credentials through environment variables / credentials files / IAM role providers at deployment time, rather than the user providing these through the UI.

**Describe the solution you'd like to see implemented.**
`access_key_id` and `secret_access_key` fields should be allowed to be blank, so that the user can ignore these fields and use the credentials from the environment

**Describe alternatives you've considered.**
I'm not sure what alternatives there are, other than continuing to require the credential fields to be entered. In setups involving IAM roles this would require an extra field to specify the role. But for automated deployments where the roles are set up at deploy time and credentials aren't exposed to the user, it makes sense to allow the server environment to provide the authentication.

**Additional context**
This was developed in the context of a Terraform deployment using IAM roles and policies to provide bucket access.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
For testers, there are notes [here](https://github.com/artefactual/archivematica-storage-service/pull/498#pullrequestreview-330962687).

It should be possible to configure an S3 space and leave the following two fields blank:

* Access Key ID to authenticate.
* Secret Access Key to authenticate with.

Those are the first two criteria. 

Two values can then be configured in the environment in the storage service by doing the following.

1. SSH to the machine.
2. `sudo su - archivematica`

Set the following `env` variables:

3. `$> AWS_ACCESS_KEY_ID=<value for access key id>`
4. `$> AWS_SECRET_ACCESS_KEY=<value for access key>`

**NB.** you can test one or the other by doing the following: `echo $AWS_ACCESS_KEY_ID` and it will print your new value. 

They should be picked up by the storage service when writing to S3 and an AIP successfully stored. If an AIP isn't stored, then we should double-check my workings above, but then it would otherwise indicate something not quite right with this feature.

### On documentation

The README for the storage service has been updated, but there is also a note in the PR above about potentially adding more in the docs proper. Helen has made a note about that and priorities, we should be able to coordinate something after the code deadline.

**Comment by replaceafill** [comment]
I tested this with docker (setting the env variables in `docker-compose.yml`) and it works nicely. The docs have also [been updated](https://github.com/artefactual/archivematica-storage-service-docs/pull/32) so I'm marking it as done :+1:
