### ISSUE TITLE
Problem: Cannot rebuild transfer backlog or AIP indices when location is encrypted

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#734]
**Expected behaviour**

The rebuild commands should rebuiild indices when locations are encrypted
**Current behaviour**

The rebuild commands fail when using encrypted locations

**Steps to reproduce**

Running the rebuild commands with encrypted locations: https://www.archivematica.org/en/docs/archivematica-1.9/admin-manual/maintenance/maintenance/#rebuild-the-indexes

**Your environment (version of Archivematica, OS version, etc)**

AM1.9.1, ubuntu 18.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
Copied from original issue: https://github.com/artefactual/archivematica/issues/916

**Comment by joel-simpson** [comment]
@cole can you please have a look at this and estimate how much effort needed to fix so we can decide whether to include in 1.10 release? 
thx

**Comment by sevein** [comment]
I've been told that SIP arrangement is also not working. I'll take a look tomorrow.

**Comment by sevein** [comment]
It seems that Storage Service allows encryption of the transfer backlog location but my impression is that's almost accidental - in practice I believe that the encryption of the transfer backlog is going to need much extra care.

`rebuild_transfer_backlog` assumes full access to the transfer backlog unencrypted so it can have access to their contents, e.g. for search indexing, processing the METS files, etc... `rebuild_transfer_backlog` was implemented before encryption and it was never updated accordingly - it could be updated to ask Storage Service to decrypt the packages in advance.

I've also been doing testing in Appraisal, which also breaks when the backlog is encrypted:
- The backlog pane is working, this is because it's based on the data that we put in the search indices and they're populated before encryption happens. One question is whether indexing metadata about encrypted transfers is a good idea at all.
- File preview or file download works because Storage Service decrypts the transfer on demand. It doesn't seem to scale very well as the package grows in size since you're decrypting the whole thing anyways.
- SIP arrangement works (also based on pre-populated search indices) but the actual SIP creation operation breaks. The error shown to the user is `SIP could not be started! Check dashboard logs.` and this is what I've seen in the logs: https://git.io/fjai0. A side effect is that the package appears unencrypted in backlog after the error occurs, which also seems undesirable. There's probably an issue in Storage Service dealing with this situation between spaces, i.e. currently processing + encrypted backlog but I haven't been able to track it down.

**Comment by sromkey** [comment]
Until we discuss this further, we should review the user documentation and make more clear what is supported for encryption and what is not.

**Comment by sevein** [comment]
I think that this is a major change, 1-2 weeks. We'd need some kind of layer in Archivematica to perform decryption via Storage Service when we need access to the data. That'd be true in the rebuild command but also from appraisal.

**Comment by tw4l** [comment]
Our current approach in `rebuild_transfer_backlog.py` and `rebuild_elasticsearch_index_from_files.py` relies on walking the backlog and AIP store locations, respectively, to discover relevant packages and the METS files needed for reindexing.

I think if we changed our approach to instead use Storage Service API endpoints to retrieve a list of the packages that need to be reindexed (filtering on package type, status, storage location, and/or origin pipeline, as appropriate) and then use the `extract_file` endpoint to download a copy of the METS file for each package to use in reindexing (which does work with encrypted packages), we could simplify these scripts a bit and avoid some of the problems involved in trying to walk an encrypted storage location.

There would be some design decisions to make around whether to replace or supplement the existing behaviour, and admittedly there are some limitations, namely: (1) this wouldn't solve the issues mentioned above that are unrelated to reindexing, and (2) as @sevein writes above, if the `extract_file` endpoint needs to decrypt the whole package, this might not scale very well to large packages. But on the other hand if we can live with those trade-offs for now, I think I could get the reindexing scripts working for encrypted storage locations in much less time (~2-3 days).

@sevein What are your thoughts? The inability to reindex encrypted storage locations has become a is complicating QA/acceptance of #1167 and #1168 and it might be possible to make these changes within that project scope, but I would understand if you'd rather hold off and tackle the underlying issue also affecting appraisal.

**Comment by sevein** [comment]
Well thought! Sounds like a plan, thanks.

**Comment by scollazo** [comment]
The approach described by @tw4l would also help in cases where the storage service runs in a different vm than the dashboard. 

The workaround we use now in those cases, is mounting the aipstores in the vm running the dashboard using the same paths than they have in the SS, in order to be able to run the reindex.

**Comment by ross-spencer** [comment]
Created a single AIP in an encrypted space on bionic `451ab553-4deb-4001-9424-3b7425ec66c9`.

![image](https://user-images.githubusercontent.com/1880412/91596894-f1a54c00-e932-11ea-8c42-c7028aa058f2.png)

Deleted the AIP index on Bionic: `curl -XDELETE "http://127.0.0.1:9200/aips,aipfiles,transfers,transferfiles"`

![image](https://user-images.githubusercontent.com/1880412/91597238-0a156680-e933-11ea-94e9-44fd1e381b71.png)

Ran the new command to index from the storage service:

```
root@am112bionic:~# sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /opt/archivematica/archivematica/src/dashboard/src/
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_aip_index_from_storage_service";
...
...
Indexing complete. Successfully indexed 24 AIPs/AICs.
```

Went looking for my AIP and found it, plus the rest of the search index repopulated:

![image](https://user-images.githubusercontent.com/1880412/91597824-2dd8ac80-e933-11ea-8344-e459eb485bfb.png)

So this feature is also looking pretty:

![nice](https://media0.giphy.com/media/1jkV5ifEE5EENHESRa/giphy.gif?cid=ecf05e47yfkz6sikvrx97smiqxf1q7996z6lyw8pfvdp1c1b&rid=giphy.gif)
