### ISSUE TITLE
Problem: Decision required on using superseded section in pointer files following reingest

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#738]
To push work on the storage service, it was suggested we merge [#466](https://github.com/artefactual/archivematica-storage-service/pull/466). As a result of that at present there is a slight change in the pointer file where a new superseded section appears as per @cole's comments [here](https://github.com/artefactual/archivematica-storage-service/pull/466#issuecomment-501120551). This work can be followed up to be changed back to the original behavior, or possibly followed up to correct (e.g. what should this look like if a user reingests three times, do we have two superseded segments, not just the one?) 

Additional notes: https://gist.github.com/cole/3578516be27039716043409cc13ad19e

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
My opinion is that the pointer file behaviour should be as consistent as possible with the AIP METS behaviour. So this would mean 1. using superseded techMDs rather than replacing them and 2. continuing to supersede as many times as the AIP in reingested.

**Comment by ross-spencer** [comment]
Thanks @sromkey.

CC. @cole ^^^ I think then that perhaps following [#466](https://github.com/artefactual/archivematica-storage-service/pull/466) we might just be missing *(n-1)*  superseding elements where a package is reingested *(n)*-times. I can try and test this again today, but more likely it will be early next week at this point.

**Comment by cole** [comment]
It looks like the current behaviour is (as @ross-spencer suspected) that the first reingest supersedes the old techmd, but subsequent reingests replace the superseded techmd, meaning that you have the most recent and second most recent techmds, but not the full history.

**Comment by cole** [comment]
Er, so I think I misunderstood how pointer files work together with reingest, and the superseded techMD doesn't actually make sense.

Pointer files are created by Storage Service on submission of a compressed AIP. However, crucially, they aren't persisted through a reingest ([source link](https://github.com/artefactual/archivematica-storage-service/blob/stable/0.14.x/storage_service/locations/models/package.py#L2155)). There are a couple different cases to consider: initially uncompressed -> reingest with compression, initially compressed -> reingest with compression, initially compressed -> reingest without compression. The only case where it seems logical to persist pointer files is when the AIP is initially compressed and then reingested with compression (so both need a pointer file), and in that case we're explictly deleting the existing pointer file. We could (and maybe should) change this behaviour, but I'm not sure that's in scope for this issue.

The reason metsrw started adding a 'superseded' section (due to changes in https://github.com/artefactual/archivematica-storage-service/pull/466) was simply that we actually update the pointer file twice when reingesting...so it was creating a techMD, and then immediately superseding it. The PR attached to this issued now removes the superseded techMD from the output.
