### ISSUE TITLE
Wrong DIP shown on "Review DIP" page

### ISSUE THREAD

**Issue by finoradin** [archivematica/Issues#76]
**Expected behaviour**
When clicking "review DIP" from the ingest pane, one should see the browsable contents of the DIP created from their SIP – one measure of which being does the DIP "objects" directory contain files with similar original name parts as the AIP "data" directory.

**Current behaviour**
No matter what files I ingest, when clicking "Review DIP" I am shown a DIP that appears to contain the digital objects from the "Images" Sample Transfer data. 

**Steps to reproduce**
Create a transfer containing anything **but** SampleTransfers/Images, create one SIP, normalize for access, do not upload the DIP, store the DIP and the AIP, click "review" on the DIP and view the file listing. Download the AIP and compare.

**Your environment (version of Archivematica, OS version, etc)**
http://sandbox.archivematica.org

**Comment by sallain** [comment]
Hi @finoradin, thanks for this report. This is a known issue - the Review DIP button currently points to the uploadedDIPs directory, which only contains DIPs that users have uploaded (or attempted to upload), rather than DIPs that are stored*. The placement of the button on *Job: Store DIP* is therefore misleading. I believe that @sevein has a fix for this in the works related to #62, which is currently milestoned for Archivematica 1.8.

I'm going to mark this as a duplicate issue and close, even though this issue explains the Review DIP button confusion better than the related issue (#62) :slightly_smiling_face: 

*Note that in the case of DIPs stored in the sandbox as of Tuesday 14 August at 1:30pm PST, the contents of the DIPs are correct. There are two DIPs (*abc* and *merl-test*) and both result from SIPs created from the Images sampledata.
