### ISSUE TITLE
Problem: `watchedDirectories/SIPCreation/completedTransfers` directory not cleaned-up

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#769]
**Current behaviour**
Archivematica keeps transfer/ingest related files (logs, metadata, METS, processing config, etc) in the `watchedDirectories/SIPCreation/completedTransfers` directory after the SIP has been ingested completely. This affects the server stability/performance for the following reasons:

* It takes up disk space that can not be cleared using the web UI (i.e.,  Administration>Processing storage usage)
* When Archivematica services are restarted, database queries seem to be executed for these SIPs (because of being in watchedDirectories?), delaying the time the server is operational again.

This is particularly problematic on servers that processed large number of ingests (e.g., servers running automation tools, that can have thousands of completed ingests)

**Expected behaviour**
Directory should be cleaned up (need to be confirm if Archivematica does not require these files for some purpose after the ingest. If it does, probably these files need to be moved somewhere else)

**Steps to reproduce**
Ingest a source completely, then check the mentioned directory

**Your environment (version of Archivematica, OS version, etc)**
Any version (checked on 1.6.x, 1.9.x, qa/1.x)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by tw4l** [comment]
This is no longer an issue in Archivematica 1.11, due to commit https://github.com/artefactual/archivematica/commit/3e52494735ebfeb0cabc477d95d692034f4b3142. Archivematica 1.11 does not leave files in `completedTransfers` after a transfer is moved to the backlog or sent on to SIP creation/Ingest.

In Archivematica 1.10 and before, these metadata files were written into `completedTransfers` and later copied into the SIP by the `copy_transfer_submission_documentation.py` and `copy_transfers_metadata_and_logs.py` client scripts during the "Process submission documentation" and "Process metadata directory" microservices. The files in `completedTransfers` were not cleaned up after that point, but can be safely deleted after those microservices complete.

In Archivematica 1.11, these metadata and submission documentation files are copied into a tmp directory rather than `completedTransfers`.
