### ISSUE TITLE
Problem: Dashboard does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#810]
**Please describe the problem you'd like to be solved.**
[Dashboard](https://github.com/artefactual/archivematica/tree/a889605d8c97e114f8c0bc707d6a371030fb5c0b/src/dashboard) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor Dashboard to use Python 3.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
Related: #392

**Comment by ross-spencer** [comment]
From internal discussions, we will review the Dashboard code and try and bring it all into `1.11` with the goal to run the Dashboard as Python 3. The fallback is to bring all of the code into `1.11` and still run it as Python 2. To get to either position:

1. Develop the strategy around https://github.com/archivematica/Issues/issues/845
2. Review and test Dashboard code. 
3. Investigate deployment requirements to run one component of AM in Py3. (And upgrades).
4. Merge, and either run in Py3 or Py2.

**Notes on Python 2.7 in 2020:**

Python 2.7 final release in July 2020: [here](https://www.python.org/dev/peps/pep-0373/#id5)
Ubuntu 20.04 (LTS) and Python 2.7: [here](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Continue-Py2-Drop)
Python3 may be default in CentOS8/RHEL8: [here](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/)

**Comment by ross-spencer** [comment]
Closing with note from Slack re: PY3 readiness:
===
I think given the extensive use through testing, and the fact anything works on any of the servers, they can be signed-off. As working baby-steps to Py3 :snake:.

And to answer your question -- Dashboard: unfortunately not because of Gearman. But once the Gearman problem is solved, then theoretically yes. But it's a moving goalpost for now until we commit to making a Py3 virtual environment available (or docker image) in a future release + Gearman 3.

Storage Service - we'd need to fill in those storage service specific gaps first. But it's looking good so far.

**Comment by ross-spencer** [comment]
NB. Complete Py3 readiness will need to be handled in a separate Issue along the lines of https://github.com/archivematica/Issues/issues/806#issuecomment-585311263
