### ISSUE TITLE
Problem: agentarchives does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#813]
**Please describe the problem you'd like to be solved.**
[agentarchives](https://github.com/artefactual-labs/agentarchives) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor agentarchives to use Python 3.

**Additional context**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
I've changed the CI tests in agentarchives to run over 2.7 and 3.5 to 3.8 in the PR above. The 3.4 version tests were failing due to the PyYAML requirements (needed by vcrpy), but supporting that version is no longer needed based on the ADR.

Tests are passing in all versions and, if we exclude the Archivists' Toolkit client tests, the coverage is not bad ...

```
Name                                           Stmts   Miss  Cover
------------------------------------------------------------------
agentarchives/__init__.py                          1      0   100%
agentarchives/archivesspace/__init__.py            1      0   100%
agentarchives/archivesspace/client.py            405     66    84%
agentarchives/archivists_toolkit/__init__.py       1      1     0%
agentarchives/archivists_toolkit/client.py       234    234     0%
agentarchives/atom/__init__.py                     1      0   100%
agentarchives/atom/client.py                     296     43    85%
------------------------------------------------------------------
TOTAL                                            939    344    63%
```

It would be nice to do some integration tests wit AM before releasing agentarchives 0.6.0, but I've also updated the `setup.py` file in preparation to do so.

**Comment by jraddaoui** [comment]
The agentarchives release would mostly be needed to update the requirements in PyPi, since it no longer supports 3.4. The only new feature since 0.5.0 would be https://github.com/artefactual-labs/agentarchives/commit/919e8ed00cd70e6956ff730ec8209ff1f0dd2850, all the other changes are related to styling and CI.

AM is already using agentarchives 0.5.0 but I'm not sure what the testing plan is for all the Py3 issues, maybe we should start closing those that we consider "done" and report new ones when we test Py3 altogether.

**Comment by sevein** [comment]
> The agentarchives release would mostly be needed to update the requirements in PyPi, since it no longer supports 3.4. The only new feature since 0.5.0 would be artefactual-labs/agentarchives@919e8ed, all the other changes are related to styling and CI.

Let me know if you need access to PyPI!

> AM is already using agentarchives 0.5.0 but I'm not sure what the testing plan is for all the Py3 issues, maybe we should start closing those that we consider "done" and report new ones when we test Py3 altogether.

Sounds like a plan!

**Comment by replaceafill** [comment]
We just switched the `agentarchives` repository CI to use GitHub Actions, and we're now testing with [all active Python releases](https://devguide.python.org/#status-of-python-branches) except for 3.9 which is broken because of https://github.com/archivematica/Issues/issues/1330. I still think this can be closed.
