### ISSUE TITLE
Problem: archivematica-acceptance-tests does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#816]
**Please describe the problem you'd like to be solved.**
[archivematica-acceptance-tests](https://github.com/artefactual-labs/archivematica-acceptance-tests) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor archivematica-acceptance-tests to use Python 3.

**Additional context**
Some Python 3 compatibility work has already been done on archivematica-acceptance-tests. It should be checked to ensure that all code has been refactored.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jraddaoui** [comment]
It looks like the archivematica-acceptance-tests require Python 3 since the beginning. On the Docker environment they're run with Python 3.6.

https://github.com/artefactual-labs/archivematica-acceptance-tests#installation-quickstart
https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/stable/1.11.x/Dockerfile#L1
