### ISSUE TITLE
Problem: jp2 files will not normalize in Archivematica 1.7

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#91]
_From @sallain on July 4, 2018 0:34_

Trying to normalize a jp2 file for preservation in Archivematica using the default rules and commands (`transcode to tif using convert`) fails with the following error:

```
convert: no decode delegate for this image format `JP2' @ error/constitute.c/ReadImage/501.
convert: no images defined `/var/archivematica/sharedDirectory/currentlyProcessing/joburg-test-0a0fe86d-9491-4d39-8c37-7407acfe0e71/objects/oakland03-e57cae6f-a7a0-4003-a2ec-658cd2a593d0.tif' @ error/convert.c/ConvertImageCommand/3210.

Failed: Transcoding to tif with convert
Standard out: 
Standard error: convert: no decode delegate for this image format `JP2' @ error/constitute.c/ReadImage/501.
convert: no images defined `/var/archivematica/sharedDirectory/currentlyProcessing/joburg-test-0a0fe86d-9491-4d39-8c37-7407acfe0e71/objects/oakland03-e57cae6f-a7a0-4003-a2ec-658cd2a593d0.tif' @ error/convert.c/ConvertImageCommand/3210.

Command Transcoding to tif with convert failed!
```

Based on some [light](https://askubuntu.com/questions/899541/how-to-enable-jpeg2000-jp2-in-imagemagick) [googling](https://www.imagemagick.org/discourse-server/viewtopic.php?t=12366), it seems like this might be an ImageMagick dependency issue - it needs certain delegate libraries for specific formats.

_Copied from original issue: artefactual/archivematica#1179_

**Comment by ablwr** [comment]
Yeah... ffmpeg runs into this problem as well, has to be installed with a specific flag. As the bug report @ross-spencer linked to mentions, openjpeg is specifically to deal with JPEG 2000 files, which aren't very common, and it's like a reverse-engineered encoder-decoder for a proprietary format.

Did some testing to see if I could leverage the jp2 reading abilities of Ghostscript, which we also use, but I don't think we can use it to convert. We will have to do what @scollazo recommends and build with libopenjp2 or whatever the current flag is.

**Comment by ablwr** [comment]
OK, I did some testing in 1.7x QA for Ubuntu and for CentOS with a script that I believe is producing optimal results with using `ffmpeg` as the normalization service tool instead of `convert`.

I tested some "irregular" jp2k files and they worked with neither script, but our standard test jp2 and other standard jp2 files work fine. Locally, my "fresher" version of ffmpeg (4.x+) is able to handle these fuzzy jp2 files, so if we are able to upgrade ffmpeg in Archivematica in the future, it'll extend the normalization abilities.

We can discuss this in our internal call later today!

Then I can do the work to make the change, which requires working with migrations, etc. I got some advice on this from @ross-spencer. My dev environment is yet to be set up, but I should be able to work on it by next week (along with general things and a return to local testing, woO!).

**Comment by ablwr** [comment]
My proposed change:

ffmpeg -i "%fileFullName%" -compression_algo raw -pix_fmt rgb24 "%outputDirectory%%prefix%%fileName%%postfix%.tif"

-compression_algo raw to pass everything through without compression
-pix_fmt rgb24 to give the highest color depth available and standardize it across

@sevein did the bulk of the migration yesterday while I watched and learned. But it's not picking up here? https://github.com/artefactual/archivematica-fpr-admin/pull/85

**Comment by sromkey** [comment]
This is working fine now, I tested with the Images sample transfer and ffmpg successfully made a tiff from a jp2.
