### ISSUE TITLE
TRIM transfer source type is not shown in the dashboard

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#932]
**Expected behaviour**
TRIM transfer source type shown in the dashboard

**Current behaviour**
TRIM transfer source type is not shown in the dashboard. The microservice scripts supporting the required workflow seem to be already in the codebase (ref. https://github.com/artefactual/archivematica/pull/621 for example)

**Steps to reproduce**
Dashboard transfer tab: check the available transfer types.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM1.10 (same for previous versions)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Hi @hakamine just wondering, do we have [sample-data](https://github.com/artefactual/archivematica-sampledata)/does it make sense to have sample-data for a TRIM transfer that helps created automated testing around it, e.g. in our [create-aip](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/master/features/black_box/create-aip.feature) feature?

**Comment by hakamine** [comment]
@ross-spencer after a bit of internal discussion, it seems to me that the way the TRIM workflow is currently implemented in AM is very customized for a particular case, so probably not good to enable TRIM transfers in mainline code (and probably not required to add testing for it I guess)

**Comment by ross-spencer** [comment]
Thanks Hector. 

Just to capture a little more information, we have the following TRIM based scripts in Archivematica:
```
create_sips_from_trim_transfer_containers.py
trim_create_rights_entries.py
trim_restructure_for_compliance.py
trim_verify_checksums.py
trim_verify_manifest.py
```
From `workflow.json` it looks like ~15 chain-links are used by TRIM at present before it merges with the standard workflow. 

![image](https://user-images.githubusercontent.com/1880412/66395287-48323080-e9d7-11e9-87ac-38533950205b.png)

(This is just a small snippet, as it's hard to capture the workflow otherwise).

And it looks like TRIM can be started from the API as a potential workaround when it cannot be accessed via the dashboard:

![image](https://user-images.githubusercontent.com/1880412/66395731-76fcd680-e9d8-11e9-9232-1f6664ad9ae5.png)

```
http --pretty=format \
    -f \
    POST "http://127.0.0.1:62080/api/transfer/start_transfer/" \
    Authorization:"ApiKey test:test" \
    name="api-demo-1" \
    type="TRIM" \
    paths[]="\
    [$(echo -n '7fd1e907-08c9-4e65-811a-ae8953253f35:/home/archivematica/archivematica-sampledata/api-demo/trim' \
    | base64 -w 0)]"
```

**Comment by sromkey** [comment]
As Hector mentioned above the internals of how the TRIM import works are too client-specific to be generalized, so I'm closing this issue.
