### ISSUE TITLE
Problem: SQLite as Storage Service database limits concurrency

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#952]
**Expected behaviour**

Archivematica Storage Service uses a database that can support concurrent writes.

**Current behaviour**

Archivematica Storage Service uses the SQLite database, which is really wonderful for systems that don't require write concurrency. However, in Archivematica Storage Service, we should be able to do database writes (done when storing a package, for example) without delaying all other writes. SQLite uses an internal lock to only allow one connection to write at a time, and if another connection is waiting it will time out quite quickly.

**Steps to reproduce**

This isn't reliable, as it depends on timing.

1. Enable multiple gunicorn worker threads in Archivematica Storage Service.
2. Process a large number of transfers concurrently.

**Your environment (version of Archivematica, operating system, other relevant details)**

docker / qa/0.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by cole** [comment]
Somewhat related to: https://github.com/archivematica/Issues/issues/730

**Comment by cole** [comment]
Also relates to: https://github.com/archivematica/Issues/issues/784

I see the solution to that issue as documenting the options, and this issue as changing the default.

**Comment by jorikvankemenade** [comment]
@cole a question that is slightly related to the problem you are describing here. When I am running a lot of concurrent transfers, I sometimes get that the SS times out because it is busy. In the reproduction part of this issue, I see that it is possible to enable multiple gunicorn worker threads in Archivematica. Would enabling multiple worker threads be a solution to this problem?  This is, of course, assuming that the SS is backed by a proper database server and not SQLlite.

**Comment by cole** [comment]
@jorikvankemenade Yes, increasing the number of workers processes (gunicorn has options for both threads and proecesses) should (hopefully) solve that problem. If you're using MySQL (or another that's not SQLite), I don't see any downside to increasing the number of workers, so I would say first try setting `SS_GUNICORN_WORKERS` (I would use 2-4, depending on the number of cores.  There is also the `SS_GUNICORN_WORKER_CLASS` which can be changed to `sync` to avoid gevent, but I'm not sure that needs to be changed.

**Comment by sevein** [comment]
The solution is to move away from SQLite which is the default engine in Storage Service. It doesn't sound unrealistic since Archivematica uses MySQL too. It would be relatively easy to make MySQL the default for new installations, but existing users need to follow a migration process that we have not developed/documented. However we're confident that the migration is possible and I think Santi and Miguel had some success during their inital tests.

**Comment by ross-spencer** [comment]
Related to: https://github.com/archivematica/Issues/issues/1036

**Comment by ross-spencer** [comment]
We have a few related Google issues around MYSQL too: 

* https://groups.google.com/d/msg/archivematica/SwnpgT8KyCM/U--QmQF0CwAJ
* https://groups.google.com/d/msg/archivematica/i_moK8xevKg/3QHFKSVqBAAJ
