### ISSUE TITLE
Problem: AIP METS generation fails when the Transcribe job runs

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#973]
**Expected behaviour**

The METS of an AIP is successfully created when the Transcribe job has run.

**Current behaviour**

If the `Transcribe` job is run on a `DemoTransferCSV`, the `Generate METS.xml document ` job fails like this:

![qa](https://user-images.githubusercontent.com/560781/68248870-48781880-ffe3-11e9-8a1e-1a33ad0da365.png)

This is how the `Generate METS.xml document ` job succeeds in 1.10:

![1 10](https://user-images.githubusercontent.com/560781/68249099-b6bcdb00-ffe3-11e9-9b3b-1c816faea08a.png)

**Steps to reproduce**

1. Run a `Standard` transfer of the `SampleTransfers/DemoTransferCSV` with:

  * `Perform file format identification (Transfer): Yes`
  * `Examine contents: Examine contents`
  * `Create SIP(s): Create single SIP and continue processing`
  * `Normalize: Normalize for preservation and access`
  * `Reminder: add metadata if desired: Continue`
  * `Transcribe files (OCR): Yes`

2. See the `Generate METS.xml document` job of the `Generate AIP METS` microservice fail.

**Your environment (version of Archivematica, operating system, other relevant details)**

Tested in `qa/1.x` and confirmed it's a regression using http://am110bionic.qa.archivematica.net/

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [x] All pull requests related to this issue are properly linked
- [x] All pull requests related to this issue have been merged
- [x] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [x] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
Investigated this a bit more and it seems the problem comes from the [package queuing PR](https://github.com/artefactual/archivematica/pull/1485) (but I can't tell why). Tested the previous commit and the AIP METS gets generated.

**Comment by ross-spencer** [comment]
Rationale for adding status `Blocked` is to indicate that we anticipate #955 once solved will resolve this, or at least will lead to solving this. #955 is still being investigated.

**Comment by ablwr** [comment]
Running into this now! It's quite a bad one because it really messes up my entire environment, even after rebuilding everything and flushing all of the data.

**Comment by ross-spencer** [comment]
I have written up an analysis of a related issue [here](https://github.com/archivematica/Issues/issues/955#issuecomment-571126909). This issue, #973, falls thoroughly under `Option 4: what have I missed?` in the #955 comment. 

While analysis of #955 shows that we likely don't need the MCP server to dynamically update its file list for partial reingest. For this issue we do. 

To explain...

There are two pathways we are discussing here:

1. We create an AIP without transcribe contents <-- **WORKS**
2. We create an AIP with transcribe contents <-- ***FAILS***

Which is pretty odd. So why does it happen?

In the first instance, transcribe contents can by definition add no additional files to the AIP package being created, therefore nothing is added to the database. All of our metadata files are yet to be added to the database. When the `Process metadata directory` job runs we load the metadata objects from disk and the microservice jobs run and then complete 👍.

Keep in mind, we load the file objects from disk only. 

In the second instance, transcribe contents adds one file. It is then added to the database [here](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/MCPClient/lib/clientScripts/transcribe_file.py#L52-L75) by the microservice job. This is problematic, because the files loaded from disk in the `Process metadata directory` job are never asked for by the MCP Server. [Here](https://github.com/artefactual/archivematica/blob/baf565e4abc3bcf9480ee0784734ce9b0b223f63/src/MCPServer/lib/server/packages.py#L683-L684) the generator is being returned based on only what is in the database. Where we need something more like the reload function discussed as not needed in #955: [here](https://github.com/archivematica/Issues/issues/955#issuecomment-571126909).

So in 2. we load the file objects purely from the database. We're only building half the picture of a package when processing...

@replaceafill describes the change that caused the issue nicely in [#955](https://github.com/archivematica/Issues/issues/955#issuecomment-568538717).

So how do we fix this?

#955 and this are similar but not quite the same but I think we should do the following:

1. Re-implement functionality to dynamically update the file list known to a package. (PR submitted but will look at adding testing).
2. Create a ticket to discuss optimizations for partial reingest (discussed in 955) including a new reingest workflow in `workflow.json` and also providing new context to microservice jobs to ensure we're not doing processing we don't need, i.e. processing an AIP METS file that doesn't need processing. 
3. Keep in mind that a clearer model of database interaction is something I believe Cole was working towards, and we should work towards in Archivematica, which might mean more changes to the MCP server, as well as creating cleaner MCP client interfaces and a separation of responsibilities.

**Comment by sallain** [comment]
This now works as expected. Tested on qa/1.x on Bionic.
